### ISSUE TITLE
CorDapp flows are not initialised if the node is started outside of the base dir

### ISSUE THREAD

**Issue by shamsasari** [corda/corda#1057]
If you start the node from outside the node's base directory:
`java -jar trader-demo/build/nodes/NotaryService/corda.jar --base-directory trader-demo/build/nodes/NotaryService`

The node is not able to initialise the flow classes it finds in the CorDapp JARs in the plugins dir.

```
[INFO ] 2017-07-17T10:32:07,132Z [main] internal.Node.scanCordapps - Scanning CorDapps in [/Users/shamsasari/git/corda/samples/trader-demo/build/nodes/NotaryService/plugins/trader-demo-0.14-SNAPSHOT.jar]
[WARN ] 2017-07-17T10:32:07,172Z [main] internal.Node.invoke - Unable to load class net.corda.traderdemo.flow.BuyerFlow
java.lang.ClassNotFoundException: net.corda.traderdemo.flow.BuyerFlow
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_131]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_131]
        at net.corda.node.internal.AbstractNode$getClassesWithAnnotation$1.invoke(AbstractNode.kt:466) [corda-node-0.14-SNAPSHOT.jar:?]
        at net.corda.node.internal.AbstractNode.getClassesWithAnnotation(AbstractNode.kt:477) [corda-node-0.14-SNAPSHOT.jar:?]
        at net.corda.node.internal.AbstractNode.registerInitiatedFlows(AbstractNode.kt:294) [corda-node-0.14-SNAPSHOT.jar:?]
        at net.corda.node.internal.AbstractNode.access$registerInitiatedFlows(AbstractNode.kt:100) [corda-node-0.14-SNAPSHOT.jar:?]
        at net.corda.node.internal.AbstractNode$start$2.invoke(AbstractNode.kt:204) [corda-node-0.14-SNAPSHOT.jar:?]
        at net.corda.node.internal.AbstractNode$start$2.invoke(AbstractNode.kt:100) [corda-node-0.14-SNAPSHOT.jar:?]
        at net.corda.node.internal.AbstractNode$initialiseDatabasePersistence$4.invoke(AbstractNode.kt:559) [corda-node-0.14-SNAPSHOT.jar:?]
        at net.corda.node.internal.AbstractNode$initialiseDatabasePersistence$4.invoke(AbstractNode.kt:100) [corda-node-0.14-SNAPSHOT.jar:?]
        at net.corda.node.utilities.CordaPersistence.inTopLevelTransaction(CordaPersistence.kt:67) [corda-node-0.14-SNAPSHOT.jar:?]
        at net.corda.node.utilities.CordaPersistence.transaction(CordaPersistence.kt:58) [corda-node-0.14-SNAPSHOT.jar:?]
        at net.corda.node.utilities.CordaPersistence.transaction(CordaPersistence.kt:48) [corda-node-0.14-SNAPSHOT.jar:?]
        at net.corda.node.internal.AbstractNode.initialiseDatabasePersistence(AbstractNode.kt:558) [corda-node-0.14-SNAPSHOT.jar:?]
        at net.corda.node.internal.Node.initialiseDatabasePersistence(Node.kt:291) [corda-node-0.14-SNAPSHOT.jar:?]
        at net.corda.node.internal.AbstractNode.start(AbstractNode.kt:172) [corda-node-0.14-SNAPSHOT.jar:?]
        at net.corda.node.internal.Node.start(Node.kt:297) [corda-node-0.14-SNAPSHOT.jar:?]
        at net.corda.node.internal.NodeStartup.startNode(NodeStartup.kt:103) [corda-node-0.14-SNAPSHOT.jar:?]
        at net.corda.node.internal.NodeStartup.run(NodeStartup.kt:81) [corda-node-0.14-SNAPSHOT.jar:?]
        at net.corda.node.Corda.main(Corda.kt:11) [corda-node-0.14-SNAPSHOT.jar:?]

```

Probably we're using a relative path somewhere in the classpath.

**Comment by shamsasari** [comment]
This is still an issue but seems to be a different reason: https://r3-cev.atlassian.net/browse/CORDA-1982
