### ISSUE TITLE
SIMM Valuation Demo exceptions in checkpointing and serialisation

### ISSUE THREAD

**Issue by Clintonio** [corda/corda#1158]
When running the SIMM valuation demo in current master or M14 there is an exception during the agree valuations flow;

     com.esotericsoftware.kryo.KryoException: java.lang.UnsupportedOperationException
     Serialization trace:
     dataObject (co.paralleluniverse.fibers.Stack)
     stack (net.corda.node.services.statemachine.FlowStateMachineImpl)
  	  	 at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:144)
  	  	 at com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.read(CompatibleFieldSerializer.java:147)
  	  	 at com.esotericsoftware.kryo.Kryo.readObjectOrNull(Kryo.java:782)
  	  	 at co.paralleluniverse.io.serialization.kryo.ReplaceableObjectKryo.readObjectOrNull(ReplaceableObjectKryo.java:107)
  	  	 at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:132)
  	  	 at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:540)
  	  	 at co.paralleluniverse.fibers.Fiber$FiberSerializer.read(Fiber.java:2091)
  	  	 at co.paralleluniverse.fibers.Fiber$FiberSerializer.read(Fiber.java:2021)
  	  	 at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
  	  	 at co.paralleluniverse.io.serialization.kryo.ReplaceableObjectKryo.readClassAndObject(ReplaceableObjectKryo.java:112)
  	  	 at net.corda.nodeapi.serialization.AbstractKryoSerializationScheme$deserialize$$inlined$use$lambda$1$1.invoke(SerializationScheme.kt:174)
  	  	 at net.corda.nodeapi.serialization.AbstractKryoSerializationScheme$deserialize$$inlined$use$lambda$1$1.invoke(SerializationScheme.kt:119)
  	  	 at net.corda.nodeapi.serialization.AbstractKryoSerializationScheme.withContext(SerializationScheme.kt:157)
  	  	 at net.corda.nodeapi.serialization.AbstractKryoSerializationScheme.access$withContext(SerializationScheme.kt:119)
  	  	 at net.corda.nodeapi.serialization.AbstractKryoSerializationScheme$deserialize$$inlined$use$lambda$1.execute(SerializationScheme.kt:171)
  	  	 at com.esotericsoftware.kryo.pool.KryoPoolQueueImpl.run(KryoPoolQueueImpl.java:61)
  	  	 at net.corda.nodeapi.serialization.AbstractKryoSerializationScheme.deserialize(SerializationScheme.kt:170)
  	  	 at net.corda.nodeapi.serialization.SerializationFactoryImpl.deserialize(SerializationScheme.kt:78)
  	  	 at net.corda.node.services.statemachine.StateMachineManager.deserializeFiber(StateMachineManager.kt:629)
  	  	 at net.corda.node.services.statemachine.StateMachineManager.access$deserializeFiber(StateMachineManager.kt:74)
  	  	 at net.corda.node.services.statemachine.StateMachineManager$updateCheckpoint$2.run(StateMachineManager.kt:497)
  	  	 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  	  	 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  	  	 at java.lang.Thread.run(Thread.java:745)
     Caused by: java.lang.UnsupportedOperationException
  	  	 at java.util.AbstractCollection.add(AbstractCollection.java:262)
  	  	 at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:134)
  	  	 at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:40)
  	  	 at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
  	  	 at co.paralleluniverse.io.serialization.kryo.ReplaceableObjectKryo.readObject(ReplaceableObjectKryo.java:92)
  	  	 at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:392)
  	  	 at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:303)
  	  	 at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
  	  	 at co.paralleluniverse.io.serialization.kryo.ReplaceableObjectKryo.readObject(ReplaceableObjectKryo.java:92)
  	  	 at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
  	  	 ... 23 more
     [ERROR] 14:15:34,878 [pool-7-thread-1] flow.[0540bb80-499f-45c6-9d32-41307a5b29da].deserializeFiber - Encountered unrestorable checkpoint!

This is repeated many times. The demo still appears to work and the tests pass.

**Comment by joeldudleyr3** [comment]
I'm closing this for now. If it can be replicated on Corda 3 or above, please re-open.
