### ISSUE TITLE
Cannot deserialize Copycat snapshot

### ISSUE THREAD

**Issue by Quiark** [corda/corda#1279]
I know this is because of the (recently added) serialization filter. Apparently copycat is using Java serialization and somewhere it clashes with the filter. This is what I got when I restarted a Raft node:

```
E 10:03:22+0000 [copycat-server-/138.197.221.45:10008-copycat-state] concurrent.SingleThreadContext.lambda$logFailure$2 - An uncaught exception occurred
 io.atomix.catalyst.serializer.SerializationException: failed to deserialize Java object
        at io.atomix.catalyst.serializer.util.JavaSerializableSerializer.read(JavaSerializableSerializer.java:57) ~[catalyst-serializer-1.1.2.jar:?]
        at io.atomix.catalyst.serializer.Serializer.readByClass(Serializer.java:1080) ~[catalyst-serializer-1.1.2.jar:?]
        at io.atomix.catalyst.serializer.Serializer.readObject(Serializer.java:1024) ~[catalyst-serializer-1.1.2.jar:?]
        at io.atomix.catalyst.serializer.Serializer.readObject(Serializer.java:981) ~[catalyst-serializer-1.1.2.jar:?]
        at io.atomix.copycat.server.storage.snapshot.SnapshotReader.readObject(SnapshotReader.java:71) ~[copycat-server-1.2.3.jar:?]
        at net.corda.node.services.transactions.DistributedImmutableMap$install$1.invoke(DistributedImmutableMap.kt:94) ~[corda-node-0.14.0.jar:?]
        at net.corda.node.services.transactions.DistributedImmutableMap$install$1.invoke(DistributedImmutableMap.kt:23) ~[corda-node-0.14.0.jar:?]
        at net.corda.node.utilities.CordaPersistence.inTopLevelTransaction(CordaPersistence.kt:67) ~[corda-node-0.14.0.jar:?]
        at net.corda.node.utilities.CordaPersistence.transaction(CordaPersistence.kt:58) ~[corda-node-0.14.0.jar:?]
        at net.corda.node.utilities.CordaPersistence.transaction(CordaPersistence.kt:48) ~[corda-node-0.14.0.jar:?]
        at net.corda.node.services.transactions.DistributedImmutableMap.install(DistributedImmutableMap.kt:90) ~[corda-node-0.14.0.jar:?]
        at io.atomix.copycat.server.state.ServerStateMachine.lambda$installSnapshot$69(ServerStateMachine.java:129) ~[copycat-server-1.2.3.jar:?]
        at io.atomix.catalyst.concurrent.Runnables.lambda$logFailure$2(Runnables.java:20) ~[catalyst-concurrent-1.1.2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_144]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.io.InvalidClassException: filter status: REJECTED
        at java.io.ObjectInputStream.filterCheck(ObjectInputStream.java:1244) ~[?:1.8.0_144]
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1836) ~[?:1.8.0_144]
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1713) ~[?:1.8.0_144]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2000) ~[?:1.8.0_144]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535) ~[?:1.8.0_144]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422) ~[?:1.8.0_144]
        at io.atomix.catalyst.serializer.util.JavaSerializableSerializer.read(JavaSerializableSerializer.java:52) ~[catalyst-serializer-1.1.2.jar:?]
        ... 19 more
```

**Comment by joeldudleyr3** [comment]
No longer an issue as of Corda 3+.
