### ISSUE TITLE
Lack of information about source of a problematic Artemis package in Corda logs

### ISSUE THREAD

**Issue by wawrzek** [corda/corda#1345]
I see following error message in Corda logs. 

Based on my experiences, that indicates versions mismatch. That make sense because the network with below error message were recently upgrade, but there was no way to enforce all nodes to upgrade.
The error message misses information about source of a problematic package, so the node owner can be contacted and inform about problem.

```
[ERROR] 2017-08-29T00:42:39,210Z [Thread-4 (activemq-netty-threads)] core.client.bufferReceived - AMQ214013: Failed to decode packet
java.lang.IndexOutOfBoundsException: readerIndex(21) + length(33622692) exceeds writerIndex(117): PooledUnsafeDirectByteBuf(ridx: 21, widx: 117, cap: 117)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1396) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1383) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:850) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:858) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.buffer.WrappedByteBuf.readBytes(WrappedByteBuf.java:649) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at org.apache.activemq.artemis.api.core.SimpleString.readSimpleString(SimpleString.java:150) ~[artemis-commons-2.1.0.jar:2.1.0]
	at org.apache.activemq.artemis.core.buffers.impl.ChannelBufferWrapper.readStringInternal(ChannelBufferWrapper.java:103) ~[artemis-commons-2.1.0.jar:2.1.0]
	at org.apache.activemq.artemis.core.buffers.impl.ChannelBufferWrapper.readString(ChannelBufferWrapper.java:88) ~[artemis-commons-2.1.0.jar:2.1.0]
	at org.apache.activemq.artemis.core.protocol.core.impl.wireformat.SessionAddMetaDataMessageV2.decodeRest(SessionAddMetaDataMessageV2.java:72) ~[artemis-core-client-2.1.0.jar:2.1.0]
	at org.apache.activemq.artemis.core.protocol.core.impl.PacketImpl.decode(PacketImpl.java:344) ~[artemis-core-client-2.1.0.jar:2.1.0]
	at org.apache.activemq.artemis.core.protocol.ServerPacketDecoder.decode(ServerPacketDecoder.java:206) ~[artemis-server-2.1.0.jar:2.1.0]
	at org.apache.activemq.artemis.core.protocol.core.impl.RemotingConnectionImpl.bufferReceived(RemotingConnectionImpl.java:355) [artemis-core-client-2.1.0.jar:2.1.0]
	at org.apache.activemq.artemis.core.remoting.server.impl.RemotingServiceImpl$DelegatingBufferHandler.bufferReceived(RemotingServiceImpl.java:631) [artemis-server-2.1.0.jar:2.1.0]
	at org.apache.activemq.artemis.core.remoting.impl.netty.ActiveMQChannelHandler.channelRead(ActiveMQChannelHandler.java:69) [artemis-core-client-2.1.0.jar:2.1.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:219) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:631) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:468) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:428) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at org.apache.activemq.artemis.core.protocol.ProtocolHandler$ProtocolDecoder.decode(ProtocolHandler.java:186) [artemis-server-2.1.0.jar:2.1.0]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at org.apache.activemq.artemis.core.protocol.ProtocolHandler$ProtocolDecoder.channelRead(ProtocolHandler.java:128) [artemis-server-2.1.0.jar:2.1.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1017) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

The log has low "information density", so below I see following lines with *XX.YYY.ZZZ.OO* IP address. I can be quite sure that's the source of the problem. In more realistic scenario that might be hard, because I don't see a way to link message. 

```
[WARN ] 2017-08-29T00:42:39,222Z [Thread-4 (activemq-netty-threads)] core.client.fail - AMQ212037: Connection failure has been detected: java.lang.IndexOutOfBoundsException: readerIndex(21) + length(33622692) exceeds writerIndex(117): PooledUnsafeDirectByteBuf(ridx: 21, widx: 117, cap: 117) [code=GENERIC_EXCEPTION]
[WARN ] 2017-08-29T00:43:00,949Z [Thread-0 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$3@77925f76)] core.client.fail - AMQ212037: Connection failure has been detected: AMQ119014: Did not receive data from /XX.YYY.ZZZ.OO:31938 within the 60,000ms connection TTL. The connection will now be closed. [code=CONNECTION_TIMEDOUT]
```

**Comment by mikehearn** [comment]
That looks like Artemis itself broke its own wire compatibility. There isn't even any Corda code on the stack. We should resolve this sort of problem as part of switching to AMQP between nodes.

**Comment by mikehearn** [comment]
We switched to AMQP between nodes in Corda 3 and I don't think we've seen this sort of error since.
