### ISSUE TITLE
Cannot send int primitives in flows in Java.

### ISSUE THREAD

**Issue by joeldudleyr3** [corda/corda#1400]
In M16-SNAPSHOT (01/09/2017), I was trying to do the following:

```
package com.template.flow;

import co.paralleluniverse.fibers.Suspendable;
import net.corda.core.flows.FlowLogic;
import net.corda.core.flows.InitiatedBy;
import net.corda.core.flows.InitiatingFlow;
import net.corda.core.flows.StartableByRPC;
import net.corda.core.identity.Party;
import net.corda.core.utilities.ProgressTracker;
import org.jetbrains.annotations.Nullable;

/**
 * Define your flow here.
 */
public class TemplateFlow {
    /**
     * You can add a constructor to each FlowLogic subclass to pass objects into the flow.
     */
    @InitiatingFlow
    @StartableByRPC
    public static class Initiator extends FlowLogic<Void> {
        private final ProgressTracker progressTracker = new ProgressTracker();

        @Override
        public ProgressTracker getProgressTracker() {
            return progressTracker;
        }

        /**
         * Define the initiator's flow logic here.
         */
        @Suspendable
        @Override public Void call() {
            Party counterparty = getServiceHub().getNetworkMapCache().getPartyNodes().get(0).getLegalIdentity();
            sendAndReceive(int.class, counterparty, 3);
            return null;
        }
    }

    @InitiatedBy(Initiator.class)
    public static class Responder extends FlowLogic<Void> {
        private Party counterparty;

        public Responder(Party counterparty) {
            this.counterparty = counterparty;
        }

        /**
         * Define the acceptor's flow logic here.
         */
        @Suspendable
        @Override
        public Void call() {
            receive(int.class, counterparty);
            send(counterparty, 3);
            return null;
        }
    }
}
```

But it gave me the following error message:

```
E 22:15:33+0100 [pool-7-thread-1] flow.[bd038145-812d-4da7-a9da-e0edde2d8c11].deserializeFiber - Encountered unrestorable checkpoint!
 java.lang.ClassNotFoundException: int
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_131]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_131]
	at net.corda.nodeapi.internal.serialization.ClassSerializer.read(Kryo.kt:520) ~[corda-node-api-0.16-SNAPSHOT.jar:?]
	at net.corda.nodeapi.internal.serialization.ClassSerializer.read(Kryo.kt:517) ~[corda-node-api-0.16-SNAPSHOT.jar:?]
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731) ~[kryo-4.0.0.jar:?]
	at co.paralleluniverse.io.serialization.kryo.ReplaceableObjectKryo.readObject(ReplaceableObjectKryo.java:92) ~[quasar-core-0.7.9-jdk8.jar:0.7.9]
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:392) ~[kryo-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:303) ~[kryo-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731) ~[kryo-4.0.0.jar:?]
	at co.paralleluniverse.io.serialization.kryo.ReplaceableObjectKryo.readObject(ReplaceableObjectKryo.java:92) ~[quasar-core-0.7.9-jdk8.jar:0.7.9]
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125) ~[kryo-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.read(CompatibleFieldSerializer.java:147) ~[kryo-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.readObjectOrNull(Kryo.java:782) ~[kryo-4.0.0.jar:?]
	at co.paralleluniverse.io.serialization.kryo.ReplaceableObjectKryo.readObjectOrNull(ReplaceableObjectKryo.java:107) ~[quasar-core-0.7.9-jdk8.jar:0.7.9]
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:132) ~[kryo-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:540) ~[kryo-4.0.0.jar:?]
	at co.paralleluniverse.fibers.Fiber$FiberSerializer.read(Fiber.java:2137) ~[quasar-core-0.7.9-jdk8.jar:0.7.9]
	at co.paralleluniverse.fibers.Fiber$FiberSerializer.read(Fiber.java:2067) ~[quasar-core-0.7.9-jdk8.jar:0.7.9]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813) ~[kryo-4.0.0.jar:?]
	at co.paralleluniverse.io.serialization.kryo.ReplaceableObjectKryo.readClassAndObject(ReplaceableObjectKryo.java:112) ~[quasar-core-0.7.9-jdk8.jar:0.7.9]
	at net.corda.nodeapi.internal.serialization.AbstractKryoSerializationScheme$deserialize$$inlined$use$lambda$1$1.invoke(SerializationScheme.kt:170) ~[corda-node-api-0.16-SNAPSHOT.jar:?]
	at net.corda.nodeapi.internal.serialization.AbstractKryoSerializationScheme$deserialize$$inlined$use$lambda$1$1.invoke(SerializationScheme.kt:114) ~[corda-node-api-0.16-SNAPSHOT.jar:?]
	at net.corda.nodeapi.internal.serialization.AbstractKryoSerializationScheme.withContext(SerializationScheme.kt:152) ~[corda-node-api-0.16-SNAPSHOT.jar:?]
	at net.corda.nodeapi.internal.serialization.AbstractKryoSerializationScheme.access$withContext(SerializationScheme.kt:114) ~[corda-node-api-0.16-SNAPSHOT.jar:?]
	at net.corda.nodeapi.internal.serialization.AbstractKryoSerializationScheme$deserialize$$inlined$use$lambda$1.execute(SerializationScheme.kt:167) ~[corda-node-api-0.16-SNAPSHOT.jar:?]
	at com.esotericsoftware.kryo.pool.KryoPoolQueueImpl.run(KryoPoolQueueImpl.java:61) ~[kryo-4.0.0.jar:?]
	at net.corda.nodeapi.internal.serialization.AbstractKryoSerializationScheme.deserialize(SerializationScheme.kt:166) ~[corda-node-api-0.16-SNAPSHOT.jar:?]
	at net.corda.nodeapi.internal.serialization.SerializationFactoryImpl.deserialize(SerializationScheme.kt:78) ~[corda-node-api-0.16-SNAPSHOT.jar:?]
	at net.corda.node.services.statemachine.StateMachineManager.deserializeFiber(StateMachineManager.kt:681) [corda-node-0.16-SNAPSHOT.jar:?]
	at net.corda.node.services.statemachine.StateMachineManager.access$deserializeFiber(StateMachineManager.kt:77) [corda-node-0.16-SNAPSHOT.jar:?]
	at net.corda.node.services.statemachine.StateMachineManager$updateCheckpoint$2.run(StateMachineManager.kt:542) [corda-node-0.16-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by rick-r3** [comment]
Send an `Integer` instead.

**Comment by joeldudleyr3** [comment]
Fair, but:
1. It's not a very friendly error message
2. Why can't we autobox it instead of throwing an error?

**Comment by rick-r3** [comment]
We could check that the object you supply is of the type you specify.  Which it isn't in this case since you supply an `Integer` (3) and it isn't a subclass of `int.class`.  So fair enough, we could give a message for user error.

**Comment by joeldudleyr3** [comment]
Yeah, my problem is that the error doesn't really correspond to the error message, that's all.
