### ISSUE TITLE
Samples fail in various ways

### ISSUE THREAD

**Issue by exFalso** [corda/corda#1468]
#### BFT notary demo node fails

To repro: 

```
./gradlew samples:notary-demo:deployNodes
./samples/notary-demo/build/nodes/nodesBFT/runnodes
```
The R3Ltd node keeps printing
```
re-connecting to replica 1 at /127.0.0.1:11010
re-connecting to replica 2 at /127.0.0.1:11020
re-connecting to replica 3 at /127.0.0.1:11030
```

#### Simm valuation demo node fails on startup

To repro:
```
./gradlew samples:simm-valuation-demo:deployNodes
./samples/simm-valuation-demo/build/nodes/runnodes
```
BankC will fail with
```

E 10:20:58+0100 [main] internal.Node.run - Exception during node startup
 java.lang.IllegalArgumentException: Invalid country 'Japan' Country code must be 2 letters ISO code 
        at net.corda.core.utilities.LegalNameValidator.validateX500Name(LegalNameValidator.kt:78) ~[corda-core-0.16-SNAPSHOT.jar:?]
        at net.corda.core.utilities.X500NameUtils.toWellFormattedName(X500NameUtils.kt:54) ~[corda-core-0.16-SNAPSHOT.jar:?]
        at net.corda.node.services.config.ConfigUtilitiesKt.createKeystoreForCordaNode(ConfigUtilities.kt:91) ~[corda-node-0.16-SNAPSHOT.jar:?]
        at net.corda.node.services.config.ConfigUtilitiesKt.createKeystoreForCordaNode$default(ConfigUtilities.kt:85) ~[corda-node-0.16-SNAPSHOT.jar:?]
        at net.corda.node.services.config.ConfigUtilitiesKt.configureDevKeyAndTrustStores(ConfigUtilities.kt:63) ~[corda-node-0.16-SNAPSHOT.jar:?]
        at net.corda.node.services.config.ConfigUtilitiesKt.configureWithDevSSLCertificate(ConfigUtilities.kt:54) ~[corda-node-0.16-SNAPSHOT.jar:?]
        at net.corda.node.internal.AbstractNode.start(AbstractNode.kt:172) ~[corda-node-0.16-SNAPSHOT.jar:?]
        at net.corda.node.internal.Node.start(Node.kt:309) ~[corda-node-0.16-SNAPSHOT.jar:?]
        at net.corda.node.internal.NodeStartup.startNode(NodeStartup.kt:97) ~[corda-node-0.16-SNAPSHOT.jar:?]
        at net.corda.node.internal.NodeStartup.run(NodeStartup.kt:75) [corda-node-0.16-SNAPSHOT.jar:?]
        at net.corda.node.Corda.main(Corda.kt:11) [corda-node-0.16-SNAPSHOT.jar:?]
```

#### Bank of Corda demo fails

To repro:

```
./gradlew samples:bank-of-corda-demo:deployNodes
./samples/bank-of-corda-demo/build/nodes/runnodes
./gradlew samples:bank-of-corda-demo:runWebCashIssue
```
Prints
```
Requesting Cash via Web ...
[ERROR] 10:32:10,570 [main] (HttpUtils.kt:48) http.HttpUtils.makeRequest - Could not fulfill HTTP request of type POST to http://localhost:10007/api/bank/issue-asset-request. Status Code: 403. Message: Unable to locate C=GB,L=London,O=BankOfCorda in identity service
```

**Comment by GavT** [comment]
I would like to see @mat-rizzo-r3 write smoke tests for this

**Comment by fenryka** [comment]
@cburlinchon this is a repeat of the slack message, but please let me know when the fix is made and merged as I'll cherry pick it for M15
