### ISSUE TITLE
Confusing error message when RAFT cluster started without shared certificate

### ISSUE THREAD

**Issue by joeldudleyr3** [corda/corda#1896]
See https://stackoverflow.com/questions/46783276/corda-v1-0-notary-clusters-config-issue-with-gradle.

If a RAFT notary cluster is started without a shared certificate, it will output the following error message, which gives no indication of the cause of the issue:

**[ERROR] 2017-10-17T05:42:31,180Z [main] identity.PersistentIdentityService.verifyAndRegisterIdentity - name constraints check failed [ERROR] 2017-10-17T05:42:31,181Z [main] identity.PersistentIdentityService.verifyAndRegisterIdentity - Path = [ERROR] 2017-10-17T05:42:31,181Z [main] identity.PersistentIdentityService.verifyAndRegisterIdentity - CN=Corda Node Root CA,O=R3,OU=corda,L=London,C=UK [ERROR] 2017-10-17T05:42:31,182Z [main] identity.PersistentIdentityService.verifyAndRegisterIdentity - CN=Corda Node Intermediate CA,O=R3,OU=corda,L=London,C=UK [ERROR] 2017-10-17T05:42:31,184Z [main] identity.PersistentIdentityService.verifyAndRegisterIdentity - C=CH,L=Zurich,O=NotaryService0,CN=Corda Client CA Certificate [ERROR] 2017-10-17T05:42:31,185Z [main] identity.PersistentIdentityService.verifyAndRegisterIdentity - C=CH,L=Zurich,O=Raft,CN=corda.notary.validating.raft [ERROR] 2017-10-17T05:42:31,189Z [main] internal.Node.run - Exception during node startup rx.exceptions.OnErrorNotImplementedException: name constraints check failed at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386) ~[rxjava-1.2.4.jar:1.2.4] at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383) ~[rxjava-1.2.4.jar:1.2.4] at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44) ~[rxjava-1.2.4.jar:1.2.4] at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153) ~[rxjava-1.2.4.jar:1.2.4] at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115) ~[rxjava-1.2.4.jar:1.2.4] at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:216) ~[rxjava-1.2.4.jar:1.2.4] at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139) ~[rxjava-1.2.4.jar:1.2.4] at rx.observers.Subscribers$5.onNext(Subscribers.java:235) ~[rxjava-1.2.4.jar:1.2.4] at net.corda.node.utilities.DatabaseTransactionWrappingSubscriber$onNext$1.invoke(CordaPersistence.kt:159) ~[corda-node-1.0.0.jar:?] at net.corda.node.utilities.DatabaseTransactionWrappingSubscriber$onNext$1.invoke(CordaPersistence.kt:143) ~[corda-node-1.0.0.jar:?] at net.corda.node.utilities.DatabaseTransactionWrappingSubscriber$forEachSubscriberWithDbTx$1.invoke(CordaPersistence.kt:150) ~[corda-node-1.0.0.jar:?] at net.corda.node.utilities.DatabaseTransactionWrappingSubscriber$forEachSubscriberWithDbTx$1.invoke(CordaPersistence.kt:143) ~[corda-node-1.0.0.jar:?] at net.corda.node.utilities.CordaPersistence.inTopLevelTransaction(CordaPersistence.kt:84) ~[corda-node-1.0.0.jar:?] at net.corda.node.utilities.CordaPersistence.transaction(CordaPersistence.kt:75) ~[corda-node-1.0.0.jar:?] at net.corda.node.utilities.CordaPersistence.transaction(CordaPersistence.kt:65) ~[corda-node-1.0.0.jar:?] at net.corda.node.utilities.DatabaseTransactionWrappingSubscriber.forEachSubscriberWithDbTx(CordaPersistence.kt:148) ~[corda-node-1.0.0.jar:?] at net.corda.node.utilities.DatabaseTransactionWrappingSubscriber.onNext(CordaPersistence.kt:159) ~[corda-node-1.0.0.jar:?] at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304) ~[rxjava-1.2.4.jar:1.2.4] at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219) ~[rxjava-1.2.4.jar:1.2.4] at rx.subjects.PublishSubject.onNext(PublishSubject.java:72) ~[rxjava-1.2.4.jar:1.2.4] at rx.internal.util.ObserverSubscriber.onNext(ObserverSubscriber.java:34) ~[rxjava-1.2.4.jar:1.2.4] at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134) ~[rxjava-1.2.4.jar:1.2.4] at rx.observers.Subscribers$5.onNext(Subscribers.java:235) ~[rxjava-1.2.4.jar:1.2.4] at rx.subjects.UnicastSubject$State.replay(UnicastSubject.java:295) ~[rxjava-1.2.4.jar:1.2.4] at rx.subjects.UnicastSubject$State.request(UnicastSubject.java:237) ~[rxjava-1.2.4.jar:1.2.4] at rx.Subscriber.setProducer(Subscriber.java:209) ~[rxjava-1.2.4.jar:1.2.4] at rx.Subscriber.setProducer(Subscriber.java:205) ~[rxjava-1.2.4.jar:1.2.4] at rx.Subscriber.setProducer(Subscriber.java:205) ~[rxjava-1.2.4.jar:1.2.4] at rx.subjects.UnicastSubject$State.call(UnicastSubject.java:252) ~[rxjava-1.2.4.jar:1.2.4] at rx.subjects.UnicastSubject$State.call(UnicastSubject.java:115) ~[rxjava-1.2.4.jar:1.2.4] at rx.Observable.unsafeSubscribe(Observable.java:10142) ~[rxjava-1.2.4.jar:1.2.4] at rx.internal.operators.OnSubscribeDelaySubscriptionOther$1.onCompleted(OnSubscribeDelaySubscriptionOther.java:74) ~[rxjava-1.2.4.jar:1.2.4] at rx.internal.operators.OnSubscribeDelaySubscriptionOther$1.onNext(OnSubscribeDelaySubscriptionOther.java:53) ~[rxjava-1.2.4.jar:1.2.4] at rx.internal.producers.SingleProducer.request(SingleProducer.java:65) ~[rxjava-1.2.4.jar:1.2.4] at rx.Subscriber.setProducer(Subscriber.java:209) ~[rxjava-1.2.4.jar:1.2.4] at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:110) ~[rxjava-1.2.4.jar:1.2.4] at rx.internal.operators.OperatorTake$1.onNext(OperatorTake.java:80) ~[rxjava-1.2.4.jar:1.2.4] at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76) ~[rxjava-1.2.4.jar:1.2.4] at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304) ~[rxjava-1.2.4.jar:1.2.4] at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219) ~[rxjava-1.2.4.jar:1.2.4] at rx.subjects.PublishSubject.onNext(PublishSubject.java:72) ~[rxjava-1.2.4.jar:1.2.4] at rx.observers.SerializedObserver.onNext(SerializedObserver.java:91) ~[rxjava-1.2.4.jar:1.2.4] at rx.subjects.SerializedSubject.onNext(SerializedSubject.java:67) ~[rxjava-1.2.4.jar:1.2.4] at net.corda.node.utilities.DatabaseTransaction.close(DatabaseTransactionManager.kt:60) ~[corda-node-1.0.0.jar:?] at net.corda.node.utilities.CordaPersistence.inTopLevelTransaction(CordaPersistence.kt:100) ~[corda-node-1.0.0.jar:?] at net.corda.node.utilities.CordaPersistence.transaction(CordaPersistence.kt:75) ~[corda-node-1.0.0.jar:?] at net.corda.node.utilities.CordaPersistence.transaction(CordaPersistence.kt:65) ~[corda-node-1.0.0.jar:?] at net.corda.node.services.network.PersistentNetworkMapCache.addNode(PersistentNetworkMapCache.kt:163) ~[corda-node-1.0.0.jar:?] at net.corda.node.internal.AbstractNode.registerWithNetworkMapIfConfigured(AbstractNode.kt:511) ~[corda-node-1.0.0.jar:?] at net.corda.node.internal.AbstractNode.start(AbstractNode.kt:220) ~[corda-node-1.0.0.jar:?] at net.corda.node.internal.Node.start(Node.kt:312) ~[corda-node-1.0.0.jar:?] at net.corda.node.internal.NodeStartup.startNode(NodeStartup.kt:95) ~[corda-node-1.0.0.jar:?] at net.corda.node.internal.NodeStartup.run(NodeStartup.kt:74) [corda-node-1.0.0.jar:?] at net.corda.node.Corda.main(Corda.kt:11) [corda-node-1.0.0.jar:?] Caused by: java.security.cert.CertPathValidatorException: name constraints check failed**

**Comment by joeldudleyr3** [comment]
Confirmed this is no longer relevant as of Corda 3.
