### ISSUE TITLE
CordaRPCClientTest throws (K)NPE

### ISSUE THREAD

**Issue by rick-r3** [corda/corda#269]
This looks timing related and seems to be happening on my PR branch but does not reproduce individually.  My high level assessment of this is that there's an attempt to notify an RPC client of a flow progress via the ProgressTracker but the node is in the process of shutdown and has nulled out the messaging producer as part of message shutdown.  We should silently swallow I suspect.

Exception in thread "Node thread" rx.exceptions.OnErrorNotImplementedException: kotlin.KotlinNullPointerException
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:216)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
	at rx.internal.operators.OperatorMaterialize$ParentSubscriber.onNext(OperatorMaterialize.java:112)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304)
	at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219)
	at rx.subjects.PublishSubject.onNext(PublishSubject.java:72)
	at net.corda.core.utilities.ProgressTracker.setCurrentStep(ProgressTracker.kt:133)
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:114)
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:33)
	at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1067)
	at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:767)
	at co.paralleluniverse.fibers.RunnableFiberTask.doExec(RunnableFiberTask.java:100)
	at co.paralleluniverse.fibers.RunnableFiberTask.run(RunnableFiberTask.java:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at net.corda.node.utilities.AffinityExecutor$ServiceAffinityExecutor$1$thread$1.run(AffinityExecutor.kt:67)
Caused by: java.util.concurrent.ExecutionException: kotlin.KotlinNullPointerException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at net.corda.node.utilities.AffinityExecutor$DefaultImpls.fetchFrom(AffinityExecutor.kt:41)
	at net.corda.node.utilities.AffinityExecutor$ServiceAffinityExecutor.fetchFrom(AffinityExecutor.kt:53)
	at net.corda.node.services.messaging.NodeMessagingClient$createRPCDispatcher$1.send(NodeMessagingClient.kt:447)
	at net.corda.node.services.messaging.RPCDispatcher$ObservableSerializer$write$subscription$1.call(RPCDispatcher.kt:69)
	at net.corda.node.services.messaging.RPCDispatcher$ObservableSerializer$write$subscription$1.call(RPCDispatcher.kt:52)
	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
	... 15 more
Caused by: kotlin.KotlinNullPointerException
	at net.corda.node.services.messaging.NodeMessagingClient$createRPCDispatcher$1$send$1.invoke(NodeMessagingClient.kt:454)
	at net.corda.node.services.messaging.NodeMessagingClient$createRPCDispatcher$1$send$1.invoke(NodeMessagingClient.kt:445)
	at net.corda.node.utilities.AffinityExecutor$fetchFrom$1.get(AffinityExecutor.kt:41)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	... 3 more

**Comment by mikehearn** [comment]
We could swallow it, but the issue here is more like the RPC dispatcher not being properly integrated into the shutdown sequence. I think the fix here is perhaps to move rpcConsumer.close() up above the shutdownLatch.wait() in NodeMessagingClient.stop().

Basically, what we need to do is stop processing of new inbound RPCs, then wait for existing in-flight RPCs to finish, then proceed with the shutdown of the server. That way every client gets a response. Special attention must be paid to the case where it's an RPC that's triggering shutdown or where an RPC might hang for a long time (ideally we avoid having any of those).
