### ISSUE TITLE
java.io.IOException: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by zhangxin20180402** [corda/corda#2904]
Windows10
JDK1.8

[WARN ] 2018-04-02T05:56:13,827Z [nioEventLoopGroup-2-1] channel.DefaultChannelPipeline.warn - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception. {}
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_141]
	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_141]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_141]
	at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_141]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_141]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
[INFO ] 2018-04-02T05:56:13,843Z [nioEventLoopGroup-2-1] netty.AMQPClient.operationComplete - Disconnected from [2001:0:9d38:6ab8:20d4:3d5:95d9:ff95]:10008 {}

**Comment by zhangxin20180402** [comment]
For the tast deployNodes, using the IP address instead of localhost, seems it has something with IPV6 implementation on windows 10
