### ISSUE TITLE
Performance limitation

### ISSUE THREAD

**Issue by adubrovs** [corda/corda#2946]
In our envirement we observe that the performance of validating notary nodes is severely limited by the method `hashCode` in `OpaqueBytes`. Here is the typical stacktrace:
```
java.lang.Thread.State: RUNNABLE
        at net.corda.core.utilities.OpaqueBytes.getBytes(ByteArrays.kt:143)
        at net.corda.core.utilities.ByteSequence.hashCode(ByteArrays.kt:107)
        at net.corda.core.transactions.SignedTransaction.hashCode(SignedTransaction.kt)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.put(HashMap.java:612)
        at java.util.HashSet.add(HashSet.java:220)
        at net.corda.core.internal.ResolveTransactionsFlow$Companion.topologicalSort(ResolveTransactionsFlow.kt:44)
        at net.corda.core.internal.ResolveTransactionsFlow.call(ResolveTransactionsFlow.kt:90)
        at net.corda.core.internal.ResolveTransactionsFlow.call(ResolveTransactionsFlow.kt:21)
        at net.corda.core.flows.FlowLogic.subFlow(FlowLogic.kt:243)
        at net.corda.core.flows.ReceiveTransactionFlow.call(ReceiveTransactionFlow.kt:46)
        at net.corda.core.flows.ReceiveTransactionFlow.call(ReceiveTransactionFlow.kt:24)
        at net.corda.core.flows.FlowLogic.subFlow(FlowLogic.kt:243)
        at net.corda.node.services.transactions.ValidatingNotaryFlow.receiveAndVerifyTx(ValidatingNotaryFlow.kt:25)
        at net.corda.core.flows.NotaryFlow$Service.call(NotaryFlow.kt:123)
        at net.corda.core.flows.NotaryFlow$Service.call(NotaryFlow.kt:119)
        at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:96)
        at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:41)
        at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1092)
        at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:788)
        at co.paralleluniverse.fibers.RunnableFiberTask.doExec(RunnableFiberTask.java:100)
        at co.paralleluniverse.fibers.RunnableFiberTask.run(RunnableFiberTask.java:91)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at net.corda.node.utilities.AffinityExecutor$ServiceAffinityExecutor$1$thread$1.run(AffinityExecutor.kt:69)
```

From the sources code of `OpaqueBytes` it becomes apparent, that, each time when `ByteSequence` checks the hashcode of bytes, `OpaqueBytes` clones the entire buffer in the following method `OpaqueBytes::get`:
```
open class OpaqueBytes(bytes: ByteArray) : ByteSequence(bytes, 0, bytes.size) {
    companion object {
        /**
         * Create [OpaqueBytes] from a sequence of [Byte] values.
         */
        @JvmStatic
        fun of(vararg b: Byte) = OpaqueBytes(byteArrayOf(*b))
    }

    init {
        require(bytes.isNotEmpty())
    }

    /**
     * The bytes are always cloned so that this object becomes immutable. This has been done
     * to prevent tampering with entities such as [net.corda.core.crypto.SecureHash] and [net.corda.core.contracts.PrivacySalt], as well as
     * preserve the integrity of our hash constants [net.corda.core.crypto.SecureHash.zeroHash] and [net.corda.core.crypto.SecureHash.allOnesHash].
     *
     * Cloning like this may become a performance issue, depending on whether or not the JIT
     * compiler is ever able to optimise away the clone. In which case we may need to revisit
     * this later.
     */
    override final val bytes: ByteArray = bytes
        get() = field.clone()
}
```

**Comment by rick-r3** [comment]
Already fixed in 3.0.
