### ISSUE TITLE
Recording a transaction that has already been recorded fails with an exception

### ISSUE THREAD

**Issue by marioschlipf** [corda/corda#3188]
We are currently looking into upgrading our application to Corda V3.1 from Corda V2.

One of our tests where we are using the SendTransactionFlow failed with a hibernate exception.
It turned out that calling ServiceHub.recordTransaction fails if the transaction has already been recorded.

The Stacktrace looks like this:
```rx.exceptions.OnErrorNotImplementedException: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:216)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
	at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304)
	at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219)
	at rx.subjects.PublishSubject.onNext(PublishSubject.java:72)
	at rx.internal.util.ObserverSubscriber.onNext(ObserverSubscriber.java:34)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
	at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304)
	at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219)
	at rx.subjects.PublishSubject.onNext(PublishSubject.java:72)
	at net.corda.node.services.vault.NodeVaultService.processAndNotify(NodeVaultService.kt:203)
	at net.corda.node.services.vault.NodeVaultService.access$processAndNotify(NodeVaultService.kt:47)
	at net.corda.node.services.vault.NodeVaultService$notifyAll$1.invoke(NodeVaultService.kt:116)
	at net.corda.node.services.vault.NodeVaultService.notifyAll(NodeVaultService.kt:126)
	at net.corda.node.services.api.ServiceHubInternal$DefaultImpls.recordTransactions(ServiceHubInternal.kt:118)
	at net.corda.node.internal.AbstractNode$ServiceHubInternalImpl$recordTransactions$1.invoke(AbstractNode.kt:847)
	at net.corda.node.internal.AbstractNode$ServiceHubInternalImpl$recordTransactions$1.invoke(AbstractNode.kt:808)
	at net.corda.nodeapi.internal.persistence.CordaPersistence.inTopLevelTransaction(CordaPersistence.kt:148)
	at net.corda.nodeapi.internal.persistence.CordaPersistence.transaction(CordaPersistence.kt:134)
	at net.corda.nodeapi.internal.persistence.CordaPersistence.transaction(CordaPersistence.kt:120)
	at net.corda.nodeapi.internal.persistence.CordaPersistence.transaction(CordaPersistence.kt:127)
	at net.corda.node.internal.AbstractNode$ServiceHubInternalImpl.recordTransactions(AbstractNode.kt:846)
	at net.corda.core.node.ServiceHub$DefaultImpls.recordTransactions(ServiceHub.kt:201)
	at net.corda.node.services.api.ServiceHubInternal$DefaultImpls.recordTransactions(ServiceHubInternal.kt)
	at net.corda.node.internal.AbstractNode$ServiceHubInternalImpl.recordTransactions(AbstractNode.kt:808)
	at net.corda.core.node.ServiceHub$DefaultImpls.recordTransactions(ServiceHub.kt:193)
	at net.corda.node.services.api.ServiceHubInternal$DefaultImpls.recordTransactions(ServiceHubInternal.kt)
	at net.corda.node.internal.AbstractNode$ServiceHubInternalImpl.recordTransactions(AbstractNode.kt:808)
	at net.corda.node.internal.AbstractNode$StartedNodeImpl$services$1.recordTransactions(AbstractNode.kt)
	at com.test.flow.DuplicateTransactionRecordingBug.bug(DuplicateTransactionRecordingBug.kt:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:147)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:155)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:162)
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1434)
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1414)
	at net.corda.node.services.schema.HibernateObserver.persistStatesWithSchema$node(HibernateObserver.kt:66)
	at net.corda.node.services.schema.HibernateObserver.persist(HibernateObserver.kt:50)
	at net.corda.node.services.schema.HibernateObserver.access$persist(HibernateObserver.kt:29)
	at net.corda.node.services.schema.HibernateObserver$Companion$install$1.call(HibernateObserver.kt:34)
	at net.corda.node.services.schema.HibernateObserver$Companion$install$1.call(HibernateObserver.kt:30)
	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
	... 52 more
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:112)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:97)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:207)
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:45)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3001)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3501)
	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:89)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:586)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:460)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:337)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1428)
	... 60 more
Caused by: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY_KEY_62 ON PUBLIC.VAULT_LINEAR_STATES(OUTPUT_INDEX, TRANSACTION_ID) VALUES (0, '7B4F6D8E143D2582E60734E5F4199185A71DCF143B9C07341194F4885EEBF657', 1)"; SQL statement:
insert into vault_linear_states (external_id, uuid, output_index, transaction_id) values (?, ?, ?, ?) [23505-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:103)
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:231)
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:190)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:707)
	at org.h2.command.dml.Insert.insertRows(Insert.java:156)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:160)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:146)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:204)
	... 69 more
```

I created a small example to reproduce the issue:

```
class TestContract : Contract {
    override fun verify(tx: LedgerTransaction) {}
    interface Commands : CommandData {
        class Issue : Commands
    }
}

class TestState(val owner: Party, override val linearId: UniqueIdentifier = UniqueIdentifier()) : LinearState {
    override val participants get() = listOf(owner)
}

class DuplicateTransactionRecordingBug {
    private lateinit var mockNet: MockNetwork
    private lateinit var node1: StartedMockNode

    @Before
    fun setup() {
        mockNet = MockNetwork(cordappPackages = listOf("com.test.flow"))
        node1 = mockNet.createPartyNode(CordaX500Name("Party 1", "Amsterdam", "NL"))
        mockNet.runNetwork()
    }

    @After
    fun tearDown() {
        mockNet.stopNodes()
    }

    @Test
    fun bug() {
        val me = node1.info.legalIdentities.first()
        val notary = mockNet.defaultNotaryIdentity
        mockNet.runNetwork()

        val tx = TransactionBuilder(notary).run {
            addCommand(TestContract.Commands.Issue(), me.owningKey)
            addOutputState(TestState(me), contractName<TestContract>())
            sign(node1.services)
        }

        node1.services.recordTransactions(tx)
        node1.services.recordTransactions(tx)
    }
}
```

Note that I am not using SendTransactionFlow in my example to reproduce, but the error is the same.

**Comment by joeldudleyr3** [comment]
Thanks. Tracked here: https://r3-cev.atlassian.net/browse/CORDA-1525.

**Comment by mikehearn** [comment]
This is already fixed on master.

**Comment by joeldudleyr3** [comment]
Sorry Marko, never got back to you. @rick-r3, do you know which PR fixed this on master?

**Comment by rick-r3** [comment]
a24a2105b193b999804a5bd5e2f38ae7fe18b7e8

I think this commit made the difference because we discovered Guava was broken, but I haven't verified it in isolation.
