### ISSUE TITLE
No injection source found for a parameter @FormDataParam

### ISSUE THREAD

**Issue by suihalee** [corda/corda#3215]
I downloaded the cordapp java-template and used default webserver. Corda version is 3.1.

The code in the API class
```
 @POST
 @Path("uploadAttachment")
 @Consumes(MediaType.MULTIPART_FORM_DATA)
 public Response uploadFile(@FormDataParam("file") final InputStream uploadedInputStream, @FormDataParam("file") final FormDataContentDisposition fileDetail, @FormDataParam("id") final String id) {...}
```

And I added compile "org.glassfish.jersey.media:jersey-media-multipart:2.25" in file build.gradle.
The project can be compiled, but when I runnodes, I got the following error.
Do I miss any configuration? Thanks.

```
org.glassfish.jersey.server.model.ModelValidationException: Validation of the application resource model has failed during application initialization.
[[FATAL] No injection source found for a parameter of type public javax.ws.rs.core.Response com.ec.api.AccountApi.uploadFile(java.io.InputStream,org.glassfish.jersey.media.multipart.FormDataContentDisposition,java.lang.String) at index 0.; source='ResourceMethod{httpMethod=POST, consumedTypes=[multipart/form-data], producedTypes=[], suspended=false, suspendTimeout=0, suspendTimeoutUnit=MILLISECONDS, invocable=Invocable{handler=ClassBasedMethodHandler{handlerClass=class com.ec.api.AccountApi, handlerConstructors=[org.glassfish.jersey.server.model.HandlerConstructor@7f514dfe]}, definitionMethod=public javax.ws.rs.core.Response com.ec.api.AccountApi.uploadFile(java.io.InputStream,org.glassfish.jersey.media.multipart.FormDataContentDisposition,java.lang.String), parameters=[Parameter [type=class java.io.InputStream, source=file, defaultValue=null], Parameter [type=class org.glassfish.jersey.media.multipart.FormDataContentDisposition, source=file, defaultValue=null], Parameter [type=class java.lang.String, source=id, defaultValue=null]], responseType=class javax.ws.rs.core.Response}, nameBindings=[]}']
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:555) ~[jersey-server-2.25.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.access$500(ApplicationHandler.java:184) ~[jersey-server-2.25.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:350) ~[jersey-server-2.25.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:347) ~[jersey-server-2.25.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[jersey-common-2.25.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[jersey-common-2.25.jar:?]
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:255) ~[jersey-common-2.25.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:347) ~[jersey-server-2.25.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:392) ~[jersey-container-servlet-core-2.25.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:177) ~[jersey-container-servlet-core-2.25.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:369) ~[jersey-container-servlet-core-2.25.jar:?]
	at javax.servlet.GenericServlet.init(GenericServlet.java:244) ~[javax.servlet-api-3.1.0.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:637) [jetty-servlet-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:421) [jetty-servlet-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:760) [jetty-servlet-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:348) [jetty-servlet-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261) [jetty-servlet-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131) [jetty-util-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113) [jetty-util-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131) [jetty-util-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.Server.start(Server.java:449) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105) [jetty-util-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.Server.doStart(Server.java:416) [jetty-server-9.4.7.v20170914.jar:9.4.7.v20170914]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.7.v20170914.jar:9.4.7.v20170914]
	at net.corda.webserver.internal.NodeWebServer.initWebServer(NodeWebServer.kt:90) [corda-webserver-impl-3.1-corda.jar:?]
	at net.corda.webserver.internal.NodeWebServer.start(NodeWebServer.kt:45) [corda-webserver-impl-3.1-corda.jar:?]
	at net.corda.webserver.WebServer.main(WebServer.kt:64) [corda-webserver-impl-3.1-corda.jar:?]
```

**Comment by joeldudleyr3** [comment]
You cannot upload files to the default webserver. What is your aim here?

**Comment by suihalee** [comment]
By implementing the example IOU, if I would like to add a document for the transaction via web browser, what's the normal process to do?
Thanks.

**Comment by joeldudleyr3** [comment]
With the default webserver, you can upload a JAR file by hitting the built-in `/upload/attachment/` endpoint. Here's an example:

    <form action="/upload/attachment" method="post" enctype="multipart/form-data">
        <div class="form-group">
            <input type="file" name="jar" class="form-control">
        </div>
        <br>
        <button type="submit" class="btn btn-default">Upload blacklist</button>
    </form>

You include documents in a transaction in the form of JAR files called attachments.

**Comment by joeldudleyr3** [comment]
That flow is correct.

With another webserver, you'd have to upload the JAR using a CordaRPCOps proxy. You could use any URL you wanted, but the format would always have to be a JAR.

I'm not aware of any other examples currently. Can you raise a question here, and I'll take a look when I can? https://stackoverflow.com/questions/tagged/corda
