### ISSUE TITLE
Notary throws exception about attachment that exists but doesn't actually exist on the Notary

### ISSUE THREAD

**Issue by lankydan** [corda/corda#3302]
The following stack trace is output when a Notary validates a transaction that contains an attachment that it doesn't yet have a local copy of.
```
[WARN ] 2018-06-05T11:25:53,323Z [Node thread-1] flow.[24638a40-773e-4e39-8c93-d32243545dac].run - Terminated by unexpected exception {}
java.nio.file.FileAlreadyExistsException: 2AEF88DDC8528D90E22218B78DD639DE18E82A5D0739450CE9A5DFE8ACD7070A
	at net.corda.node.services.persistence.NodeAttachmentService$import$1.invoke(NodeAttachmentService.kt:300) ~[corda-node-3.1-corda.jar:?]
	at net.corda.node.services.persistence.NodeAttachmentService$import$1.invoke(NodeAttachmentService.kt:43) ~[corda-node-3.1-corda.jar:?]
	at net.corda.nodeapi.internal.ClassloaderUtilsKt.withContractsInJar(ClassloaderUtils.kt:37) ~[corda-node-api-3.1-corda.jar:?]
	at net.corda.node.services.persistence.NodeAttachmentService.import(NodeAttachmentService.kt:281) ~[corda-node-3.1-corda.jar:?]
	at net.corda.node.services.persistence.NodeAttachmentService.importAttachment(NodeAttachmentService.kt:265) ~[corda-node-3.1-corda.jar:?]
	at net.corda.core.internal.FetchAttachmentsFlow.maybeWriteToDisk(FetchDataFlow.kt:150) ~[corda-core-3.1-corda.jar:?]
	at net.corda.core.internal.FetchDataFlow.call(FetchDataFlow.kt:93) ~[corda-core-3.1-corda.jar:?]
	at net.corda.core.internal.FetchDataFlow.call(FetchDataFlow.kt:39) ~[corda-core-3.1-corda.jar:?]
	at net.corda.core.flows.FlowLogic.subFlow(FlowLogic.kt:290) ~[corda-core-3.1-corda.jar:?]
	at net.corda.core.internal.ResolveTransactionsFlow.fetchMissingAttachments(ResolveTransactionsFlow.kt:174) ~[corda-core-3.1-corda.jar:?]
	at net.corda.core.internal.ResolveTransactionsFlow.call(ResolveTransactionsFlow.kt:89) ~[corda-core-3.1-corda.jar:?]
	at net.corda.core.internal.ResolveTransactionsFlow.call(ResolveTransactionsFlow.kt:23) ~[corda-core-3.1-corda.jar:?]
	at net.corda.core.flows.FlowLogic.subFlow(FlowLogic.kt:290) ~[corda-core-3.1-corda.jar:?]
	at net.corda.node.services.transactions.ValidatingNotaryFlow.resolveAndContractVerify(ValidatingNotaryFlow.kt:57) ~[corda-node-3.1-corda.jar:?]
	at net.corda.node.services.transactions.ValidatingNotaryFlow.receiveAndVerifyTx(ValidatingNotaryFlow.kt:33) ~[corda-node-3.1-corda.jar:?]
	at net.corda.core.flows.NotaryFlow$Service.call(NotaryFlow.kt:142) ~[corda-core-3.1-corda.jar:?]
	at net.corda.core.flows.NotaryFlow$Service.call(NotaryFlow.kt:133) ~[corda-core-3.1-corda.jar:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:96) [corda-node-3.1-corda.jar:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:44) [corda-node-3.1-corda.jar:?]
	at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1092) [quasar-core-0.7.9-jdk8.jar:0.7.9]
	at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:788) [quasar-core-0.7.9-jdk8.jar:0.7.9]
	at co.paralleluniverse.fibers.RunnableFiberTask.doExec(RunnableFiberTask.java:100) [quasar-core-0.7.9-jdk8.jar:0.7.9]
	at co.paralleluniverse.fibers.RunnableFiberTask.run(RunnableFiberTask.java:91) [quasar-core-0.7.9-jdk8.jar:0.7.9]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_172]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_172]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_172]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172]
	at net.corda.node.utilities.AffinityExecutor$ServiceAffinityExecutor$1$thread$1.run(AffinityExecutor.kt:62) [corda-node-3.1-corda.jar:?]
```
The following code is in the `ResolveTransactionsFlow` line 174:
```kotlin
if (missingAttachments.isNotEmpty())
            subFlow(FetchAttachmentsFlow(missingAttachments.toSet(), otherSide))
```
It makes this check and goes in to execute the code, which suggests that the attachment doesn't exist on the Notary yet but later on while executing this code it ends up throwing the exception shown earlier.

Furthermore, this only occurs on the first occasion. If another transaction is passed that relies on the attachment, no exception is thrown. It seems that the attachment is now correctly saved to the vault and when it makes the attachment check above it doesn't pass and therefore doesn't try to save the attachment to the node (I haven't debugged this so this is a guess).

edit:

This only occurs on a validating notary

**Comment by adagys** [comment]
Hi Dan, thanks for reporting this, was able to reproduce it on master. Filed a bug: https://r3-cev.atlassian.net/browse/CORDA-1588

**Comment by adagys** [comment]
Could you verify if https://github.com/corda/corda/pull/3327 fixes the problem?
