### ISSUE TITLE
Exception when uploading large attachment: Missing validated user from the Artemis message

### ISSUE THREAD

**Issue by joeldudleyr3** [corda/corda#3649]
In Corda 3.1 OS, when trying to upload a large attachment to the node (100MBs+), I receive the following error message:

	Wed Jul 18 16:24:11 BST 2018>>> E 16:24:52+0100 [Thread-0 (ActiveMQ-client-global-threads)] core.client.run - AMQ214000: Failed to call onMessage {actor_id=user1, actor_owningIdentity=O=George State Bank, L=New York, C=US, actor_store_id=NODE_CONFIG, invocation_id=7a5455bc-b2b8-4321-8c41-1527505fedc9, invocation_timestamp=2018-07-18T15:24:40.838Z, session_id=153da0b7-0ace-4933-95ac-e0e95c7fbdbb, session_timestamp=2018-07-18T15:24:36.584Z}
	 java.lang.IllegalArgumentException: Missing validated user from the Artemis message
		at net.corda.node.services.messaging.RPCServer.actorFrom(RPCServer.kt:410) ~[corda-node-corda-3.0.jar:?]
		at net.corda.node.services.messaging.RPCServer.context(RPCServer.kt:404) ~[corda-node-corda-3.0.jar:?]
		at net.corda.node.services.messaging.RPCServer.clientArtemisMessageHandler(RPCServer.kt:316) ~[corda-node-corda-3.0.jar:?]
		at net.corda.node.services.messaging.RPCServer.access$clientArtemisMessageHandler(RPCServer.kt:82) ~[corda-node-corda-3.0.jar:?]
		at net.corda.node.services.messaging.RPCServer$createRpcConsumer$1.invoke(RPCServer.kt:199) ~[corda-node-corda-3.0.jar:?]
		at net.corda.node.services.messaging.RPCServer$createRpcConsumer$1.invoke(RPCServer.kt:82) ~[corda-node-corda-3.0.jar:?]
		at net.corda.node.services.messaging.RPCServerKt$sam$MessageHandler$97dacd80.onMessage(RPCServer.kt) ~[corda-node-corda-3.0.jar:?]
		at org.apache.activemq.artemis.core.client.impl.ClientConsumerImpl.callOnMessage(ClientConsumerImpl.java:997) ~[artemis-core-client-2.2.0.jar:2.2.0]
		at org.apache.activemq.artemis.core.client.impl.ClientConsumerImpl.access$400(ClientConsumerImpl.java:49) ~[artemis-core-client-2.2.0.jar:2.2.0]
		at org.apache.activemq.artemis.core.client.impl.ClientConsumerImpl$Runner.run(ClientConsumerImpl.java:1120) [artemis-core-client-2.2.0.jar:2.2.0]
		at org.apache.activemq.artemis.utils.actors.OrderedExecutor.doTask(OrderedExecutor.java:42) [artemis-commons-2.2.0.jar:2.2.0]
		at org.apache.activemq.artemis.utils.actors.OrderedExecutor.doTask(OrderedExecutor.java:31) [artemis-commons-2.2.0.jar:2.2.0]
		at org.apache.activemq.artemis.utils.actors.ProcessorBase$ExecutorTask.run(ProcessorBase.java:53) [artemis-commons-2.2.0.jar:2.2.0]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
		at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Comment by kid101** [comment]
Mainly because Artemis needs to update to version 2.5 or above which I can see in the master. though 3.2 seems to come out with 2.2

**Comment by joeldudleyr3** [comment]
Tracked here: https://r3-cev.atlassian.net/browse/CORDA-2215.

**Comment by davidrapacchiale** [comment]
Closing this issue as it is related to an old version of the software. Either not relevant any longer, or fixed elsewhere. Please do reopen if still relevant
