### ISSUE TITLE
MappedSchema doesn't throw an exception when it occurs and FinalityFlow has been executing for ever a transaction without have an answer

### ISSUE THREAD

**Issue by trferreira-BR** [corda/corda#3742]
Hi guys,

**Description:** I figured out a problem related to exception treatment in Corda . If a schema has a atribute java.sql.TimeStamp and during a parse from java.time.LocalDate to java.sql.TimeStamp in generateMappedObject() : PersistentState, It occurs an exception, the transaction stops forever after a Flow calls `subFlow(FinalityFlow(signedTx))`

So, It is a problem caused by mistake from Java (polimorfism), but It reflects directly on Corda V3-2 causing a strange and dangerous behaviour. It is a critical bug in Corda.
**If a new transaction in Corda is request after the subFlow stop and wait forever, then the error doesn't throw again in Nodes` log trace, covering and hiding the error and its state and others subsequent doesn't storage on vault.**

Java Problem:
java.sql.Timestamp.valueOf(LocalDateTime.from(LocalDate))
LocalDate is a TemporalAcessor
But in this case, LocalDate has a formatt 2018-08-04 and the exception occurs.

**Logs:**
[WARN ] 2018-08-04T13:50:53,433Z [Node thread-1] flow.[d0fc3d2e-16d4-4e74-bda3-61827875515d].run - Terminated by unexpected exception {}
rx.exceptions.OnErrorNotImplementedException: Unable to obtain LocalDateTime from TemporalAccessor: 2018-07-27 of type java.time.LocalDate
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:216) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.subjects.PublishSubject.onNext(PublishSubject.java:72) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.util.ObserverSubscriber.onNext(ObserverSubscriber.java:34) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.subjects.PublishSubject.onNext(PublishSubject.java:72) ~[rxjava-1.2.4.jar:1.2.4]
	at net.corda.node.services.vault.NodeVaultService.processAndNotify(NodeVaultService.kt:203) ~[corda-node-3.2-corda.jar:?]
	at net.corda.node.services.vault.NodeVaultService.access$processAndNotify(NodeVaultService.kt:47) ~[corda-node-3.2-corda.jar:?]
	at net.corda.node.services.vault.NodeVaultService$notifyAll$1.invoke(NodeVaultService.kt:116) ~[corda-node-3.2-corda.jar:?]
	at net.corda.node.services.vault.NodeVaultService.notifyAll(NodeVaultService.kt:126) ~[corda-node-3.2-corda.jar:?]
	at net.corda.node.services.api.ServiceHubInternal$DefaultImpls.recordTransactions(ServiceHubInternal.kt:118) ~[corda-node-3.2-corda.jar:?]
	at net.corda.node.internal.AbstractNode$ServiceHubInternalImpl$recordTransactions$1.invoke(AbstractNode.kt:859) ~[corda-node-3.2-corda.jar:?]
	at net.corda.node.internal.AbstractNode$ServiceHubInternalImpl$recordTransactions$1.invoke(AbstractNode.kt:820) ~[corda-node-3.2-corda.jar:?]
	at net.corda.nodeapi.internal.persistence.CordaPersistence.transaction(CordaPersistence.kt:136) ~[corda-node-api-3.2-corda.jar:?]
	at net.corda.nodeapi.internal.persistence.CordaPersistence.transaction(CordaPersistence.kt:124) ~[corda-node-api-3.2-corda.jar:?]
	at net.corda.nodeapi.internal.persistence.CordaPersistence.transaction(CordaPersistence.kt:131) ~[corda-node-api-3.2-corda.jar:?]
	at net.corda.node.internal.AbstractNode$ServiceHubInternalImpl.recordTransactions(AbstractNode.kt:858) ~[corda-node-3.2-corda.jar:?]
	at net.corda.core.node.ServiceHub$DefaultImpls.recordTransactions(ServiceHub.kt:201) ~[corda-core-3.2-corda.jar:?]
	at net.corda.node.services.api.ServiceHubInternal$DefaultImpls.recordTransactions(ServiceHubInternal.kt) ~[corda-node-3.2-corda.jar:?]
	at net.corda.node.internal.AbstractNode$ServiceHubInternalImpl.recordTransactions(AbstractNode.kt:820) ~[corda-node-3.2-corda.jar:?]
	at net.corda.core.node.ServiceHub$DefaultImpls.recordTransactions(ServiceHub.kt:193) ~[corda-core-3.2-corda.jar:?]
	at net.corda.node.services.api.ServiceHubInternal$DefaultImpls.recordTransactions(ServiceHubInternal.kt) ~[corda-node-3.2-corda.jar:?]
	at net.corda.node.internal.AbstractNode$ServiceHubInternalImpl.recordTransactions(AbstractNode.kt:820) ~[corda-node-3.2-corda.jar:?]
	at net.corda.core.flows.FinalityFlow.notariseAndRecord(FinalityFlow.kt:78) ~[corda-core-3.2-corda.jar:?]
	at net.corda.core.flows.FinalityFlow.call(FinalityFlow.kt:56) ~[corda-core-3.2-corda.jar:?]
	at net.corda.core.flows.FinalityFlow.call(FinalityFlow.kt:28) ~[corda-core-3.2-corda.jar:?]
	at net.corda.core.flows.FlowLogic.subFlow(FlowLogic.kt:290) ~[corda-core-3.2-corda.jar:?]
	...
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:96) [corda-node-3.2-corda.jar:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:44) [corda-node-3.2-corda.jar:?]
	at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1092) [quasar-core-0.7.9-jdk8.jar:0.7.9]
	at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:788) [quasar-core-0.7.9-jdk8.jar:0.7.9]
	at co.paralleluniverse.fibers.RunnableFiberTask.doExec(RunnableFiberTask.java:100) [quasar-core-0.7.9-jdk8.jar:0.7.9]
	at co.paralleluniverse.fibers.RunnableFiberTask.run(RunnableFiberTask.java:91) [quasar-core-0.7.9-jdk8.jar:0.7.9]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
	at net.corda.node.utilities.AffinityExecutor$ServiceAffinityExecutor$1$thread$1.run(AffinityExecutor.kt:62) [corda-node-3.2-corda.jar:?]
Caused by: java.time.DateTimeException: Unable to obtain LocalDateTime from TemporalAccessor: 2018-07-27 of type java.time.LocalDate
	at java.time.LocalDateTime.from(Unknown Source) ~[?:1.8.0_161]

**Structure:** 

```
data class IOUState(): OwnableState, QueryableState {
	override fun generateMappedObject(schema: MappedSchema): PersistentState {
			//object LocalDate with format 2018-07-27
	        return when (schema) {
	            is IOUSchemaV1 -> IOUSchemaV1.PersistentIOU(
	                    date = java.sql.Timestamp.valueOf(LocalDateTime.from(LocalDate)),
	            )
	            else -> throw IllegalArgumentException("Unrecognised schema $schema")
	        }
	    }
}
```

```
object IOUSchema

@CordaSerializable
object IOUSchemaV1 : MappedSchema(
        schemaFamily = IOUSchema.javaClass,
        version = 1,
        mappedTypes = listOf(PersistentIOU::class.java)) {
    @Entity
    @Table(name = "iou_states")
    class PersistentIOU(
            
            @Column(name = "date")
            var date: Timestamp

    ) : PersistentState()
}

```

**Version:** Corda V3-2
Indexed people @mikehearn @gendal

**Comment by joeldudleyr3** [comment]
Thanks Thiago. Tracked here: https://r3-cev.atlassian.net/browse/CORDA-1881.

**Comment by mikehearn** [comment]
Fixed by the fix for CORDA-1847. The patch will ship in Corda 3.3
