### ISSUE TITLE
Driver DSL fails to form a connection with a notary

### ISSUE THREAD

**Issue by dazraf** [corda/corda#3743]
When using the Driver DSL on my MacBook Pro 2017  16GB 3.1 GHz Intel Core i7, it fails to carry out a simple Cash payment. 

I've created a sample project that exhibits the issue with instructions and key segment of the log:

https://github.com/dazraf/cordapp-template-kotlin

During the cash payment, this is the output of the log:

```
[INFO ] 09:33:24,827 [nioEventLoopGroup-12-1] (AMQPChannelHandler.kt:49) O=PartyA, L=London, C=GB.channelActive - New client connection e32a17e2 from localhost/127.0.0.1:10000 to /127.0.0.1:63779 {}
[WARN ] 09:33:24,839 [Node thread-3] (AppendOnlyPersistentMap.kt:79) utilities.AppendOnlyPersistentMapBase.set - Double insert in net.corda.node.utilities.AppendOnlyPersistentMap for entity class class net.corda.node.services.identity.PersistentIdentityService$PersistentIdentity key BC0AA7612C81D24A2DC5D0D7E69E0508C7C3549CBD3FF0498C1983CD163DD539, not inserting the second time {}
[INFO ] 09:33:24,863 [nioEventLoopGroup-12-1] (AMQPChannelHandler.kt:89) O=PartyA, L=London, C=GB.userEventTriggered - handshake completed subject: O=PartyA, L=London, C=GB {}
[INFO ] 09:33:24,870 [nioEventLoopGroup-12-1] (AMQPBridgeManager.kt:106) peers.DL6peD56B7zNNTgSnxyqC2PX78CbhfhKLLqj5aeBCRHFL5 -> localhost:10000:O=PartyA, L=London, C=GB.onSocketConnected - Bridge Connected {}
[INFO ] 09:33:24,886 [nioEventLoopGroup-12-1] (ConnectionStateMachine.kt:100) O=PartyB, L=New York, C=US.onConnectionLocalOpen - Connection local open org.apache.qpid.proton.engine.impl.ConnectionImpl@228cb46 {}
[WARN ] 09:33:24,941 [Node thread-3] (AppendOnlyPersistentMap.kt:79) utilities.AppendOnlyPersistentMapBase.set - Double insert in net.corda.node.utilities.AppendOnlyPersistentMap for entity class class net.corda.node.services.identity.PersistentIdentityService$PersistentIdentity key 567ECDD3423FA9BC7EAE9275D1BA8E227B60B88FE6F104B4BCF248E6D32EAA2A, not inserting the second time {}
[INFO ] 09:33:24,978 [Thread-0 (ActiveMQ-client-factory-threads-1679362123)] (P2PMessagingClient.kt:402) messaging.P2PMessagingClient.artemisToCordaMessage - Received message from: p2p.inbound.DL6peD56B7zNNTgSnxyqC2PX78CbhfhKLLqj5aeBCRHFL5 user: O=PartyB, L=New York, C=US topic: platform.session uuid: e0542ed7-06bc-4233-b28f-0c97a3e42195 {}
[INFO ] 09:33:25,034 [Thread-0 (ActiveMQ-client-factory-threads-1679362123)] (P2PMessagingClient.kt:402) messaging.P2PMessagingClient.artemisToCordaMessage - Received message from: p2p.inbound.DL6peD56B7zNNTgSnxyqC2PX78CbhfhKLLqj5aeBCRHFL5 user: O=PartyB, L=New York, C=US topic: platform.session uuid: ad09ad7e-c1df-438a-8200-85eb27fbfb97 {}
[INFO ] 09:33:25,103 [Thread-0 (ActiveMQ-client-factory-threads-1679362123)] (P2PMessagingClient.kt:402) messaging.P2PMessagingClient.artemisToCordaMessage - Received message from: p2p.inbound.DL6peD56B7zNNTgSnxyqC2PX78CbhfhKLLqj5aeBCRHFL5 user: O=PartyB, L=New York, C=US topic: platform.session uuid: bce8d7b2-21f8-42ca-bd07-961da67928a6 {}
[WARN ] 09:33:25,119 [Node thread-1] (AppendOnlyPersistentMap.kt:79) utilities.AppendOnlyPersistentMapBase.set - Double insert in net.corda.node.utilities.AppendOnlyPersistentMap for entity class class net.corda.node.services.identity.PersistentIdentityService$PersistentIdentity key BC0AA7612C81D24A2DC5D0D7E69E0508C7C3549CBD3FF0498C1983CD163DD539, not inserting the second time {}
[WARN ] 09:33:25,271 [Node thread-1] (AppendOnlyPersistentMap.kt:79) utilities.AppendOnlyPersistentMapBase.set - Double insert in net.corda.node.utilities.AppendOnlyPersistentMap for entity class class net.corda.node.services.identity.PersistentIdentityService$PersistentIdentity key 567ECDD3423FA9BC7EAE9275D1BA8E227B60B88FE6F104B4BCF248E6D32EAA2A, not inserting the second time {}
[INFO ] 09:33:25,567 [Node thread-1] (FlowStateMachineImpl.kt:432) flow.[ee8debc4-caea-43cf-a19a-1e812922ad1b].initiateSession - Initiating flow session with party O=Notary Service, L=Zurich, C=CH. Session id for tracing purposes is SessionId(toLong=-4884935399875269269). {}
[INFO ] 09:33:25,615 [Messaging DL6peD56B7zNNTgSnxyqC2PX78CbhfhKLLqj5aeBCRHFL5] (P2PMessagingClient.kt:623) messaging.P2PMessagingClient.createQueueIfAbsent - Create fresh queue internal.peers.DLF1ZmHt1DXc9HbxzDNm6VHduUABBbNsp7Mh4DhoBs6ifd bound on same address {}
[WARN ] 09:33:25,624 [Thread-2 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$3@3e4fc89c)] (QueueImpl.java:3193) core.server.checkDeadLetterAddressAndExpiryAddress - AMQ222165: No Dead Letter Address configured for queue internal.peers.DLF1ZmHt1DXc9HbxzDNm6VHduUABBbNsp7Mh4DhoBs6ifd in AddressSettings {}
[WARN ] 09:33:25,625 [Thread-2 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$3@3e4fc89c)] (QueueImpl.java:3196) core.server.checkDeadLetterAddressAndExpiryAddress - AMQ222166: No Expiry Address configured for queue internal.peers.DLF1ZmHt1DXc9HbxzDNm6VHduUABBbNsp7Mh4DhoBs6ifd in AddressSettings {}
[INFO ] 09:33:25,639 [Thread-0 (ActiveMQ-client-factory-threads-1244519356)] (BridgeControlListener.kt:79) bridging.BridgeControlListener.processControlMessage - Received bridge control message Create(nodeIdentity=DL6peD56B7zNNTgSnxyqC2PX78CbhfhKLLqj5aeBCRHFL5, bridgeInfo=BridgeEntry(queueName=internal.peers.DLF1ZmHt1DXc9HbxzDNm6VHduUABBbNsp7Mh4DhoBs6ifd, targets=[localhost:10001], legalNames=[O=Notary Service, L=Zurich, C=CH])) {}
[INFO ] 09:33:25,644 [Thread-0 (ActiveMQ-client-factory-threads-1244519356)] (AMQPBridgeManager.kt:82) peers.DLF1ZmHt1DXc9HbxzDNm6VHduUABBbNsp7Mh4DhoBs6ifd -> localhost:10001:O=Notary Service, L=Zurich, C=CH.start - Create new AMQP bridge {}
[INFO ] 09:33:25,644 [Thread-0 (ActiveMQ-client-factory-threads-1244519356)] (AMQPClient.kt:126) netty.AMQPClient.start - connect to: localhost:10001 {}
[INFO ] 09:33:25,649 [nioEventLoopGroup-3-2] (AMQPClient.kt:76) netty.AMQPClient.operationComplete - Connected to localhost:10001 {}
[INFO ] 09:33:25,651 [nioEventLoopGroup-3-2] (AMQPChannelHandler.kt:49) O=Notary Service, L=Zurich, C=CH.channelActive - New client connection 25c1f884 from localhost/127.0.0.1:10001 to /127.0.0.1:63780 {}
[INFO ] 09:33:25,651 [nioEventLoopGroup-3-2] (AMQPClient.kt:86) netty.AMQPClient.operationComplete - Disconnected from localhost:10001 {}
[ERROR] 09:33:25,655 [nioEventLoopGroup-3-2] (AMQPChannelHandler.kt:98) O=Notary Service, L=Zurich, C=CH.userEventTriggered - Handshake failure SslHandshakeCompletionEvent(java.nio.channels.ClosedChannelException) {}
[INFO ] 09:33:25,657 [nioEventLoopGroup-3-2] (AMQPChannelHandler.kt:74) O=Notary Service, L=Zurich, C=CH.channelInactive - Closed client connection 25c1f884 from localhost/127.0.0.1:10001 to /127.0.0.1:63780 {}
[INFO ] 09:33:25,658 [nioEventLoopGroup-3-2] (AMQPBridgeManager.kt:115) peers.DLF1ZmHt1DXc9HbxzDNm6VHduUABBbNsp7Mh4DhoBs6ifd -> localhost:10001:O=Notary Service, L=Zurich, C=CH.onSocketConnected - Bridge Disconnected {}
[INFO ] 09:33:26,653 [nioEventLoopGroup-3-3] (AMQPClient.kt:91) netty.AMQPClient.run - Retry connect {}
[INFO ] 09:33:26,657 [nioEventLoopGroup-3-4] (AMQPClient.kt:76) netty.AMQPClient.operationComplete - Connected to localhost:10001 {}
[INFO ] 09:33:26,658 [nioEventLoopGroup-3-4] (AMQPChannelHandler.kt:49) O=Notary Service, L=Zurich, C=CH.channelActive - New client connection db926eb8 from localhost/127.0.0.1:10001 to /127.0.0.1:63781 {}
[INFO ] 09:33:26,658 [nioEventLoopGroup-3-4] (AMQPClient.kt:86) netty.AMQPClient.operationComplete - Disconnected from localhost:10001 {}
[ERROR] 09:33:26,658 [nioEventLoopGroup-3-4] (AMQPChannelHandler.kt:98) O=Notary Service, L=Zurich, C=CH.userEventTriggered - Handshake failure SslHandshakeCompletionEvent(java.nio.channels.ClosedChannelException) {}
[INFO ] 09:33:26,659 [nioEventLoopGroup-3-4] (AMQPChannelHandler.kt:74) O=Notary Service, L=Zurich, C=CH.channelInactive - Closed client connection db926eb8 from localhost/127.0.0.1:10001 to /127.0.0.1:63781 {}
[INFO ] 09:33:26,659 [nioEventLoopGroup-3-4] (AMQPBridgeManager.kt:115) peers.DLF1ZmHt1DXc9HbxzDNm6VHduUABBbNsp7Mh4DhoBs6ifd -> localhost:10001:O=Notary Service, L=Zurich, C=CH.onSocketConnected - Bridge Disconnected {}
[INFO ] 09:33:27,662 [nioEventLoopGroup-3-5] (AMQPClient.kt:91) netty.AMQPClient.run - Retry connect {}
[INFO ] 09:33:27,667 [nioEventLoopGroup-3-6] (AMQPClient.kt:76) netty.AMQPClient.operationComplete - Connected to localhost:10001 {}
[INFO ] 09:33:27,668 [nioEventLoopGroup-3-6] (AMQPChannelHandler.kt:49) O=Notary Service, L=Zurich, C=CH.channelActive - New client connection 81808e51 from localhost/127.0.0.1:10001 to /127.0.0.1:63782 {}
[INFO ] 09:33:27,668 [nioEventLoopGroup-3-6] (AMQPClient.kt:86) netty.AMQPClient.operationComplete - Disconnected from localhost:10001 {}
[ERROR] 09:33:27,669 [nioEventLoopGroup-3-6] (AMQPChannelHandler.kt:98) O=Notary Service, L=Zurich, C=CH.userEventTriggered - Handshake failure SslHandshakeCompletionEvent(java.nio.channels.ClosedChannelException) {}
[INFO ] 09:33:27,669 [nioEventLoopGroup-3-6] (AMQPChannelHandler.kt:74) O=Notary Service, L=Zurich, C=CH.channelInactive - Closed client connection 81808e51 from localhost/127.0.0.1:10001 to /127.0.0.1:63782 {}
[INFO ] 09:33:27,669 [nioEventLoopGroup-3-6] (AMQPBridgeManager.kt:115) peers.DLF1ZmHt1DXc9HbxzDNm6VHduUABBbNsp7Mh4DhoBs6ifd -> localhost:10001:O=Notary Service, L=Zurich, C=CH.onSocketConnected - Bridge Disconnected {}
[INFO ] 09:33:28,671 [nioEventLoopGroup-3-7] (AMQPClient.kt:91) netty.AMQPClient.run - Retry connect {}
[INFO ] 09:33:28,677 [nioEventLoopGroup-3-8] (AMQPClient.kt:76) netty.AMQPClient.operationComplete - Connected to localhost:10001 {}
[INFO ] 09:33:28,680 [nioEventLoopGroup-3-8] (AMQPChannelHandler.kt:49) O=Notary Service, L=Zurich, C=CH.channelActive - New client connection a0e0cd1e from localhost/127.0.0.1:10001 to /127.0.0.1:63783 {}
[INFO ] 09:33:28,680 [nioEventLoopGroup-3-8] (AMQPClient.kt:86) netty.AMQPClient.operationComplete - Disconnected from localhost:10001 {}
[ERROR] 09:33:28,681 [nioEventLoopGroup-3-8] (AMQPChannelHandler.kt:98) O=Notary Service, L=Zurich, C=CH.userEventTriggered - Handshake failure SslHandshakeCompletionEvent(java.nio.channels.ClosedChannelException) {}
[INFO ] 09:33:28,682 [nioEventLoopGroup-3-8] (AMQPChannelHandler.kt:74) O=Notary Service, L=Zurich, C=CH.channelInactive - Closed client connection a0e0cd1e from localhost/127.0.0.1:10001 to /127.0.0.1:63783 {}
[INFO ] 09:33:28,682 [nioEventLoopGroup-3-8] (AMQPBridgeManager.kt:115) peers.DLF1ZmHt1DXc9HbxzDNm6VHduUABBbNsp7Mh4DhoBs6ifd -> localhost:10001:O=Notary Service, L=Zurich, C=CH.onSocketConnected - Bridge Disconnected {}
[INFO ] 09:33:29,682 [nioEventLoopGroup-3-9] (AMQPClient.kt:91) netty.AMQPClient.run - Retry connect {}
[INFO ] 09:33:29,686 [nioEventLoopGroup-3-10] (AMQPClient.kt:76) netty.AMQPClient.operationComplete - Connected to localhost:10001 {}
[INFO ] 09:33:29,687 [nioEventLoopGroup-3-10] (AMQPChannelHandler.kt:49) O=Notary Service, L=Zurich, C=CH.channelActive - New client connection 00ab0536 from localhost/127.0.0.1:10001 to /127.0.0.1:63784 {}
[INFO ] 09:33:29,688 [nioEventLoopGroup-3-10] (AMQPClient.kt:86) netty.AMQPClient.operationComplete - Disconnected from localhost:10001 {}
[ERROR] 09:33:29,688 [nioEventLoopGroup-3-10] (AMQPChannelHandler.kt:98) O=Notary Service, L=Zurich, C=CH.userEventTriggered - Handshake failure SslHandshakeCompletionEvent(java.nio.channels.ClosedChannelException) {}
[INFO ] 09:33:29,689 [nioEventLoopGroup-3-10] (AMQPChannelHandler.kt:74) O=Notary Service, L=Zurich, C=CH.channelInactive - Closed client connection 00ab0536 from localhost/127.0.0.1:10001 to /127.0.0.1:63784 {}
[INFO ] 09:33:29,689 [nioEventLoopGroup-3-10] (AMQPBridgeManager.kt:115) peers.DLF1ZmHt1DXc9HbxzDNm6VHduUABBbNsp7Mh4DhoBs6ifd -> localhost:10001:O=Notary Service, L=Zurich, C=CH.onSocketConnected - Bridge Disconnected {}
[INFO ] 09:33:30,693 [nioEventLoopGroup-3-11] (AMQPClient.kt:91) netty.AMQPClient.run - Retry connect {}
... 
```

**Comment by dazraf** [comment]
Tudor helped me today to debug this issue, comparing to his laptop. We didn't get to the heart of it but progressed much further (thanks Tudor!) Notably:

1. The notary logs show the artemis server starting but the client is unable to connect

```
[INFO ] 13:24:21,735 [main] (ActiveMQServerImpl.java:540) core.server.internalStart - AMQ221001: Apache ActiveMQ Artemis Message Broker version 2.2.0 [localhost, nodeID=7b3df3b8-98aa-11e8-83bd-ead493c8221e]  {}
[DEBUG] 13:24:21,735 [main] (ArtemisRpcBroker.kt:51) rpc.ArtemisRpcBroker.start - Artemis RPC broker is started. {}
[INFO ] 13:24:21,737 [main] (ArtemisMessagingClient.kt:28) internal.ArtemisMessagingClient.start - Connecting to message broker: localhost:10001 {}
[ERROR] 13:24:22,298 [main] (NettyConnector.java:713) core.client.createConnection - AMQ214016: Failed to create netty connection {}
java.nio.channels.ClosedChannelException: null
	at io.netty.handler.ssl.SslHandler.channelInactive(...)(Unknown Source) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
[DEBUG] 13:24:22,362 [main] (PersistentIdentityService.kt:137) identity.PersistentIdentityService.verifyAndRegisterIdentity - Registering identity O=Notary Service, L=Zurich, C=CH {}
[WARN ] 13:24:22,363 [main] (AppendOnlyPersistentMap.kt:79) utilities.AppendOnlyPersistentMapBase.set - Double insert in net.corda.node.utilities.AppendOnlyPersistentMap for entity class class net.corda.node.services.identity.PersistentIdentityService$PersistentIdentity key 69ACAA32A0C7934D9454CB53EEA6CA6CCD8E4090B30C560A5A36EA10F3DC13E8, not inserting the second time {}
[ERROR] 13:24:22,368 [main] (NodeStartup.kt:125) internal.Node.run - Exception during node startup {}
org.apache.activemq.artemis.api.core.ActiveMQNotConnectedException: AMQ119007: Cannot connect to server(s). Tried with all available servers.
	at org.apache.activemq.artemis.core.client.impl.ServerLocatorImpl.createSessionFactory(ServerLocatorImpl.java:787) ~[artemis-core-client-2.2.0.jar:2.2.0]
	at net.corda.nodeapi.internal.ArtemisMessagingClient.start(ArtemisMessagingClient.kt:39) ~[corda-node-api-3.2-corda.jar:?]
	at net.corda.nodeapi.internal.bridging.AMQPBridgeManager.start(AMQPBridgeManager.kt:195) ~[corda-node-api-3.2-corda.jar:?]
	at net.corda.nodeapi.internal.bridging.BridgeControlListener.start(BridgeControlListener.kt:35) ~[corda-node-api-3.2-corda.jar:?]
	at net.corda.node.internal.Node.startMessagingService(Node.kt:301) ~[corda-node-3.2-corda.jar:?]
```

2. His logs show:

```
Advertised P2P messaging addresses      : [2a02:c7d:ca6a:7e00:ec17:d884:42b:65df%en0]:10002
Advertised P2P messaging addresses      : [2a02:c7d:ca6a:7e00:ec17:d884:42b:65df%en0]:10001
RPC connection address                  : localhost:10003
RPC connection address                  : localhost:10006
RPC admin connection address            : localhost:10004
RPC admin connection address            : localhost:10007
```

whilst mine show

```
Advertised P2P messaging addresses      : localhost:10001
RPC connection address                  : localhost:10002
RPC admin connection address            : localhost:10003
```

3. comparing our `/etc/hosts`

his:

```
127.0.0.1	localhost
127.0.0.1       TUDORSMACBOOK.local
fe80::1%lo0     TUDORSMACBOOK.local
255.255.255.255	broadcasthost
::1             localhost
```

whilst mine

```
127.0.0.1       localhost  fuzzmac fuzzmac.local
255.255.255.255 broadcasthost
::1             localhost fuzzmac fuzzmac.local
```

I tried altering mine to:

```
127.0.0.1       localhost
127.0.0.1       fuzzmac.local
fe80::1%lo0     fuzzmac.local
255.255.255.255 broadcasthost
::1             localhost
```

and then to

```
127.0.0.1       localhost
127.0.0.1       fuzzmac.local
# fe80::1%lo0     fuzzmac.local
255.255.255.255 broadcasthost
# ::1             localhost
```

Neither of which worked.

I'm now working on debuggin the artemis server startup to figure out what interface it's binding to.

**Comment by dazraf** [comment]
I think IntelliJ may be the culprit. With it cleanly restarted with no projects loaded:

```bash
lsof -nP -i | grep LISTEN | grep "1000[0-9]"
idea      3036 fuzz    7u  IPv4 0x5338e71a994fd78f      0t0  TCP *:10001 (LISTEN)
```

**Comment by dazraf** [comment]
so the reason was that the YourKit shipped with Intellij ultimate runs by default on port 10001.

I located the config using:
https://intellij-support.jetbrains.com/hc/en-us/articles/207241235

and altered it to use a different port as per: 
https://stackoverflow.com/questions/13345986/intellij-idea-using-10001-port

here's my new config line:
`-agentlib:yjpagent=delay=10000,probe_disable=*,port=30000`

This fixes this issue. Thanks Tudor for all the help!

**Comment by tudor-malene** [comment]
The exception was really unhelpful. 
One would expect a completely different exception when a port is taken.

It looks like the client is trying to connect before the broker is started, and it fails badly because it doesn't encounter the exception it's expecting.

@tlil , wdyt?

**Comment by tlil** [comment]
@tudor-malene Yes, agree. I'll make a note of this to make sure we improve the error reporting.
