### ISSUE TITLE
Command line shell processor throws StringIndexOutOfBoundsException on malformed command

### ISSUE THREAD

**Issue by sklimakov** [corda/corda#4052]
Version: 3.2

**Steps to reproduce**

Start an ordinary node

`java -jar corda.jar`

Once the command line greeting is appeared insert the text produced by:

`python2 -c 'print "".join([chr(c) for c in [99, 111, 114, 100, 97, 1, 194, 128, 195, 133, 98, 1, 195, 144, 39, 194, 162, 3, 194, 163, 34, 110, 101, 116, 46, 99, 111, 114, 100, 97, 58, 56, 103, 79, 83, 116, 113, 70, 75, 65, 74, 80, 85, 101, 111, 99, 102, 118, 51, 83, 101, 83, 81, 61, 61, 195, 144, 30, 101, 2, 194, 163, 34, 110, 101, 116, 46, 99, 111, 114, 100, 97, 58, 71, 43, 73, 103, 51, 97, 118, 99, 106, 101, 52, 75, 88, 107, 51, 119, 114, 99, 106, 68, 69, 81, 61, 61, 195, 128, 195, 170, 1, 194, 163, 34, 110, 101, 116, 46, 99, 111, 114, 100, 97, 58, 121, 102, 98, 43, 50, 54, 104, 90, 78, 56, 87, 52, 111, 51, 69, 113, 108, 99, 90, 54, 106, 103, 61, 61, 195, 128, 195, 130, 4, 194, 163, 33, 110, 101, 116, 46, 99, 111, 114, 100, 97, 58, 106, 97, 118, 97, 46, 115, 101, 99, 117, 114, 105, 116, 121, 46, 80, 117, 98, 108, 105, 99, 75, 101, 121, 194, 160, 44, 48, 42, 48, 5, 6, 3, 43, 101, 112, 3, 33, 51, 195, 173, 45, 194, 175, 194, 156, 24, 195, 162, 195, 139, 194, 185, 45, 77, 22, 85, 194, 176, 194, 152, 195, 170, 52, 194, 131, 194, 179, 194, 173, 195, 183, 48, 50, 195, 182, 195, 142, 126, 194, 165, 97, 194, 138, 195, 131, 195, 138, 20, 194, 160, 64, 5, 195, 150, 195, 149, 195, 144, 13, 10, 195, 131, 98, 194, 141, 194, 159, 195, 140, 194, 148, 195, 167, 194, 140, 123, 53, 195, 187, 103, 116, 70, 194, 150, 194, 134, 48, 57, 40, 194, 153, 16, 194, 139, 72, 195, 177, 194, 133, 194, 167, 23, 195, 175, 8, 118, 194, 165, 194, 171, 194, 181, 9, 194, 140, 99, 194, 167, 195, 156, 194, 174, 18, 195, 184, 4, 195, 134, 194, 132, 194, 184, 64, 101, 194, 139, 194, 138, 194, 170, 13, 10, 194, 175, 39, 73, 51, 21, 12, 64, 194, 163, 34, 110, 101, 116, 46, 99, 111, 114, 100, 97, 58, 73, 122, 70, 116, 56, 99, 82, 75, 121, 116, 115, 74, 113, 51, 118, 81, 43, 121, 106, 115, 71, 103, 61, 61, 195, 128, 5, 2, 84, 3, 84, 4, 194, 163, 34, 110, 101, 116, 46, 99, 111, 114, 100, 97, 58, 76, 79, 48, 66, 83, 78, 43, 51, 120, 51, 74, 78, 53, 79, 77, 114, 77, 78, 85, 55, 106, 65, 61, 61, 195, 144, 29, 38, 1, 194, 176, 29, 29, 99, 111, 114, 100, 97, 1, 194, 128, 195, 133, 98, 1, 195, 144, 29, 6, 3, 194, 163, 34, 110, 101, 116, 46, 99, 111, 114, 100, 97, 58, 88, 79, 111, 53, 88, 114, 110, 48, 49, 109, 99, 86, 106, 111, 107, 73, 108, 72, 49, 101, 107, 65, 61, 61, 195, 144, 23, 195, 182, 2, 194, 163]])'`

The above byte array is a part of blob from the database, it was inserted accidentally.

**Result**

CLI hangs with the following exception:

> Exception in thread "Command line shell processor" java.lang.StringIndexOutOfBoundsException: String index out of range: 20
        at java.lang.AbstractStringBuilder.charAt(Unknown Source)
        at java.lang.StringBuilder.charAt(Unknown Source)
        at org.crsh.console.EditorBuffer.pop(EditorBuffer.java:401)
        at org.crsh.console.EditorBuffer.appendDel(EditorBuffer.java:358)
        at org.crsh.console.EditorBuffer.replace(EditorBuffer.java:167)
        at org.crsh.console.EditorAction$History.perform(EditorAction.java:224)
        at org.crsh.console.EditorAction.execute(EditorAction.java:768)
        at org.crsh.console.Editor.append(Editor.java:151)
        at org.crsh.console.Console.iterate(Console.java:214)
        at org.crsh.console.Console.on(Console.java:158)
        at org.crsh.console.Console.on(Console.java:135)
        at org.crsh.console.jline.JLineProcessor.run(JLineProcessor.java:204)
        at net.corda.node.shell.InteractiveShell$runLocalShell$2.invoke(InteractiveShell.kt:135)
        at net.corda.node.shell.InteractiveShell$runLocalShell$2.invoke(InteractiveShell.kt:79)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Comment by joeldudleyr3** [comment]
Thanks. Tracked here: https://r3-cev.atlassian.net/browse/CORDA-2123.

**Comment by davidrapacchiale** [comment]
Fixed.
