### ISSUE TITLE
If a flow has an empty progress tracker that's never used, exception is thrown

### ISSUE THREAD

**Issue by mikehearn** [corda/corda#4062]
For example:

```
[WARN ] 10:39:47,259 [Node thread-4] (StateMachineManagerImpl.kt:79) flow.[38701a62-1cb5-441f-ad00-9fe6bf14242c].uncaughtException - Caught exception from flow {}
java.lang.IllegalStateException: Cannot rewind a progress tracker once it has ended
	at net.corda.core.utilities.ProgressTracker.setCurrentStep(ProgressTracker.kt:117) ~[corda-core-3.2-corda.jar:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:120) ~[corda-node-3.2-corda.jar:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:44) ~[corda-node-3.2-corda.jar:?]
	at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1092) [quasar-core-0.7.9-jdk8.jar:0.7.9]
	at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:788) [quasar-core-0.7.9-jdk8.jar:0.7.9]
	at co.paralleluniverse.fibers.RunnableFiberTask.doExec(RunnableFiberTask.java:100) [quasar-core-0.7.9-jdk8.jar:0.7.9]
	at co.paralleluniverse.fibers.RunnableFiberTask.run(RunnableFiberTask.java:91) [quasar-core-0.7.9-jdk8.jar:0.7.9]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_172]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_172]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_172]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_172]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172]
	at net.corda.node.utilities.AffinityExecutor$ServiceAffinityExecutor$1$thread$1.run(AffinityExecutor.kt:62) [corda-node-3.2-corda.jar:?]
```

This can happen if you make an empty progress tracker that's unused. This should log an error or warning that explains what happened, or it should be ignored, but we shouldn't throw.

**Comment by joeldudleyr3** [comment]
@mikehearn Is there a corresponding JIRA?

**Comment by mikehearn** [comment]
https://r3-cev.atlassian.net/browse/CORDA-2121

**Comment by roastario** [comment]
I believe this has been fixed by: 

https://github.com/corda/corda/pull/3985

**Comment by roastario** [comment]
After testing, latest version of corda does not suffer from this bug - closing
