### ISSUE TITLE
internal.Node.run - Exception during node startup {} java.lang.IllegalStateException: Identity specified by [c7401749-2e78-4ad2-a68f-94ee3c418ee2] "" is not one of ours!

### ISSUE THREAD

**Issue by RemHD** [corda/corda#4069]
Hi everybody I'm currently using Corda 3.2.

I have an issue while connecting one of my node with a PostgresSQL DB, I managed to do it once and then after it started to crash everytime.

The exact message is this one when I'm trying to use runnodes.bat
`[ERROR] 2018-10-12T14:24:23,172Z [main] internal.Node.run - Exception during node startup {}
java.lang.IllegalStateException: Identity specified by [c7401749-2e78-4ad2-a68f-94ee3c418ee2] (O=Renault, L=London, C=GB) is not one of ours!
	at net.corda.node.services.statemachine.StateMachineManagerImpl.initFiber(StateMachineManagerImpl.kt:438) ~[corda-node-3.2-corda.jar:?]
	at net.corda.node.services.statemachine.StateMachineManagerImpl.access$initFiber(StateMachineManagerImpl.kt:63) ~[corda-node-3.2-corda.jar:?]
	at net.corda.node.services.statemachine.StateMachineManagerImpl$restoreFibersFromCheckpoints$$inlined$locked$lambda$1.invoke(StateMachineManagerImpl.kt:228) ~[corda-node-3.2-corda.jar:?]
	at net.corda.node.services.statemachine.StateMachineManagerImpl$restoreFibersFromCheckpoints$$inlined$locked$lambda$1.invoke(StateMachineManagerImpl.kt:63) ~[corda-node-3.2-corda.jar:?]
	at net.corda.node.services.persistence.DBCheckpointStorage.forEach(DBCheckpointStorage.kt:54) ~[corda-node-3.2-corda.jar:?]
	at net.corda.node.services.statemachine.StateMachineManagerImpl.restoreFibersFromCheckpoints(StateMachineManagerImpl.kt:224) ~[corda-node-3.2-corda.jar:?]
	at net.corda.node.services.statemachine.StateMachineManagerImpl.start(StateMachineManagerImpl.kt:156) ~[corda-node-3.2-corda.jar:?]
	at net.corda.node.internal.AbstractNode$start$$inlined$apply$lambda$1.invoke(AbstractNode.kt:279) ~[corda-node-3.2-corda.jar:?]
	at net.corda.node.internal.AbstractNode$start$$inlined$apply$lambda$1.invoke(AbstractNode.kt:105) ~[corda-node-3.2-corda.jar:?]
	at net.corda.nodeapi.internal.persistence.CordaPersistence.inTopLevelTransaction(CordaPersistence.kt:152) ~[corda-node-api-3.2-corda.jar:?]
	at net.corda.nodeapi.internal.persistence.CordaPersistence.transaction(CordaPersistence.kt:138) ~[corda-node-api-3.2-corda.jar:?]
	at net.corda.nodeapi.internal.persistence.CordaPersistence.transaction(CordaPersistence.kt:124) ~[corda-node-api-3.2-corda.jar:?]
	at net.corda.nodeapi.internal.persistence.CordaPersistence.transaction(CordaPersistence.kt:131) ~[corda-node-api-3.2-corda.jar:?]
	at net.corda.node.internal.AbstractNode.start(AbstractNode.kt:278) ~[corda-node-3.2-corda.jar:?]
	at net.corda.node.internal.Node.start(Node.kt:359) ~[corda-node-3.2-corda.jar:?]
	at net.corda.node.internal.NodeStartup.startNode(NodeStartup.kt:145) ~[corda-node-3.2-corda.jar:?]
	at net.corda.node.internal.NodeStartup.run(NodeStartup.kt:115) [corda-node-3.2-corda.jar:?]
	at net.corda.node.Corda.main(Corda.kt:13) [corda-node-3.2-corda.jar:?]`

I tried to rebuild from scratch, I also cleared all my DB on Postgres. The nodes are all starting then the shell of the specified node just shut itself.

**Comment by joeldudleyr3** [comment]
It looks like you've modified your node's identity after initially connecting to the database. Did you re-run `deployNodes` or modify the node's keystores and certificates in some other way?

**Comment by RemHD** [comment]
I didn't change the node identity, but I used several times the
"deployNodes" and I think the issue is coming from the certificate and I
don't know how to release or change it.

Le ven. 19 oct. 2018 à 11:53, Joel Dudley <notifications@github.com> a
écrit :

**Comment by joeldudleyr3** [comment]
Every time you redeploy the node, you change its certificates and therefore its identity. This causes the error above.

Instead, you should keep the same node, and create and install the new CorDapp JARs by following the instructions here: https://docs.corda.net/cordapp-build-systems.html#creating-the-cordapp-jar.
