### ISSUE TITLE
Handle Exceptions - Flows doesn't catch exceptions correctly

### ISSUE THREAD

**Issue by trferreira-BR** [corda/corda#4080]
Hi,

**Description**
I was testing and receiving a result not expected for a Flow Test using TDD - JUnit simulating a Virtual Mock Network Corda and I was not able to find some logs, because there isn't a place related to logs from Nodes to check (My suggestion is to create a place to storage logs from every virtual node on a Corda Mock Network).

So, I figured out the problem on a Real Corda Network .

I simulated an error within the flow which calls FinalityFlow by passing only signed transaction (signed by origin party) using a command serviceHub.signInitialTransaction(txBuilder), 
instead to use fully transaction (signed transaction by origin party PLUS signed transaction by other party) using a command subFlow(CollectSignaturesFlow(signedTx, listOf(otherPartyFlow), CollectSignaturesFlow.tracker()))

**Logs**
```
[WARN ] 2018-10-15T18:24:01,835Z [flow-worker] interceptors.DumpHistoryOnErrorInterceptor.executeTransition - Flow [a409b59b-ce58-4caa-acf9-50210cced245] error {fiber-id=10000003, flow-id=a409b59b-ce58-4caa-acf9-50210cced245, invocation_id=3b6ed335-a5d8-47ff-a9aa-cad9957d3902, invocation_timestamp=2018-10-15T18:23:59.104Z, session_id=3b6ed335-a5d8-47ff-a9aa-cad9957d3902, session_timestamp=2018-10-15T18:23:59.104Z, thread-id=277, tx_id=FEAE39955A29C14702BFC217613E535BA8B8529C8756BACE19E6E3D814AC98D8}
**net.corda.core.transactions.SignedTransaction$SignaturesMissingException: Missing signatures for [br.com.test.contract.Contract.Commands.Transfer with pubkeys DL7BWyGVGxXdzdYADhNtwCWbdHdkfsLbrAx1RqtVRFEKzW, DL8317FTk79ADAvnLVju1QD3oXKpnJ3pkw6VNveJUxXirz] on transaction FEAE39 for net.i2p.crypto.eddsa.EdDSAPublicKey@228cb728**
	at net.corda.core.transactions.TransactionWithSignatures.verifySignaturesExcept(TransactionWithSignatures.kt:83) ~[corda-core-3.1.jar:?]
	at net.corda.core.transactions.TransactionWithSignatures.verifySignaturesExcept(TransactionWithSignatures.kt:63) ~[corda-core-3.1.jar:?]
	at net.corda.core.flows.FinalityFlow.verifyTx(FinalityFlow.kt:123) ~[corda-core-3.1.jar:?]
	at net.corda.core.flows.FinalityFlow.call(FinalityFlow.kt:69) ~[corda-core-3.1.jar:?]
	at net.corda.core.flows.FinalityFlow.call(FinalityFlow.kt:39) ~[corda-core-3.1.jar:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.subFlow(FlowStateMachineImpl.kt:281) [corda-node-3.1.jar:?]
	at net.corda.core.flows.FlowLogic.subFlow(FlowLogic.kt:312) ~[corda-core-3.1.jar:?]
	...
	at net.corda.node.services.statemachine.FlowStateMachineImpl.subFlow(FlowStateMachineImpl.kt:281) [corda-node-3.1.jar:?]
	at net.corda.core.flows.FlowLogic.subFlow(FlowLogic.kt:312) ~[corda-core-3.1.jar:?]
	...
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:225) [corda-node-3.1.jar:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:51) [corda-node-3.1.jar:?]
	at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1092) [quasar-core-0.7.10-jdk8.jar:0.7.10]
	at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:788) [quasar-core-0.7.10-jdk8.jar:0.7.10]
	at co.paralleluniverse.fibers.RunnableFiberTask.doExec(RunnableFiberTask.java:100) [quasar-core-0.7.10-jdk8.jar:0.7.10]
	at co.paralleluniverse.fibers.RunnableFiberTask.run(RunnableFiberTask.java:91) [quasar-core-0.7.10-jdk8.jar:0.7.10]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_181]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.22.Final.jar:4.1.22.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]

```
**Steps to reproduce**
```
val signedTx = serviceHub.signInitialTransaction(txBuilder)
val otherPartyFlow = initiateFlow(otherParty)
val fullySignedTx = subFlow(CollectSignaturesFlow(signedTx, listOf(otherPartyFlow), CollectSignaturesFlow.tracker()))

//Programmatically, It's not OK and the exception should have thrown on a Corda Mock Network, but It doesn't happen (It should have thrown the exception at trace above
val ftx = subFlow(FinalityFlow(signedTx))
 
//It's OK. It doesn't throw exception.
val ftx = subFlow(FinalityFlow(fullySignedTx))
```

**Version**
Corda Enterprise 3.1 and Open Source 3.2

@mikehearn @gendal @joeldudleyr3 

Best Regards,
Thiago

**Comment by trferreira-BR** [comment]
Hello Joel,

Thank you for sharing your code, but now, try to replicate this exception calling a subFlow which throws this exception making in the same test.
The problem is: When a subFlow throws an exception something like that (SignedTransaction$SignaturesMissingException), It doesn't catch at test and pass as a success.

It can be dangerous for real transaction. It should have stopped and thrown for any flow level.

Please, Tell me if I can help you with more information.

THX,
Thiago

**Comment by trferreira-BR** [comment]
Joel,

To be more complete, at @InitiatedBy, I call a flow, this flow throws an exception and its should be catch.

THX,
Thiago

**Comment by joeldudleyr3** [comment]
Thanks. Tracked here: https://r3-cev.atlassian.net/browse/CORDA-2122.

**Comment by sollecitom** [comment]
This is expected behaviour, Corda uses the exception thrown to conditionally handle a transaction which doesn't verify. Hence why your test is not failing.
