### ISSUE TITLE
docker image cannot start by docker run command

### ISSUE THREAD

**Issue by leyle** [corda/corda#4119]
I use Dockerform generate docker-compose.yml file, then I use `docker-compose up`,
all nodes started and everything is ok.
But if I use  `docker run -p port:port  some-node-img-name`, then it cannot start and throw out some error message. I paste it below

> Logs can be found in                    : /opt/corda/logs
Database connection url is              : jdbc:h2:tcp://172.17.0.2:43059/node
Advertised P2P messaging addresses      : clinica:10002
RPC connection address                  : clinica:10003
RPC admin connection address            : clinica:10005
E 17:13:00+0000 [main] internal.Node.run - Exception during node startup {}
 java.nio.channels.UnresolvedAddressException: null
	at io.netty.channel.epoll.AbstractEpollChannel.checkResolvable(AbstractEpollChannel.java:256) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.epoll.EpollServerSocketChannel.doBind(EpollServerSocketChannel.java:90) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:365) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_181]

**Comment by juliuslipp** [comment]
So if anybody wonders: It has to do with the docker network settings. You have to define an alias on the network the node is using with the nodes name, like docker-compose does. 
For example: 
Node name: clinica
- Create container and custom Network.
Container already stopped with the exception.
- Add an alias to the network (same name as node).
  In this case: `docker network connect --alias clinica NETWORKNAME CONTAINERNAME`
- Restart container.

**Comment by davidrapacchiale** [comment]
Closing this issue as it is related to an old version of the software. Either not relevant any longer, or fixed elsewhere. Please do reopen this issue if is still a valid bug on the latest version of Corda OS
