### ISSUE TITLE
AttachmentsClassLoader fails when calling setURLStreamHandlerFactory

### ISSUE THREAD

**Issue by manosbatsis** [corda/corda#4511]
* A clear description of the issue

`AttachmentsClassLoader` blindly attempts to set a custom `URLStreamHandlerFactory` by calling `URL.setURLStreamHandlerFactory`. The problem with this approach is the method can be [called at most once in a given Java Virtual Machine](https://docs.oracle.com/javase/7/docs/api/java/net/URL.html#setURLStreamHandlerFactory(java.net.URLStreamHandlerFactory)), so  
`AttachmentsClassLoader` fails in case a `URLStreamHandlerFactory` is already set by something else, e.g. by Tomcat during integration testing.

For JDK8 this can be solved with using a decorator and reflection ([example](https://stackoverflow.com/questions/41696088/register-custom-urlstreamhandler-in-spring-web-application-tomcat#answer-41760601)). As of Java 9 you can use SPI to provide handlers.

* Any logs or stack traces that you can provide (use a site like https://pastebin.com for larger logs)

 e.g. when TransactionBuilder.toSignedTransaction is called:

```
java.lang.Error: factory already defined
        at java.net.URL.setURLStreamHandlerFactory(URL.java:1112) ~[na:1.8.0_181]
        at net.corda.core.serialization.internal.AttachmentsClassLoader.<clinit>(AttachmentsClassLoader.kt:45) ~[corda-core-4.0-SNAPSHOT.jar:na]
        at net.corda.core.serialization.internal.AttachmentsClassLoaderBuilder$build$2.apply(AttachmentsClassLoader.kt:146) ~[corda-core-4.0-SNAPSHOT.jar:na]
        at net.corda.core.serialization.internal.AttachmentsClassLoaderBuilder$build$2.apply(AttachmentsClassLoader.kt:136) ~[corda-core-4.0-SNAPSHOT.jar:na]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1127) ~[na:1.8.0_181]
        at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2672) ~[na:1.8.0_181]
        at net.corda.core.serialization.internal.AttachmentsClassLoaderBuilder.build(AttachmentsClassLoader.kt:145) ~[corda-core-4.0-SNAPSHOT.jar:na]
        at net.corda.core.serialization.internal.AttachmentsClassLoaderBuilder.withAttachmentsClassloaderContext(AttachmentsClassLoader.kt:153) ~[corda-core-4.0-SNAPSHOT.jar:na]
        at net.corda.core.transactions.LedgerTransaction.verifyInternal$core(LedgerTransaction.kt:135) ~[corda-core-4.0-SNAPSHOT.jar:na]
        at net.corda.core.transactions.LedgerTransaction.verify(LedgerTransaction.kt:121) ~[corda-core-4.0-SNAPSHOT.jar:na]
        at net.corda.core.transactions.TransactionBuilder.addMissingDependency(TransactionBuilder.kt:181) ~[corda-core-4.0-SNAPSHOT.jar:na]
        at net.corda.core.transactions.TransactionBuilder.toWireTransactionWithContext$core(TransactionBuilder.kt:168) ~[corda-core-4.0-SNAPSHOT.jar:na]
        at net.corda.core.transactions.TransactionBuilder.toWireTransactionWithContext$core$default(TransactionBuilder.kt:136) ~[corda-core-4.0-SNAPSHOT.jar:na]
        at net.corda.core.transactions.TransactionBuilder.toWireTransaction(TransactionBuilder.kt:133) ~[corda-core-4.0-SNAPSHOT.jar:na]
        at net.corda.core.transactions.TransactionBuilder.toSignedTransaction(TransactionBuilder.kt:701) ~[corda-core-4.0-SNAPSHOT.jar:na]
        at net.corda.core.node.ServiceHub$DefaultImpls.signInitialTransaction(ServiceHub.kt:228) ~[corda-core-4.0-SNAPSHOT.jar:na]
        at net.corda.core.node.ServiceHub$DefaultImpls.signInitialTransaction(ServiceHub.kt:242) ~[corda-core-4.0-SNAPSHOT.jar:na]
        at net.corda.node.services.api.ServiceHubInternal$DefaultImpls.signInitialTransaction(ServiceHubInternal.kt) ~[corda-node-4.0-SNAPSHOT.jar:na]
        at net.corda.node.internal.AbstractNode$ServiceHubInternalImpl.signInitialTransaction(AbstractNode.kt:994) ~[corda-node-4.0-SNAPSHOT.jar:na]
        at net.corda.core.node.ServiceHub$DefaultImpls.signInitialTransaction(ServiceHub.kt:251) ~[corda-core-4.0-SNAPSHOT.jar:na]
        at net.corda.node.services.api.ServiceHubInternal$DefaultImpls.signInitialTransaction(ServiceHubInternal.kt) ~[corda-node-4.0-SNAPSHOT.jar:na]
        at net.corda.node.internal.AbstractNode$ServiceHubInternalImpl.signInitialTransaction(AbstractNode.kt:994) ~[corda-node-4.0-SNAPSHOT.jar:na]
```

same error when calling TransactionBuilder.verify

```
java.lang.Error: factory already defined
	at java.net.URL.setURLStreamHandlerFactory(URL.java:1112) ~[na:1.8.0_181]
	at net.corda.core.serialization.internal.AttachmentsClassLoader.<clinit>(AttachmentsClassLoader.kt:45) ~[corda-core-4.0-SNAPSHOT.jar:na]
	at net.corda.core.serialization.internal.AttachmentsClassLoaderBuilder$build$2.apply(AttachmentsClassLoader.kt:146) ~[corda-core-4.0-SNAPSHOT.jar:na]
	at net.corda.core.serialization.internal.AttachmentsClassLoaderBuilder$build$2.apply(AttachmentsClassLoader.kt:136) ~[corda-core-4.0-SNAPSHOT.jar:na]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127) ~[na:1.8.0_181]
	at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2672) ~[na:1.8.0_181]
	at net.corda.core.serialization.internal.AttachmentsClassLoaderBuilder.build(AttachmentsClassLoader.kt:145) ~[corda-core-4.0-SNAPSHOT.jar:na]
	at net.corda.core.serialization.internal.AttachmentsClassLoaderBuilder.withAttachmentsClassloaderContext(AttachmentsClassLoader.kt:153) ~[corda-core-4.0-SNAPSHOT.jar:na]
	at net.corda.core.transactions.LedgerTransaction.verifyInternal$core(LedgerTransaction.kt:135) ~[corda-core-4.0-SNAPSHOT.jar:na]
	at net.corda.core.transactions.LedgerTransaction.verify(LedgerTransaction.kt:121) ~[corda-core-4.0-SNAPSHOT.jar:na]
	at net.corda.core.transactions.TransactionBuilder.addMissingDependency(TransactionBuilder.kt:181) ~[corda-core-4.0-SNAPSHOT.jar:na]
	at net.corda.core.transactions.TransactionBuilder.toWireTransactionWithContext$core(TransactionBuilder.kt:168) ~[corda-core-4.0-SNAPSHOT.jar:na]
	at net.corda.core.transactions.TransactionBuilder.toWireTransactionWithContext$core$default(TransactionBuilder.kt:136) ~[corda-core-4.0-SNAPSHOT.jar:na]
	at net.corda.core.transactions.TransactionBuilder.toWireTransaction(TransactionBuilder.kt:133) ~[corda-core-4.0-SNAPSHOT.jar:na]
	at net.corda.core.transactions.TransactionBuilder.toLedgerTransaction(TransactionBuilder.kt:483) ~[corda-core-4.0-SNAPSHOT.jar:na]
	at net.corda.core.transactions.TransactionBuilder.verify(TransactionBuilder.kt:491) ~[corda-core-4.0-SNAPSHOT.jar:na]
	at mypackage.yo.workflow.YoFlow.call(YoWorkflow.kt:73) ~[cordapp-workflow-0.19-SNAPSHOT.jar:na]
	at mypackage.yo.workflow.YoFlow.call(YoWorkflow.kt:41) ~[cordapp-workflow-0.19-SNAPSHOT.jar:na]
```

* The version/tag/release or commit hash it occurred on

master

**Comment by tudor-malene** [comment]
Hi Manos, thank you for raising this issue.
This is the problem I suspected you had when you mentioned it.

The reason we chose this approach is that Corda is supposed to run in it's own JVM, and there is no reason for any cordapp to call `setURLStreamHandlerFactory`.

What is your setup? You mentioned in the PR that it's failing during integration tests?

**Comment by mikehearn** [comment]
Is the actual problem here that the driver API is putting too much stuff onto the node classpath? The URL stream handler factory thing is a very unfortunate part of the Java API but nonetheless, the node JVM process is our domain - roaming tomcats are dangerous, and so should be shot and have their heads mounted on the walls.

I recall someone mentioning that the driver works in a weird way and just adds everything in the host JVM onto the node classpath, which isn't how things would work in production at all. I'm not sure why it works that way for tests, but I wonder if that's the real issue here.

We can merge this as a temporary workaround but we should mark it as to be removed as part of cleanup.

**Comment by manosbatsis** [comment]
The "unfortunate part of the Java API" pretty much nails it. My fix works around breakage in cases like mine, where one can equally blame anyone assuming ownership of the JVM, without any side-effects to normal node-only  operation. I do see this as a temporary fix in terms of JDK version though, but need it for my code to work with corda 4.0

**Comment by mikehearn** [comment]
Fair enough. Tudor is already looking at how to fix the more general classpath issue.
