### ISSUE TITLE
Postgres integration runnode error

### ISSUE THREAD

**Issue by felmoreno1726** [corda/corda#4639]
Thank you for choosing to report an issue with Corda. 
Greetings my team is working on a Corda application, and we are trying to migrate to using postgres database instead of H2. The following bug was introduced by the changes made to the database configuration. The following was taken from node-directory/logs/node-ip-*:
[ERROR] 2019-01-26T19:05:24,244Z [main] internal.Node.run - Exception during node startup {}
java.security.cert.CertPathValidatorException: signature check failed
        at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135) ~[?:1.8.0_191]
        at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:233) ~[?:1.8.0_191]
        at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:141) ~[?:1.8.0_191]
        at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:80) ~[?:1.8.0_191]
        at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292) ~[?:1.8.0_191]
        at net.corda.core.identity.PartyAndCertificate.verify(PartyAndCertificate.kt:45) ~[corda-core-3.3-corda.jar:?]
        at net.corda.node.services.identity.PersistentIdentityService.verifyAndRegisterIdentity(PersistentIdentityService.kt:119) ~[corda-node-3.3-corda.jar:?]
        at net.corda.node.services.network.NetworkMapCacheImpl.<init>(PersistentNetworkMapCache.kt:47) ~[corda-node-3.3-corda.jar:?]
        at net.corda.node.internal.AbstractNode$start$4.invoke(AbstractNode.kt:208) ~[corda-node-3.3-corda.jar:?]
        at net.corda.node.internal.AbstractNode$start$4.invoke(AbstractNode.kt:105) ~[corda-node-3.3-corda.jar:?]
        at net.corda.node.internal.AbstractNode$initialiseDatabasePersistence$2.invoke(AbstractNode.kt:700) ~[corda-node-3.3-corda.jar:?]
        at net.corda.node.internal.AbstractNode$initialiseDatabasePersistence$2.invoke(AbstractNode.kt:105) ~[corda-node-3.3-corda.jar:?]
        at net.corda.nodeapi.internal.persistence.CordaPersistence.inTopLevelTransaction(CordaPersistence.kt:152) ~[corda-node-api-3.3-corda.jar:?]
        at net.corda.nodeapi.internal.persistence.CordaPersistence.transaction(CordaPersistence.kt:138) ~[corda-node-api-3.3-corda.jar:?]
        at net.corda.nodeapi.internal.persistence.CordaPersistence.transaction(CordaPersistence.kt:124) ~[corda-node-api-3.3-corda.jar:?]
        at net.corda.nodeapi.internal.persistence.CordaPersistence.transaction(CordaPersistence.kt:131) ~[corda-node-api-3.3-corda.jar:?]
        at net.corda.node.internal.AbstractNode.initialiseDatabasePersistence(AbstractNode.kt:699) ~[corda-node-3.3-corda.jar:?]
        at net.corda.node.internal.Node.initialiseDatabasePersistence(Node.kt:347) ~[corda-node-3.3-corda.jar:?]
        at net.corda.node.internal.AbstractNode.start(AbstractNode.kt:207) ~[corda-node-3.3-corda.jar:?]
        at net.corda.node.internal.Node.start(Node.kt:361) ~[corda-node-3.3-corda.jar:?]
        at net.corda.node.internal.NodeStartup.startNode(NodeStartup.kt:203) ~[corda-node-3.3-corda.jar:?]
        at net.corda.node.internal.NodeStartup.run(NodeStartup.kt:126) [corda-node-3.3-corda.jar:?]
        at net.corda.node.Corda.main(Corda.kt:13) [corda-node-3.3-corda.jar:?]
Caused by: java.security.SignatureException: Signature does not match.
        at sun.security.x509.X509CertImpl.verify(X509CertImpl.java:449) ~[?:1.8.0_191]
        at sun.security.provider.certpath.BasicChecker.verifySignature(BasicChecker.java:166) ~[?:1.8.0_191]
        at sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:147) ~[?:1.8.0_191]
        at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125) ~[?:1.8.0_191]
        ... 22 more

The following is the node.conf file:
configFile="./los/src/main/resources/node-config/nms.conf"
dataSourceProperties {
    "dataSource.password"=postgres
    "dataSource.url"="jdbc:postgresql://127.0.0.1:5432/postgres"
    "dataSource.user"=postgres
    dataSourceClassName="org.postgresql.ds.PGSimpleDataSource"
}
database {
    transactionIsolationLevel="REPEATABLE_READ"
}
jarDirs=[
    "/usr/share/java"
]
jvmArgs=[
    "-Xmx1g"
]
myLegalName="O=Node_name,L=Node_Location,C=Contry_name"
p2pAddress="localhost:10005"
rpcSettings {
    address="127.0.0.1:10006"
    adminAddress="127.0.0.1:10046"
}
rpcUsers=[
    {
        password=test
        permissions=[
            ALL
        ]
        user=user1
    }
]
webAddress="localhost:10007"

compatibilityZoneURL="http://NMS_IP:NMS_PORT"
trustStorePassword : "trustpass"
devMode : true

The machine running the instance has postgreSQL 9.6, the /usr/share/java directory contains jdbc drivers: postgresql-jdbc3-9.2.jar and postgresql-jdbc4-9.2.jar. Machine was configured to having a postgres role with postgres password. Please advice on how to resolve. Thanks

**Comment by nargas-ritu** [comment]
Please open a new issue against Corda 4.9 if the issue persists.
