### ISSUE TITLE
4.0-RC03 issues with Node Driver

### ISSUE THREAD

**Issue by manosbatsis** [corda/corda#4671]
1. `TestCordappImpl#buildCordappJar() ` attempts to scan build/libs without checking if the directory actually exists

```
java.nio.file.NoSuchFileException: /home/manos/git/corbeans/corbeans-corda-webserver/build/libs
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:427)
        at java.nio.file.Files.newDirectoryStream(Files.java:457)
        at java.nio.file.Files.list(Files.java:3451)
        at net.corda.testing.node.internal.TestCordappImpl$Companion$buildCordappJar$1.apply(TestCordappImpl.kt:102)
        at net.corda.testing.node.internal.TestCordappImpl$Companion$buildCordappJar$1.apply(TestCordappImpl.kt:38)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        at net.corda.testing.node.internal.TestCordappImpl$Companion.buildCordappJar(TestCordappImpl.kt:79)
        at net.corda.testing.node.internal.TestCordappImpl$Companion.findJars(TestCordappImpl.kt:50)
        at net.corda.testing.node.internal.TestCordappImpl.getJarFile(TestCordappImpl.kt:28)
        at net.corda.testing.node.internal.TestCordappInternal$Companion.installCordapps(TestCordappInternal.kt:33)
        at net.corda.testing.node.internal.DriverDSLImpl.startNodeInternal(DriverDSLImpl.kt:576)
        at net.corda.testing.node.internal.DriverDSLImpl.startRegisteredNode(DriverDSLImpl.kt:249)
        at net.corda.testing.node.internal.DriverDSLImpl.startRegisteredNode$default(DriverDSLImpl.kt:211)
        at net.corda.testing.node.internal.DriverDSLImpl.startSingleNotary(DriverDSLImpl.kt:489)
        at net.corda.testing.node.internal.DriverDSLImpl.startNotaries(DriverDSLImpl.kt:477)
        at net.corda.testing.node.internal.DriverDSLImpl.access$startNotaries(DriverDSLImpl.kt:80)
        at net.corda.testing.node.internal.DriverDSLImpl$start$3.invoke(DriverDSLImpl.kt:364)
        at net.corda.testing.node.internal.DriverDSLImpl$start$3.invoke(DriverDSLImpl.kt:80)

```

2. The driver will also throw an error if the directory exists without any JARs in it, which makes no sense - there should be no assumption that the driver is only used in cordapp modules - think integration tests etc.
```
java.lang.IllegalStateException: No jars were built in /home/manos/git/corbeans/corbeans-corda-webserver/build/libs
        at net.corda.testing.node.internal.TestCordappImpl$Companion$buildCordappJar$1.apply(TestCordappImpl.kt:86)
        at net.corda.testing.node.internal.TestCordappImpl$Companion$buildCordappJar$1.apply(TestCordappImpl.kt:38)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        at net.corda.testing.node.internal.TestCordappImpl$Companion.buildCordappJar(TestCordappImpl.kt:79)
        at net.corda.testing.node.internal.TestCordappImpl$Companion.findJars(TestCordappImpl.kt:50)
        at net.corda.testing.node.internal.TestCordappImpl.getJarFile(TestCordappImpl.kt:28)
        at net.corda.testing.node.internal.TestCordappInternal$Companion.installCordapps(TestCordappInternal.kt:33)
        at net.corda.testing.node.internal.DriverDSLImpl.startNodeInternal(DriverDSLImpl.kt:576)
        at net.corda.testing.node.internal.DriverDSLImpl.startRegisteredNode(DriverDSLImpl.kt:249)
        at net.corda.testing.node.internal.DriverDSLImpl.startRegisteredNode$default(DriverDSLImpl.kt:211)
        at net.corda.testing.node.internal.DriverDSLImpl.startSingleNotary(DriverDSLImpl.kt:489)
        at net.corda.testing.node.internal.DriverDSLImpl.startNotaries(DriverDSLImpl.kt:477)
        at net.corda.testing.node.internal.DriverDSLImpl.access$startNotaries(DriverDSLImpl.kt:80)
        at net.corda.testing.node.internal.DriverDSLImpl$start$3.invoke(DriverDSLImpl.kt:364)
        at net.corda.testing.node.internal.DriverDSLImpl$start$3.invoke(DriverDSLImpl.kt:80)
        at net.corda.core.internal.concurrent.CordaFutureImplKt$map$$inlined$also$lambda$1$1.invoke(CordaFutureImpl.kt:36)
        at net.corda.core.internal.concurrent.ValueOrException$DefaultImpls.capture(CordaFutureImpl.kt:130)
        at net.corda.core.internal.concurrent.OpenFuture$DefaultImpls.capture(CordaFutureImpl.kt)
        at net.corda.core.internal.concurrent.CordaFutureImpl.capture(CordaFutureImpl.kt:142)
        at net.corda.core.internal.concurrent.CordaFutureImplKt$map$$inlined$also$lambda$1.invoke(CordaFutureImpl.kt:36)
        at net.corda.core.internal.concurrent.CordaFutureImplKt$map$$inlined$also$lambda$1.invoke(CordaFutureImpl.kt)
        at net.corda.core.concurrent.ConcurrencyUtils.match(ConcurrencyUtils.kt:19)
        at net.corda.core.internal.concurrent.CordaFutureImplKt$thenMatch$1.invoke(CordaFutureImpl.kt:25)
        at net.corda.core.internal.concurrent.CordaFutureImplKt$thenMatch$1.invoke(CordaFutureImpl.kt)
        at net.corda.core.internal.concurrent.CordaFutureImpl$thenImpl$1.accept(CordaFutureImpl.kt:155)
        at net.corda.core.internal.concurrent.CordaFutureImpl$thenImpl$1.accept(CordaFutureImpl.kt:142)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at net.corda.core.internal.concurrent.CordaFutureImpl.set(CordaFutureImpl.kt:148)
        at net.corda.core.internal.concurrent.ValueOrException$DefaultImpls.capture(CordaFutureImpl.kt:129)
        at net.corda.core.internal.concurrent.OpenFuture$DefaultImpls.capture(CordaFutureImpl.kt)
        at net.corda.core.internal.concurrent.CordaFutureImpl.capture(CordaFutureImpl.kt:142)
        at net.corda.core.internal.concurrent.CordaFutureImplKt$map$$inlined$also$lambda$1.invoke(CordaFutureImpl.kt:36)
        at net.corda.core.internal.concurrent.CordaFutureImplKt$map$$inlined$also$lambda$1.invoke(CordaFutureImpl.kt)
        at net.corda.core.concurrent.ConcurrencyUtils.match(ConcurrencyUtils.kt:19)
        at net.corda.core.internal.concurrent.CordaFutureImplKt$thenMatch$1.invoke(CordaFutureImpl.kt:25)
        at net.corda.core.internal.concurrent.CordaFutureImplKt$thenMatch$1.invoke(CordaFutureImpl.kt)
        at net.corda.core.internal.concurrent.CordaFutureImpl$thenImpl$1.accept(CordaFutureImpl.kt:155)
        at net.corda.core.internal.concurrent.CordaFutureImpl$thenImpl$1.accept(CordaFutureImpl.kt:142)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at net.corda.core.internal.concurrent.CordaFutureImpl.set(CordaFutureImpl.kt:148)
        at net.corda.core.internal.concurrent.ValueOrException$DefaultImpls.capture(CordaFutureImpl.kt:129)
        at net.corda.core.internal.concurrent.OpenFuture$DefaultImpls.capture(CordaFutureImpl.kt)
        at net.corda.core.internal.concurrent.CordaFutureImpl.capture(CordaFutureImpl.kt:142)
        at net.corda.core.internal.concurrent.CordaFutureImplKt$fork$$inlined$also$lambda$1.run(CordaFutureImpl.kt:22)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by manosbatsis** [comment]
Bah. In case someone else manages to shoot themselves in the foot, don't call `net.corda.testing.node.internal.InternalTestUtilsKt#findCordapp` with an empty string
