### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: net.corda.finance.contracts.asset.OnLedgerAsset

### ISSUE THREAD

**Issue by robertmckay** [corda/corda#4724]
In Corda 4 RC1, RC2, RC3

If you extend OnLedgerAsset in a contract, the corda node fails on startup with a class not found exception for OnLedgerAsset. It compiles fine and junit test involving the contract work, just when starting an actual node it blows up.

I have tried various combinations of 

cordaCompile "net.corda:corda-finance:$corda_release_version"
cordaRuntime "net.corda:corda-finance:$corda_release_version"
cordapp "net.corda:corda-finance:$corda_release_version"

and added 
"$corda_release_group:corda-finance:$corda_release_version"

to the cordapp list in deployNodes. The corda-finance cordapp jar is indeed deployed in the various node cordapps directories.

I have also tried lots of combinations using the split corda-finance-workflows and corda-finance-contracts instead of the old corda-finance one, but it makes no difference.

https://github.com/robertmckay/cordapp-template-kotlin/commit/d5d943d4071d0da33a17dfb48636f74b7487ace9

The link above is a modified cordapp-template project that reproduces the issue. Just build it, deploy nodes and then run them.. the nodes should throw the following exception on startup:

Listening for transport dt_socket at address: 5007
Jolokia: Agent started with URL http://127.0.0.1:7007/jolokia/

   ______               __
  / ____/     _________/ /___ _
 / /     __  / ___/ __  / __ `/         Where do cryptographers go for
/ /___  /_/ / /  / /_/ / /_/ /          entertainment? The security theatre.
\____/     /_/   \__,_/\__,_/

--- Corda Open Source 4.0-RC03 (dd002ee) -------------------------------------------------------------

Logs can be found in                    : /Users/rm/IdeaProjects/cordapp-template-kotlin/build/nodes/PartyB/logs
😴  Your computer took over a second to resolve localhost due an incorrect configuration. Corda will work but start very slowly until this is fixed. 
😴  Please see https://docs.corda.net/troubleshooting.html#slow-localhost-resolution for information on how to fix this. 
😴  It will only take a few seconds for you to resolve.
⚠️   ATTENTION: This node is running in development mode! 👩‍💻   This is not safe for production deployment.
Advertised P2P messaging addresses      : localhost:10008
RPC connection address                  : localhost:10009
RPC admin connection address            : localhost:10049
Exception in thread "main" java.lang.NoClassDefFoundError: net/corda/finance/contracts/asset/OnLedgerAsset
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.corda.nodeapi.internal.ContractsJarFile.scan(ContractsScanning.kt:41)
	at net.corda.nodeapi.internal.ContractsScanningKt$withContractsInJar$contracts$1.invoke(ContractsScanning.kt:59)
	at net.corda.nodeapi.internal.ContractsScanningKt$withContractsInJar$contracts$1.invoke(ContractsScanning.kt)
	at net.corda.core.internal.InternalUtils.logElapsedTime(InternalUtils.kt:193)
	at net.corda.nodeapi.internal.ContractsScanningKt.withContractsInJar(ContractsScanning.kt:58)
	at net.corda.node.services.persistence.NodeAttachmentService$import$1.invoke(NodeAttachmentService.kt:343)
	at net.corda.node.services.persistence.NodeAttachmentService$import$1.invoke(NodeAttachmentService.kt:52)
	at net.corda.nodeapi.internal.persistence.CordaPersistence.transaction(CordaPersistence.kt:210)
	at net.corda.nodeapi.internal.persistence.CordaPersistence.transaction(CordaPersistence.kt:190)
	at net.corda.nodeapi.internal.persistence.CordaPersistence.transaction(CordaPersistence.kt:196)
	at net.corda.node.services.persistence.NodeAttachmentService.import(NodeAttachmentService.kt:342)
	at net.corda.node.services.persistence.NodeAttachmentService.privilegedImportAttachment(NodeAttachmentService.kt:294)
	at net.corda.node.internal.cordapp.CordappProviderImpl.loadContractsIntoAttachmentStore(CordappProviderImpl.kt:79)
	at net.corda.node.internal.cordapp.CordappProviderImpl.start(CordappProviderImpl.kt:39)
	at net.corda.node.internal.AbstractNode$start$7.invoke(AbstractNode.kt:373)
	at net.corda.node.internal.AbstractNode$start$7.invoke(AbstractNode.kt:118)
	at net.corda.nodeapi.internal.persistence.CordaPersistence.inTopLevelTransaction(CordaPersistence.kt:227)
	at net.corda.nodeapi.internal.persistence.CordaPersistence.transaction(CordaPersistence.kt:212)
	at net.corda.nodeapi.internal.persistence.CordaPersistence.transaction(CordaPersistence.kt:190)
	at net.corda.nodeapi.internal.persistence.CordaPersistence.transaction(CordaPersistence.kt:196)
	at net.corda.node.internal.AbstractNode.start(AbstractNode.kt:369)
	at net.corda.node.internal.Node.start(Node.kt:419)
	at net.corda.node.internal.NodeStartup.startNode(NodeStartup.kt:180)
	at net.corda.node.internal.NodeStartupCli$runProgram$2.run(NodeStartup.kt:109)
	at net.corda.node.internal.NodeStartup$initialiseAndRun$5.invoke(NodeStartup.kt:161)
	at net.corda.node.internal.NodeStartup$initialiseAndRun$5.invoke(NodeStartup.kt:116)
	at net.corda.node.internal.NodeStartupLogging$DefaultImpls.attempt(NodeStartup.kt:445)
	at net.corda.node.internal.NodeStartup.attempt(NodeStartup.kt:116)
	at net.corda.node.internal.NodeStartup.initialiseAndRun(NodeStartup.kt:159)
	at net.corda.node.internal.NodeStartupCli.runProgram(NodeStartup.kt:107)
	at net.corda.cliutils.CordaCliWrapper.call(CordaCliWrapper.kt:184)
	at net.corda.cliutils.CordaCliWrapper.call(CordaCliWrapper.kt:152)
	at picocli.CommandLine.execute(CommandLine.java:1056)
	at picocli.CommandLine.access$900(CommandLine.java:142)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1246)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1214)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1122)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1405)
	at net.corda.cliutils.CordaCliWrapperKt.start(CordaCliWrapper.kt:72)
	at net.corda.node.Corda.main(Corda.kt:13)
Caused by: java.lang.ClassNotFoundException: net.corda.finance.contracts.asset.OnLedgerAsset
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 51 more

**Comment by robertmckay** [comment]
I just tried switching to corda 5.0-SNAPSHOT, and this problem went away

**Comment by arsalankhalid** [comment]
Any updates on this? What if I don't want to use 5.0-SNAPSHOT, seems like there's no response to this, as this keeps happening when I do runnodes...

**Comment by robertmckay** [comment]
I talked to Roger Willis about it and he suggested that it would work if we include the classes from corda-finance in our own cordapp. Basically it's not currently possible to subclass contracts that are part of a different cordapp (such as corda-finance).

I should add that while 5.0-SNAPSHOT doesn't crash the node on startup anymore, it turns out that it doesn't work either.. instead you get a multiple attachment exception when trying to make transactions involving the affected contract.

**Comment by nargas-ritu** [comment]
Fixed in subsequent releases
