### ISSUE TITLE
java.lang.IllegalArgumentException: Corda service com.orcalise.NodeInterestRates$Oracle does not exist

### ISSUE THREAD

**Issue by prateektiwari7** [corda/corda#5054]
Hello Corda Team

I am ruining OracleNodeTearOffTests and Getting an error while running the node and its test cases.

Here is the screenshot of the output. 

 
![Uploading Screen Shot 2019-04-25 at 5.55.42 PM.png…]()

Please help me to find the solution. Thank you !

**Comment by prateektiwari7** [comment]
```
[INFO] 15:05:54,904 [main] connections.access.getIsolatedConnection - HHH10001501: Connection obtained from JdbcConnectionAccess [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess@5d368436] for (non-JTA) DDL execution was not in auto-commit mode; the Connection 'local transaction' will be committed and the Connection will be set into auto-commit mode.
[INFO] 15:05:54,993 [main] persistence.HibernateConfiguration.makeSessionFactoryForSchemas - Created session factory for schemas: [CommonSchemaV1(name=net.corda.core.schemas.CommonSchema, version=1), VaultSchemaV1(name=net.corda.node.services.vault.VaultSchema, version=1), NodeInfoSchemaV1(name=net.corda.node.internal.schemas.NodeInfoSchema, version=1), NodeCoreV1(name=net.corda.node.services.schema.NodeSchemaService$NodeCore, version=1)]
[INFO] 15:05:54,996 [main] internal.QueryTranslatorFactoryInitiator.initiateService - HHH000397: Using ASTQueryTranslatorFactory
[INFO] 15:05:55,000 [main] internal.InternalMockNetwork$MockNode.updateNodeInfo - Node-info has changed so submitting update. Old node-info was null
[INFO] 15:05:55,000 [main] network.PersistentNetworkMapCache.addNode - Adding node with info: NodeInfo(addresses=[mock.node:1000], legalIdentitiesAndCerts=[O=Bob Plc, L=Rome, C=IT], platformVersion=4, serial=1556184955000)
[INFO] 15:05:55,004 [main] network.PersistentNetworkMapCache.addNode - No previous node found
[INFO] 15:05:55,018 [main] internal.InternalMockNetwork$MockNode.updateNodeInfo - New node-info: NodeInfo(addresses=[mock.node:1000], legalIdentitiesAndCerts=[O=Bob Plc, L=Rome, C=IT], platformVersion=4, serial=1556184955000)
[INFO] 15:05:55,032 [main] network.NetworkMapUpdater.start - Auto-accept enabled for network parameter changes which modify only: [epoch, modifiedTime, packageOwnership, whitelistedContractImplementations]
[INFO] 15:05:55,038 [MockNode-3-2] network.PersistentNetworkMapCache.addNode - Adding node with info: NodeInfo(addresses=[mock.node:1000], legalIdentitiesAndCerts=[O=Bob Plc, L=Rome, C=IT], platformVersion=4, serial=1556184955000)
[INFO] 15:05:55,046 [MockNode-3-2] network.PersistentNetworkMapCache.addNode - Previous node was identical to incoming one - doing nothing
[INFO] 15:05:55,075 [main] ClassloaderUtils.logElapsedTime - Contracts loading for '/var/folders/3s/pl0yszb56x7_mrlyxzv1hrjr0000gn/T/attachment7184807313502172400.jar' took 24 msec
[INFO] 15:05:55,109 [main] persistence.NodeAttachmentService.invoke - Stored new attachment: id=3D880AF108AF07990AC2A6151F124A2392DD267FD03BE21324C6B3AE2C8009AC uploader=app filename=null
[INFO] 15:05:55,128 [main] statemachine.SingleThreadedStateMachineManager.invoke - Node ready, info: NodeInfo(addresses=[mock.node:1000], legalIdentitiesAndCerts=[O=Bob Plc, L=Rome, C=IT], platformVersion=4, serial=1556184955000)
[INFO] 15:05:55,132 [main] network.PersistentNetworkMapCache.addNode - Adding node with info: NodeInfo(addresses=[mock.node:1000], legalIdentitiesAndCerts=[O=Notary Service, L=Zurich, C=CH], platformVersion=4, serial=1556184949443)
[INFO] 15:05:55,135 [main] network.PersistentNetworkMapCache.addNode - No previous node found
[INFO] 15:05:55,161 [main] network.PersistentNetworkMapCache.addNode - Adding node with info: NodeInfo(addresses=[mock.node:1000], legalIdentitiesAndCerts=[O=Bob Plc, L=Rome, C=IT], platformVersion=4, serial=1556184955000)
[INFO] 15:05:55,163 [main] network.PersistentNetworkMapCache.addNode - No previous node found
[INFO] 15:05:55,183 [main] network.PersistentNetworkMapCache.addNode - Adding node with info: NodeInfo(addresses=[mock.node:1000], legalIdentitiesAndCerts=[O=Alice Corp, L=Madrid, C=ES], platformVersion=4, serial=1556184952891)
[INFO] 15:05:55,189 [main] network.PersistentNetworkMapCache.addNode - No previous node found
[INFO] 15:05:55,210 [main] network.PersistentNetworkMapCache.addNode - Adding node with info: NodeInfo(addresses=[mock.node:1000], legalIdentitiesAndCerts=[O=Bob Plc, L=Rome, C=IT], platformVersion=4, serial=1556184955000)
[INFO] 15:05:55,214 [main] network.PersistentNetworkMapCache.addNode - No previous node found
[INFO] 15:05:55,232 [main] network.PersistentNetworkMapCache.addNode - Adding node with info: NodeInfo(addresses=[mock.node:1000], legalIdentitiesAndCerts=[O=Bob Plc, L=Rome, C=IT], platformVersion=4, serial=1556184955000)
[INFO] 15:05:55,232 [main] network.PersistentNetworkMapCache.addNode - Previous node was identical to incoming one - doing nothing
[INFO] 15:05:55,233 [main] network.PersistentNetworkMapCache.addNode - Adding node with info: NodeInfo(addresses=[mock.node:1000], legalIdentitiesAndCerts=[O=Bob Plc, L=Rome, C=IT], platformVersion=4, serial=1556184955000)
[INFO] 15:05:55,233 [main] network.PersistentNetworkMapCache.addNode - Previous node was identical to incoming one - doing nothing
[INFO] 15:05:55,279 [main] pool.HikariPool.shutdown - HikariPool-1 - Close initiated...
[INFO] 15:05:55,287 [main] pool.HikariPool.shutdown - HikariPool-1 - Closed.
[INFO] 15:05:55,325 [main] pool.HikariPool.shutdown - HikariPool-2 - Close initiated...
[INFO] 15:05:55,329 [main] pool.HikariPool.shutdown - HikariPool-2 - Closed.
[INFO] 15:05:55,331 [main] pool.HikariPool.shutdown - HikariPool-3 - Close initiated...
[INFO] 15:05:55,334 [main] pool.HikariPool.shutdown - HikariPool-3 - Closed.

java.lang.IllegalArgumentException: Corda service com.orcalise.NodeInterestRates$Oracle does not exist

	at net.corda.node.internal.AbstractNode$ServiceHubInternalImpl.cordaService(AbstractNode.kt:985)
	at net.corda.testing.node.internal.InternalMockNetwork$MockNode$createStartedNode$1.cordaService(InternalMockNetwork.kt)
	at com.orcalise.OracleNodeTearOffTests$setUp$$inlined$apply$lambda$1.invoke(OracleNodeTearOffTests.kt:60)
	at com.orcalise.OracleNodeTearOffTests$setUp$$inlined$apply$lambda$1.invoke(OracleNodeTearOffTests.kt:34)
	at net.corda.testing.node.StartedMockNode$transaction$1.invoke(MockNetwork.kt:239)
	at net.corda.testing.node.StartedMockNode$transaction$1.invoke(MockNetwork.kt:172)
	at net.corda.nodeapi.internal.persistence.CordaPersistence.inTopLevelTransaction(CordaPersistence.kt:236)
	at net.corda.nodeapi.internal.persistence.CordaPersistence.transaction(CordaPersistence.kt:221)
	at net.corda.nodeapi.internal.persistence.CordaPersistence.transaction(CordaPersistence.kt:199)
	at net.corda.nodeapi.internal.persistence.CordaPersistence.transaction(CordaPersistence.kt:205)
	at net.corda.testing.node.StartedMockNode.transaction(MockNetwork.kt:238)
	at com.orcalise.OracleNodeTearOffTests.setUp(OracleNodeTearOffTests.kt:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

```

**Comment by nargas-ritu** [comment]
Can't reproduce in 4.8.x
