### ISSUE TITLE
ActiveMQ Shuts Down But Node Does Not

### ISSUE THREAD

**Issue by opticyclic** [corda/corda#5082]
This replicates the issue that @gendal posted at https://r3-cev.atlassian.net/browse/CORDA-2620

The symptom from the end user perspective was that data was not populated on the web page.

In the background the REST API was calling the RPC methods and never returning.

However, the CRaSH shell was showing no errors. Only on exit is the error below output to the console.

**CRaSH Output**

Notary:
```
java -jar corda.jar 
______               __
/ ____/     _________/ /___ _
/ /     __  / ___/ __  / __ `/         Computer science and finance together.
/ /___  /_/ / /  / /_/ / /_/ /          You should see our crazy Christmas parties!
\____/     /_/   \__,_/\__,_/
--- Corda Open Source 4.0 (503a2ff) -------------------------------------------------------------
Logs can be found in                    : /Projects/blockchain/build/nodes/Notary/logs
! ATTENTION: This node is running in development mode!  This is not safe for production deployment.
Advertised P2P messaging addresses      : localhost:10001
RPC connection address                  : localhost:10002
RPC admin connection address            : localhost:10003
Loaded 0 CorDapp(s)                     :
Node for "Notary" started up and registered in 22.51 sec
Welcome to the Corda interactive shell.
Useful commands include 'help' to see what is available, and 'bye' to shut down the node.
Tue Apr 30 16:19:33 EDT 2019>>> exit
Have a good day!
Exception in thread "Command line shell terminator" ActiveMQObjectClosedException[errorType=OBJECT_CLOSED message=AMQ119019: Session is closed]
at org.apache.activemq.artemis.core.client.impl.ClientSessionImpl.checkClosed(ClientSessionImpl.java:1950)
at org.apache.activemq.artemis.core.client.impl.ClientSessionImpl.commit(ClientSessionImpl.java:840)
at org.apache.activemq.artemis.core.client.impl.ClientSessionImpl.commit(ClientSessionImpl.java:835)
at net.corda.node.services.messaging.P2PMessagingClient.stop(P2PMessagingClient.kt:436)
at net.corda.node.services.messaging.P2PMessagingClient.close(P2PMessagingClient.kt:462)
at net.corda.node.internal.AbstractNode$closeOnStop$1.invoke(AbstractNode.kt:255)
at net.corda.node.internal.AbstractNode$closeOnStop$1.invoke(AbstractNode.kt:120)
at net.corda.node.internal.AbstractNode.stop(AbstractNode.kt:803)
at net.corda.node.internal.Node.stop(Node.kt:520)
at net.corda.node.internal.NodeStartup$startNode$2$1$1.invoke(NodeStartup.kt:199)
at net.corda.node.internal.NodeStartup$startNode$2$1$1.invoke(NodeStartup.kt:117)
at net.corda.tools.shell.InteractiveShell$runLocalShell$4.invoke(InteractiveShell.kt:155)
at net.corda.tools.shell.InteractiveShell$runLocalShell$4.invoke(InteractiveShell.kt:74)
at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

Node
```
java -jar corda.jar
______               __
/ ____/     _________/ /___ _
/ /     __  / ___/ __  / __ `/         Always borrow money from a pessimist.
/ /___  /_/ / /  / /_/ / /_/ /          He won't expect it back.
\____/     /_/   \__,_/\__,_/
--- Corda Open Source 4.0 (503a2ff) -------------------------------------------------------------
Logs can be found in                    : /Projects/blockchain/build/nodes/BankA/logs
! ATTENTION: This node is running in development mode!  This is not safe for production deployment.
Advertised P2P messaging addresses      : localhost:10007
RPC connection address                  : localhost:10008
RPC admin connection address            : localhost:10009
Loaded 2 CorDapp(s)                     : Contract CorDapp: Contracts version 1 by vendor Demo with licence Unknown, Workflow CorDapp: Workflows version 1 by vendor Demo with licence Unknown
Node for "BankA" started up and registered in 43.4 sec
Welcome to the Corda interactive shell.
Useful commands include 'help' to see what is available, and 'bye' to shut down the node.
Tue Apr 30 16:20:23 EDT 2019>>> exit
Have a good day!
Exception in thread "Command line shell terminator" ActiveMQObjectClosedException[errorType=OBJECT_CLOSED message=AMQ119019: Session is closed]
at org.apache.activemq.artemis.core.client.impl.ClientSessionImpl.checkClosed(ClientSessionImpl.java:1950)
at org.apache.activemq.artemis.core.client.impl.ClientSessionImpl.commit(ClientSessionImpl.java:840)
at org.apache.activemq.artemis.core.client.impl.ClientSessionImpl.commit(ClientSessionImpl.java:835)
at net.corda.node.services.messaging.P2PMessagingClient.stop(P2PMessagingClient.kt:436)
at net.corda.node.services.messaging.P2PMessagingClient.close(P2PMessagingClient.kt:462)
at net.corda.node.internal.AbstractNode$closeOnStop$1.invoke(AbstractNode.kt:255)
at net.corda.node.internal.AbstractNode$closeOnStop$1.invoke(AbstractNode.kt:120)
at net.corda.node.internal.AbstractNode.stop(AbstractNode.kt:803)
at net.corda.node.internal.Node.stop(Node.kt:520)
at net.corda.node.internal.NodeStartup$startNode$2$1$1.invoke(NodeStartup.kt:199)
at net.corda.node.internal.NodeStartup$startNode$2$1$1.invoke(NodeStartup.kt:117)
at net.corda.tools.shell.InteractiveShell$runLocalShell$4.invoke(InteractiveShell.kt:155)
at net.corda.tools.shell.InteractiveShell$runLocalShell$4.invoke(InteractiveShell.kt:74)
at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Shutting down ...
```
The logs show similar information

```
[INFO ] 2019-04-30T20:20:23,701Z [main] rpc.RPCServer.start - Starting RPC server with configuration RPCServerConfiguration(rpcThreadPoolSize=4, reapInterval=PT1S, deduplicationCacheExpiry=PT24H)
[WARN ] 2019-05-01T02:29:06,265Z [Thread-23 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$5@19574274)] core.client.fail - AMQ212037: Connection failure has been detected: AMQ119014: Did not receive data from /127.0.0.1:48374 within the 60,000ms connection TTL. The connection will now be closed. [code=CONNECTION_TIMEDOUT]
[WARN ] 2019-05-01T02:29:06,265Z [Thread-18 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$5@5a564a61)] core.client.fail - AMQ212037: Connection failure has been detected: AMQ119014: Did not receive data from /127.0.0.1:34808 within the 60,000ms connection TTL. The connection will now be closed. [code=CONNECTION_TIMEDOUT]
[WARN ] 2019-05-01T02:29:06,436Z [Thread-18 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$5@5a564a61)] core.client.fail - AMQ212037: Connection failure has been detected: AMQ119014: Did not receive data from /127.0.0.1:34810 within the 60,000ms connection TTL. The connection will now be closed. [code=CONNECTION_TIMEDOUT]
[WARN ] 2019-05-01T02:29:06,463Z [Thread-18 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$5@5a564a61)] core.client.fail - AMQ212037: Connection failure has been detected: AMQ119014: Did not receive data from /127.0.0.1:34806 within the 60,000ms connection TTL. The connection will now be closed. [code=CONNECTION_TIMEDOUT]
```

This was replicated by running the nodes on a laptop, closing the lid, then opening it a few hours later.

The point is that ActiveMQ has shut down within the node.

The node either needs to restart ActiveMQ when it gets shut down or the node itself needs to shutdown.

Staying alive in a zombie state is confusing for the user.

**Comment by peterli-r3** [comment]
Hi Opticyclic,

With Corda 5 coming soon, we are closing up the issues prior to Corda v4.5. Thank you for your contribution to Corda!

Please feel free to contact [devrel@r3.com](mailto:devrel@r3.com) if you need any further information
