### ISSUE TITLE
OutOfMemoryError exceptions when running integration tests.

### ISSUE THREAD

**Issue by chrisr3** [corda/corda#535]
I am trying to run the integration tests on a PC with 6 GB of RAM. However, the following tests are triggering `OutOfMemoryError` exceptions:

    net.corda.services.messaging.P2PMessagingTest
    net.corda.node.utilities.JDBCHashMapTestSuite
    net.corda.node.services.RaftNotaryServiceTests
    net.corda.node.services.BFTNotaryServiceTests

I have managed to generate the following stack traces:
```java
BFTNotaryServiceTests:

java.lang.OutOfMemoryError: Java heap space
	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
	at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
	at org.apache.activemq.artemis.core.io.nio.NIOSequentialFile.fill(NIOSequentialFile.java:93)
	at org.apache.activemq.artemis.core.journal.impl.JournalFilesRepository.createFile0(JournalFilesRepository.java:575)
	at org.apache.activemq.artemis.core.journal.impl.JournalFilesRepository.createFile(JournalFilesRepository.java:529)
	at org.apache.activemq.artemis.core.journal.impl.JournalFilesRepository.ensureMinFiles(JournalFilesRepository.java:199)
	at org.apache.activemq.artemis.core.journal.impl.JournalImpl.setUpCurrentFile(JournalImpl.java:2810)
	at org.apache.activemq.artemis.core.journal.impl.JournalImpl.load(JournalImpl.java:1869)
	at org.apache.activemq.artemis.core.journal.impl.JournalImpl.load(JournalImpl.java:1268)
	at org.apache.activemq.artemis.core.journal.impl.JournalImpl.load(JournalImpl.java:1252)
	at org.apache.activemq.artemis.core.persistence.impl.journal.AbstractJournalStorageManager.loadMessageJournal(AbstractJournalStorageManager.java:837)
	at org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl.loadJournals(ActiveMQServerImpl.java:2213)
	at org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl.initialisePart2(ActiveMQServerImpl.java:2067)
	at org.apache.activemq.artemis.core.server.impl.LiveOnlyActivation.run(LiveOnlyActivation.java:64)
	at org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl.internalStart(ActiveMQServerImpl.java:520)
	at org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl.start(ActiveMQServerImpl.java:469)
	at net.corda.node.services.messaging.ArtemisMessagingServer.configureAndStartServer(ArtemisMessagingServer.kt:148)
	at net.corda.node.services.messaging.ArtemisMessagingServer.start(ArtemisMessagingServer.kt:119)
	at net.corda.node.internal.Node.startMessagingService(Node.kt:179)
	at net.corda.node.internal.AbstractNode$start$3.invoke(AbstractNode.kt:236)
	at net.corda.node.internal.AbstractNode$start$3.invoke(AbstractNode.kt:78)
	at net.corda.node.internal.AbstractNode$initialiseDatabasePersistence$2.invoke(AbstractNode.kt:343)
	at net.corda.node.internal.AbstractNode$initialiseDatabasePersistence$2.invoke(AbstractNode.kt:78)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:69)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:57)
	at net.corda.node.utilities.DatabaseSupportKt.databaseTransaction(DatabaseSupport.kt:39)
	at net.corda.node.internal.AbstractNode.initialiseDatabasePersistence(AbstractNode.kt:342)
	at net.corda.node.internal.Node.initialiseDatabasePersistence(Node.kt:231)
	at net.corda.node.internal.AbstractNode.start(AbstractNode.kt:212)
	at net.corda.node.internal.Node.start(Node.kt:238)
	at net.corda.testing.node.NodeBasedTest.startNodeInternal(NodeBasedTest.kt:139)
	at net.corda.testing.node.NodeBasedTest.startNetworkMapNode(NodeBasedTest.kt:61)
```
and
```java
RaftNotaryServiceTests:

java.lang.OutOfMemoryError: Java heap space
	at io.netty.buffer.UnpooledHeapByteBuf.<init>(UnpooledHeapByteBuf.java:46)
	at io.netty.buffer.UnpooledUnsafeHeapByteBuf.<init>(UnpooledUnsafeHeapByteBuf.java:29)
	at io.netty.buffer.UnpooledByteBufAllocator.newHeapBuffer(UnpooledByteBufAllocator.java:59)
	at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:160)
	at io.netty.buffer.Unpooled.buffer(Unpooled.java:135)
	at org.apache.activemq.artemis.api.core.ActiveMQBuffers.fixedBuffer(ActiveMQBuffers.java:95)
	at org.apache.activemq.artemis.core.io.buffer.TimedBuffer.<init>(TimedBuffer.java:108)
	at org.apache.activemq.artemis.core.io.AbstractSequentialFileFactory.<init>(AbstractSequentialFileFactory.java:78)
	at org.apache.activemq.artemis.core.io.nio.NIOSequentialFileFactory.<init>(NIOSequentialFileFactory.java:65)
	at org.apache.activemq.artemis.core.persistence.impl.journal.JournalStorageManager.init(JournalStorageManager.java:133)
	at org.apache.activemq.artemis.core.persistence.impl.journal.AbstractJournalStorageManager.<init>(AbstractJournalStorageManager.java:216)
	at org.apache.activemq.artemis.core.persistence.impl.journal.JournalStorageManager.<init>(JournalStorageManager.java:104)
	at org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl.createStorageManager(ActiveMQServerImpl.java:1863)
	at org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl.initialisePart1(ActiveMQServerImpl.java:2000)
	at org.apache.activemq.artemis.core.server.impl.LiveOnlyActivation.run(LiveOnlyActivation.java:62)
	at org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl.internalStart(ActiveMQServerImpl.java:520)
	at org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl.start(ActiveMQServerImpl.java:469)
	at net.corda.node.services.messaging.ArtemisMessagingServer.configureAndStartServer(ArtemisMessagingServer.kt:148)
	at net.corda.node.services.messaging.ArtemisMessagingServer.start(ArtemisMessagingServer.kt:119)
	at net.corda.node.internal.Node.startMessagingService(Node.kt:179)
	at net.corda.node.internal.AbstractNode$start$3.invoke(AbstractNode.kt:236)
	at net.corda.node.internal.AbstractNode$start$3.invoke(AbstractNode.kt:78)
	at net.corda.node.internal.AbstractNode$initialiseDatabasePersistence$2.invoke(AbstractNode.kt:343)
	at net.corda.node.internal.AbstractNode$initialiseDatabasePersistence$2.invoke(AbstractNode.kt:78)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:69)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:57)
	at net.corda.node.utilities.DatabaseSupportKt.databaseTransaction(DatabaseSupport.kt:39)
	at net.corda.node.internal.AbstractNode.initialiseDatabasePersistence(AbstractNode.kt:342)
	at net.corda.node.internal.Node.initialiseDatabasePersistence(Node.kt:231)
	at net.corda.node.internal.AbstractNode.start(AbstractNode.kt:212)
	at net.corda.node.internal.Node.start(Node.kt:238)
	at net.corda.testing.node.NodeBasedTest.startNodeInternal(NodeBasedTest.kt:139)
```

**Comment by mikehearn** [comment]
Can you fix it by adjusting this line?

https://github.com/corda/corda/blob/master/node/capsule/build.gradle#L60

It's not machine RAM that matters, it's max heap size as configured in the JVM. Try whacking that up to 600mb or 1 gigabyte and see if that fixes it.

**Comment by chrisr3** [comment]
I was expecting the error message to say `OutOfMemoryError: Metaspace`, because I only see these errors on my machine with 6 GB RAM. (I would have expected *everyone* to see errors due to an undersized heap.) But I can certainly try increasing the heap size.

**Comment by chrisr3** [comment]
Another OOM exception message from `net.corda.services.messaging.P2PMessagingTest`:
```
network map will work after restart

java.lang.OutOfMemoryError: GC overhead limit exceeded
```

**Comment by mikehearn** [comment]
Weird. I can run the integration tests OK on my laptop. But I have 16mb.

Why do you only have 6 gig of RAM? Is your machine incredibly old?

**Comment by chrisr3** [comment]
I do not consider something bought in 2009 to be "incredibly old". _That_ particular honour belongs to my 200 MHz Pentium MMX machine ;-).

**Comment by chrisr3** [comment]
I've upgraded my PC to have 12 GB of RAM, and I can now run the integration tests again. It would seem that anything less than 10 GB is no longer enough to develop Corda.

**Comment by mikehearn** [comment]
Powers of two are too mainstream for you? :)

**Comment by chrisr3** [comment]
Long, long ago, I received this piece of wisdom from the PC Gods who created my PC:
> The Socket LGA 1366 motherboard work withgreatest performance/bandwidth to the RAM when it is running in Tripple Channel mode. If you put multiples of two RAM modules in rather than multiples of 3 it will run in Dual Channel mode which will decrease the bandwidth for access to the RAM. If you absolutly must put in a 4th module if your use of the system requires more RAM, but slower access to it, then if you contact our friendly sales team with your order number they should be able to let you know the specification of the RAM installed for you to obtain a single module from the manufacturers.

So 3 x 4 GB modules it is...

**Comment by mikehearn** [comment]
Today I learned!
