### ISSUE TITLE
A StateRef cannot be both an input and a reference input in the same transaction

### ISSUE THREAD

**Issue by FredericHeem** [corda/corda#5365]
A problem occurs when using a state which has a [LinearPointer](https://github.com/FredericHeem/fuzz-poker/blob/checkForInputsAndReferencesOverlap/cordapp-example/contracts-kotlin/src/main/kotlin/com/example/state/SettlementState.kt#L25) in a [transaction that contains the pointed state](https://github.com/FredericHeem/fuzz-poker/blob/checkForInputsAndReferencesOverlap/cordapp-example/workflows-kotlin/src/main/kotlin/com/example/flow/PositionUpdate.kt#L69).

Here are the steps to reproduce the exception.
Check the code at the right branch:
```
$ git clone git@github.com:FredericHeem/fuzz-poker.git samples -b checkForInputsAndReferencesOverlap
$ cd samples/cordapp-example
$ ./gradlew build
```

Note: Corda version 4.1

```
java.lang.IllegalArgumentException: A StateRef cannot be both an input and a reference input in the same transaction.

	at net.corda.core.transactions.TransactionBuilder.checkForInputsAndReferencesOverlap(TransactionBuilder.kt:472)
	at net.corda.core.transactions.TransactionBuilder.addReferenceState(TransactionBuilder.kt:548)
	at net.corda.core.transactions.TransactionBuilder.resolveStatePointers(TransactionBuilder.kt:505)
	at net.corda.core.transactions.TransactionBuilder.addOutputState(TransactionBuilder.kt:568)
	at net.corda.core.transactions.TransactionBuilder.addOutputState(TransactionBuilder.kt:586)
	at net.corda.core.transactions.TransactionBuilder.addOutputState$default(TransactionBuilder.kt:585)
	at net.corda.core.transactions.TransactionBuilder.addOutputState(TransactionBuilder.kt:605)
	at net.corda.core.transactions.TransactionBuilder.addOutputState$default(TransactionBuilder.kt:600)
	at com.example.flow.PositionUpdateFlow$Initiator.call(PositionUpdate.kt:72)
```

**Comment by roger-that-dev** [comment]
Hi @FredericHeem This is by design. It doesn't make sense to have a single state as both a reference and a regular input state. This is because the reference state would immediately become consumed when the notary signs over the transaction. The notary service also checks that all reference states have not been consumed, so I believe it would be impossible to commit such a transaction.

**Comment by kid101** [comment]
Yes, It makes sense if there are only Input states and reference Input in the Tx, However, If there is an equivalent Output state as well in the Tx like in the [sample  provided](https://github.com/FredericHeem/fuzz-poker/blob/checkForInputsAndReferencesOverlap/cordapp-example/workflows-kotlin/src/main/kotlin/com/example/flow/PositionUpdate.kt#L69). Position state is added both as an input and output? wouldn't it make sense as it's linear pointer?  otherwise one would need to create two Tx to do something like in the sample ?
