### ISSUE TITLE
Checkpoint dump does not work in non-validating notary node

### ISSUE THREAD

**Issue by mhjort** [corda/corda#5479]
The checkpoint dump tool does not work in non-validating notary node. The tool is not mentioned in Open Source documentation but the code is in Open Source version and documentation can be found from Enterprise Version site https://docs.corda.r3.com/checkpoint-tooling.html.

The dump runs successfully but all the entries in zip file contain following error:
```
[INFO ] 2019-09-16T13:18:03,776Z [main] rpc.CheckpointDumper.accept - Failed to deserialise checkpoint with id: D5F7B4D67D7083FE8D167718660C72FC68C2DC273867AF4E279CA94835C5FA5B {}
com.fasterxml.jackson.databind.JsonMappingException: net.corda.core.transactions.FilteredTransaction cannot be cast to net.corda.core.transactions.SignedTransaction (through reference chain: net.corda.node.services.rpc.CheckpointDumper$CheckpointJson["activeSessions"]->ja
va.util.ArrayList[0]->net.corda.node.services.rpc.CheckpointDumper$ActiveSession["receivedMessages"]->java.util.Collections$SingletonList[0]->net.corda.node.services.statemachine.ReceivedSessionMessage["message"]->net.corda.node.services.statemachine.ExistingSessionMessag
e["payload"]->net.corda.node.services.statemachine.DataSessionMessage["payload"]->net.corda.core.flows.NotarisationPayload["signedTransaction"])
```

The node log contains following error:
```
Caused by: java.lang.ClassCastException: net.corda.core.transactions.FilteredTransaction cannot be cast to net.corda.core.transactions.SignedTransaction
        at net.corda.core.flows.NotarisationPayload.getSignedTransaction(NotarisationRequest.kt:94) ~[corda-core-3.4.20180718.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:687) ~[jackson-databind-2.9.2.jar:2.9.2]
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719) ~[jackson-databind-2.9.2.jar:2.9.2]
        ... 58 more
```

Most probably this is due to the fact that the full `SignedTransaction` is not sent to non-validating notary and the dump tool does not handle that case properly.

**Comment by peterli-r3** [comment]
Hi mhjort

With Corda 5 coming soon, we are closing up the issues prior to Corda v4.5. Thank you for your contribution to Corda!

Please feel free to contact devrel@r3.com if you need any further information
