### ISSUE TITLE
FinalityFlow not accepting empty collection.

### ISSUE THREAD

**Issue by vchaurasia95** [corda/corda#5485]
While executing a Single Party Transaction the Flow throws a "Parameter specified as non-null is null" error while invoking the FinalityFlow. 

Exception happening in log:

```log
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.collections.CollectionsKt__MutableCollectionsKt.addAll, parameter elements
	at kotlin.collections.CollectionsKt__MutableCollectionsKt.addAll(MutableCollections.kt) ~[kotlin-stdlib-1.2.71.jar:1.2.71-release-64 (1.2.71)]
	at net.corda.core.flows.FinalityFlow.extractExternalParticipants(FinalityFlow.kt:285) ~[corda-core-4.1.jar:?]
	at net.corda.core.flows.FinalityFlow.call(FinalityFlow.kt:134) ~[corda-core-4.1.jar:?]
	at net.corda.core.flows.FinalityFlow.call(FinalityFlow.kt:39) ~[corda-core-4.1.jar:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.subFlow(FlowStateMachineImpl.kt:329) ~[corda-node-4.1.jar:?]
	at net.corda.core.flows.FlowLogic.subFlow(FlowLogic.kt:314) ~[corda-core-4.1.jar:?]
	at com.template.flows.StartHeartBeatFlow.call(StartHeartBeatFlow.java:24) ~[?:?]
	at com.template.flows.StartHeartBeatFlow.call(StartHeartBeatFlow.java:11) ~[?:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:269) ~[corda-node-4.1.jar:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:45) ~[corda-node-4.1.jar:?]
	at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1092) ~[quasar-core-0.7.10-jdk8.jar:0.7.10]
	at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:788) ~[quasar-core-0.7.10-jdk8.jar:0.7.10]
	at co.paralleluniverse.fibers.RunnableFiberTask.doExec(RunnableFiberTask.java:100) ~[quasar-core-0.7.10-jdk8.jar:0.7.10]
	at co.paralleluniverse.fibers.RunnableFiberTask.run(RunnableFiberTask.java:91) ~[quasar-core-0.7.10-jdk8.jar:0.7.10]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_221]
	at net.corda.node.utilities.AffinityExecutor$ServiceAffinityExecutor$1$thread$1.run(AffinityExecutor.kt:63) ~[corda-node-4.1.jar:?]
```

For more info please find the below the attached log file:

[node-A2ML27052.log](https://github.com/corda/corda/files/3626038/node-A2ML27052.log)

```kotlin
public Void call() throws FlowException {
        Party notary = getServiceHub().getNetworkMapCache().getNotaryIdentities().get(0);
        HeartBeatState output = new HeartBeatState(getOurIdentity());
        Command command =new Command(new HeartBeatContract.Beat(),getOurIdentity().getOwningKey());
        TransactionBuilder txBuilder = new TransactionBuilder(notary)
                .addOutputState(output)
                .addCommand(command);
        txBuilder.verify(getServiceHub());
        SignedTransaction signedTx = getServiceHub().signInitialTransaction(txBuilder);
        subFlow(new FinalityFlow(signedTx, Collections.emptyList()));
        return null;
    }
```

**Comment by lankydan** [comment]
Looks like error is happening here:

```kotlin
private fun extractExternalParticipants(ltx: LedgerTransaction): Set<Party> {
        val participants = ltx.outputStates.flatMap { it.participants } + ltx.inputStates.flatMap { it.participants }
        return groupAbstractPartyByWellKnownParty(serviceHub, participants).keys - serviceHub.myInfo.legalIdentities
    }
```

This is a bit weird.

It suggests ` ltx.inputStates` is `null` but the field itself is not nullable...
