### ISSUE TITLE
NullPointerException On Test Exit

### ISSUE THREAD

**Issue by opticyclic** [corda/corda#5544]
In a DriverDSL test using corda_release_version = '4.3-RC01' after calling a flow the test hangs

    return subFlow(FinalityFlow(locallySignedTx, emptyList()))

The following error is thrown:

```
ERROR net.corda.nodeapi.internal.bridging.BridgeControlListener - Unable to process bridge control message
java.lang.NullPointerException: null
	at java.util.HashMap.putMapEntries(HashMap.java:501)
	at java.util.HashMap.putAll(HashMap.java:785)
	at java.util.Collections$SynchronizedMap.putAll(Collections.java:2594)
	at ch.qos.logback.classic.util.LogbackMDCAdapter.setContextMap(LogbackMDCAdapter.java:197)
	at org.slf4j.MDC.setContextMap(MDC.java:264)
	at net.corda.nodeapi.internal.bridging.AMQPBridgeManager$AMQPBridge.withMDC(AMQPBridgeManager.kt:94)
	at net.corda.nodeapi.internal.bridging.AMQPBridgeManager$AMQPBridge.logInfoWithMDC(AMQPBridgeManager.kt:104)
	at net.corda.nodeapi.internal.bridging.AMQPBridgeManager$AMQPBridge.start(AMQPBridgeManager.kt:115)
	at net.corda.nodeapi.internal.bridging.AMQPBridgeManager.deployBridge(AMQPBridgeManager.kt:229)
	at net.corda.nodeapi.internal.bridging.BridgeControlListener.processControlMessage(BridgeControlListener.kt:115)
	at net.corda.nodeapi.internal.bridging.BridgeControlListener.access$processControlMessage(BridgeControlListener.kt:19)
	at net.corda.nodeapi.internal.bridging.BridgeControlListener$start$1.onMessage(BridgeControlListener.kt:53)
	at org.apache.activemq.artemis.core.client.impl.ClientConsumerImpl.callOnMessage(ClientConsumerImpl.java:1002)
	at org.apache.activemq.artemis.core.client.impl.ClientConsumerImpl.access$400(ClientConsumerImpl.java:50)
	at org.apache.activemq.artemis.core.client.impl.ClientConsumerImpl$Runner.run(ClientConsumerImpl.java:1125)
	at org.apache.activemq.artemis.utils.actors.OrderedExecutor.doTask(OrderedExecutor.java:42)
	at org.apache.activemq.artemis.utils.actors.OrderedExecutor.doTask(OrderedExecutor.java:31)
	at org.apache.activemq.artemis.utils.actors.ProcessorBase.executePendingTasks(ProcessorBase.java:66)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.activemq.artemis.utils.ActiveMQThreadFactory$1.run(ActiveMQThreadFactory.java:118)
```

The SLF4J javadocs say:

    /**
     * Return a copy of the current thread's context map, with keys and 
     * values of type String. Returned value may be null.
     * 
     * @return A copy of the current thread's context map. May be null.
     * @since 1.5.1
     */
    public Map<String, String> getCopyOfContextMap();

But you [don't check for null](https://github.com/corda/corda/blob/release/os/4.4/node-api/src/main/kotlin/net/corda/nodeapi/internal/bridging/AMQPBridgeManager.kt#L85-L96) and thus a NullPointerException occurs.

**Comment by mikehearn** [comment]
Thanks for the bug report!

**Comment by opticyclic** [comment]
Code has been merged
