### ISSUE TITLE
Official Corda Docker Image doesn't work for setting up a node in testnet

### ISSUE THREAD

**Issue by ivica7** [corda/corda#5636]
As described in documentation, I am using corda/corda-corretto-4.1:latest to setup a node on the test network.

```
docker run -ti \
        -e MY_PUBLIC_ADDRESS="......." \
        -e ONE_TIME_DOWNLOAD_KEY="............." \
        -e LOCALITY="Frankfurt" -e COUNTRY="DE" \
        -v /appdata/container/dcp/runtime/dev/cone/config:/etc/corda \
        -v /appdata/container/dcp/runtime/dev/cone/certificates:/opt/corda/certificates \
        corda/corda-corretto-4.1:latest config-generator --testnet
```

```
Archive:  /opt/corda/certificates/certs.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /opt/corda/certificates/certs.zip or
        /opt/corda/certificates/certs.zip.zip, and cannot find /opt/corda/certificates/certs.zip.ZIP, period.
Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'keyStorePassword'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
	at com.typesafe.config.impl.SimpleConfig.getValue(SimpleConfig.java:207)
	at com.typesafe.config.impl.SimpleConfig.getValue(SimpleConfig.java:41)
	at net.corda.core.ConfigExporter.combineTestNetWithOurConfig(ConfigExporter.kt:21)
	at net.corda.core.ConfigExporterMain.main(ConfigExporter.kt:73)
```

The downloaded certs.zip is actually the following json response:
```
{"timestamp":"2019-10-23T05:00:17.024+0000","status":404,"error":"Not Found","message":"No message available","path":"/api/user/node/generate/one-time-key/redeem/89d2254c-....."}
```

How to proceed on this? Can it be that the published docker image doesn't match with the most recent URLs for the testnet? Should I build Docker image from Dockerfile in the corda main project?

**Comment by roastario** [comment]
@farm hi Istvan, have the testnet endpoints been changed recently? This looks like it's getting back a funny response.

**Comment by altinukshini** [comment]
Has anyone found the problem yet? Do these one-time keys expire after a while?
