### ISSUE TITLE
Error while starting a node in DemoBench

### ISSUE THREAD

**Issue by alaa-m** [corda/corda#5705]
Hello,

I started an new clean Windows Sandbox on Windows 10 x64 and installed JDK 8u231. after that, I installed Corda Demo Bench 4.1 from your website.

When I start Corda Demo Bench 4.1, I leave everything as default and press Start Node but nothing happens.

This is my log:

2019-11-13T14:31:47,155Z [INFO ] JVMConfig - Java executable: C:\Program Files\Corda DemoBench\runtime\bin\java
2019-11-13T14:31:47,331Z [INFO ] ExplorerController - Explorer JAR: C:\Program Files\Corda DemoBench\app\explorer\node-explorer.jar
2019-11-13T14:31:47,333Z [INFO ] WebServerController - Web Server JAR: C:\Program Files\Corda DemoBench\app\corda\corda-webserver.jar
2019-11-13T14:31:47,391Z [INFO ] NodeController - Base directory: C:\Users\WDAGUtilityAccount\demobench\20191113163145
2019-11-13T14:31:47,391Z [INFO ] NodeController - Corda JAR: C:\Program Files\Corda DemoBench\app\corda\corda.jar
2019-11-13T14:31:53,530Z [INFO ] NodeInfoFilesCopier - Now watching: C:\Users\WDAGUtilityAccount\demobench\20191113163145\notary
2019-11-13T14:31:53,901Z [INFO ] CordappController - Installed cordapp: C:\Program Files\Corda DemoBench\app\cordapps\corda-finance-contracts.jar
2019-11-13T14:31:53,910Z [INFO ] CordappController - Installed cordapp: C:\Program Files\Corda DemoBench\app\cordapps\corda-finance-workflows.jar
2019-11-13T14:31:55,848Z [ERROR] NodeController - Failed to launch Corda: Couldn't create PTY
java.io.IOException: Couldn't create PTY
	at com.pty4j.windows.WinPtyProcess.<init>(WinPtyProcess.java:42) ~[pty4j-0.7.2.jar:?]
	at com.pty4j.PtyProcess.exec(PtyProcess.java:81) ~[pty4j-0.7.2.jar:?]
	at com.pty4j.PtyProcess.exec(PtyProcess.java:51) ~[pty4j-0.7.2.jar:?]
	at net.corda.demobench.pty.R3Pty.createTtyConnector(R3Pty.kt:33) ~[demobench-4.1.jar:?]
	at net.corda.demobench.pty.R3Pty.run(R3Pty.kt:55) ~[demobench-4.1.jar:?]
	at net.corda.demobench.model.NodeController.runCorda(NodeController.kt:129) [demobench-4.1.jar:?]
	at net.corda.demobench.views.NodeTerminalView$open$2.run(NodeTerminalView.kt:93) [demobench-4.1.jar:?]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [?:1.8.0_181]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [?:1.8.0_181]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_181]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_181]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_181]
	at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_181]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) [?:1.8.0_181]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [?:1.8.0_181]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_181]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_181]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_181]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_181]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_181]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_181]
Caused by: com.pty4j.PtyException: Error running process: CreateProcess failed. Code 2
	at com.pty4j.windows.WinPty.<init>(WinPty.java:90) ~[pty4j-0.7.2.jar:?]
	at com.pty4j.windows.WinPtyProcess.<init>(WinPtyProcess.java:40) ~[pty4j-0.7.2.jar:?]
	... 20 more
2019-11-13T14:31:58,920Z [INFO ] DemoBenchView - Exiting
2019-11-13T14:31:58,921Z [INFO ] DBViewer - Shutting down
2019-11-13T14:31:58,924Z [INFO ] R3Pty - Closing terminal 'O=Notary, L=Rome, C=IT'

Do you have any idea why this error happens?

Thank you.

**Comment by davidrapacchiale** [comment]
@alaa-m This sounds like a permission issue with your windows sandbox.

**Comment by pvrbharg** [comment]
@davidrapacchiale - I am new to CORDA and I am trying to run the DemoBench - latest edition on latest version of Windows 10 laptop OS. I see the same above error. I understand your response as posted here - however newbies like me need guidance on how to resolve this issue - even though this may not be related to CORDA DemoBench per say.  

My question - how do I get beyond this problem and this should be part of DemoBench documentation i troubleshooting section - I would submit. 

We want new or seasoned professionals to succeed in their attempts - so we can help wider knowledge base and CORDA adoption base. 

Would you agree and point me to how I can resolve this issue - in the context of installing and running DemoBench?

THANK  YOU in advance and HAPPY NEW YEAR 2020!

**Comment by jschmiede** [comment]
> @alaa-m This sounds like a permission issue with your windows sandbox.

Hi I'm having the same problem, with the distribution from corda site & from code, why is the issue closed without explanation?

**Comment by pvrbharg** [comment]
@alaa-m @jschmiede @davidrapacchiale  I am able to get past by doing a git clone of sources and compiling the binary for the platform and getting the DemoBench work for me on all supported platforms - Windows 10, Ubuntu Linux and Mac. I did not want to get into debugging the pre-built binary as to why it would not work - instead I choose to get the master branch source code, build it on platform myself, run tests and bring up the DemoBench. Works perfectly.

As I said - I am a new-bie to Corda and am learning it as yet. But this one issue can be side stepped - if this helps you as it did to me.

Sincerely yours - @pvrbharg 

![image](https://user-images.githubusercontent.com/5838902/72765798-02befb00-3ba3-11ea-8f67-c8c5ca5ec42c.png)

**Comment by sorokinvld** [comment]
solution is:

Step 1: launch the terminal (cmd) on windows.
Step 2: go to the C:\Program Files\Corda DemoBench\apps directory.
Step 3: type this: java -jar demobench-4.1.jar

works for me
