### ISSUE TITLE
Cannot connect to oracle database

### ISSUE THREAD

**Issue by FredericHeem** [corda/corda#5728]
Given the following configuration in *deployNode* to connect to oracle 12c:

```
extraConfig = [
                "dataSourceProperties.dataSourceClassName"  : "oracle.jdbc.pool.OracleDataSource",
                "dataSourceProperties.dataSource.url"       : "jdbc:oracle:thin:lc/password@localhost:1521:orcl",
                "dataSourceProperties.dataSource.user"      : "lc",
                "dataSourceProperties.dataSource.password"  : "password",
                "database.transactionIsolationLevel"        : "READ_COMMITTED",
                "jarDirs": ["/Users/myhome/myproject/workflows-kotlin/OJDBC8"]
                
        ]
```
> Make sure the Orable database drivers are in *jarDirs*.

Here is the exception thrown when running the node with the *runnodes* script:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at oracle.jdbc.driver.T4CPreparedStatement.configureRowData(T4CPreparedStatement.java:443)
        at oracle.jdbc.driver.OracleStatement.<init>(OracleStatement.java:735)
        at oracle.jdbc.driver.OraclePreparedStatement.<init>(OraclePreparedStatement.java:1363)
        at oracle.jdbc.driver.T4CPreparedStatement.<init>(T4CPreparedStatement.java:43)
        at oracle.jdbc.driver.T4CDriverExtension.allocatePreparedStatement(T4CDriverExtension.java:75)
        at oracle.jdbc.driver.PhysicalConnection.prepareStatementInternal(PhysicalConnection.java:1648)
        at oracle.jdbc.driver.PhysicalConnection.prepareStatement(PhysicalConnection.java:1606)
        at oracle.jdbc.driver.PhysicalConnection.prepareStatement(PhysicalConnection.java:1533)
        at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:315)
        at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
        at net.corda.node.services.persistence.DBCheckpointStorage.getCheckpointCount(DBCheckpointStorage.kt:86)
        at net.corda.node.internal.AbstractNodeKt.startHikariPool(AbstractNode.kt:1160)
        at net.corda.node.internal.AbstractNode.startDatabase(AbstractNode.kt:822)
        at net.corda.node.internal.Node.startDatabase(Node.kt:432)
        at net.corda.node.internal.AbstractNode.generateAndSaveNodeInfo(AbstractNode.kt:305)
        at net.corda.node.internal.Node.generateAndSaveNodeInfo(Node.kt:441)
        at net.corda.node.internal.subcommands.GenerateNodeInfoCli$runProgram$1.run(GenerateNodeInfoCli.kt:12)
        at net.corda.node.internal.NodeStartup$initialiseAndRun$5.invoke(NodeStartup.kt:187)
        at net.corda.node.internal.NodeStartup$initialiseAndRun$5.invoke(NodeStartup.kt:138)
        at net.corda.node.internal.NodeStartupLogging$DefaultImpls.attempt(NodeStartup.kt:529)
        at net.corda.node.internal.NodeStartup.attempt(NodeStartup.kt:138)
        at net.corda.node.internal.NodeStartup.initialiseAndRun(NodeStartup.kt:186)
        at net.corda.node.internal.NodeStartup.initialiseAndRun$default(NodeStartup.kt:147)
        at net.corda.node.internal.subcommands.GenerateNodeInfoCli.runProgram(GenerateNodeInfoCli.kt:10)
        at net.corda.cliutils.CliWrapperBase.call(CordaCliWrapper.kt:143)
        at net.corda.cliutils.CliWrapperBase.call(CordaCliWrapper.kt:106)
        at picocli.CommandLine.execute(CommandLine.java:1173)
        at picocli.CommandLine.access$800(CommandLine.java:141)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1367)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1335)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
        at net.corda.cliutils.CordaCliWrapperKt.start(CordaCliWrapper.kt:73)
        at net.corda.node.Corda.main(Corda.kt:13)
Caused by: java.lang.NullPointerException
        at oracle.jdbc.driver.DynamicByteArray$1.run(DynamicByteArray.java:718)
        at java.security.AccessController.doPrivileged(Native Method)
        at oracle.jdbc.driver.DynamicByteArray.<clinit>(DynamicByteArray.java:713)
```

Note that connecting to oracle works fine when running the tests. 
It seems that the ojdbc8 driver doesn't like to be the "loaded" by Corda.
The project has been updated to the latest 4.3 and is running on a Mac.

**Comment by davidrapacchiale** [comment]
Thanks @FredericHeem 
We have opened a new ticket in Corda OS jira project (https://r3-cev.atlassian.net/browse/CORDA-3466) where you can track its progress.

**Comment by szymonsztuka** [comment]
The Oracle Driver is loaded by the node because your stractrecte id thron from Oracle JDBC classes (`Exception in thread "main" java.lang.ExceptionInInitializerError at oracle.jdbc.driver.T4CPreparedStatement.configureRowData(T4CPreparedStatement.java:443)`).
Is this issue with JDBC diver version ? See https://stackoverflow.com/questions/33381256/has-anyone-seen-this-npe-in-oracle-jdbc-driver

**Comment by FredericHeem** [comment]
It has been tried with ojdbc8-19.3.0.0.jar and ojdbc8-12.2.0.1.jar, both fails with the same exception.

Here are the steps to install and run oracle 12c:
```
$ docker pull  absolutapps/oracle-12c-ee
$ docker run -d --name oracle  --privileged -v $(pwd)/oradata:/u01/app/oracle -p 8080:8080 -p 1521:1521 absolutapps/oracle-12c-ee
```
Wait until the db is ready:
```
    $ docker logs oracle -f
```
Run a bash command inside the containter
```
$ docker exec -it oracle /bin/bash
```
Now connect the the sql console to create a user
```
 $ sqlplus system/oracle@//localhost:1521/orcl
```
Create the user lc: 
```
CREATE USER lc IDENTIFIED BY password;
GRANT CONNECT, RESOURCE, DBA TO lc;
GRANT ALL PRIVILEGES TO lc;
```

Try to login as the newly created user:
```
$ sqlplus lc/password@//localhost:1521/orcl
```
Now it is time to connect from Corda.
Download the oracle driver [ojdbc8-19.3.0.0.jar](https://repo1.maven.org/maven2/com/oracle/ojdbc/ojdbc8/19.3.0.0/ojdbc8-19.3.0.0.jar) and move it to the *lib* directory

Edit the *deployTask*  in *build.gradle* and add the oracle config for one of the nodes, make sure *jarDirs* is correct
```
extraConfig = [
                "dataSourceProperties.dataSourceClassName"  : "oracle.jdbc.pool.OracleDataSource",
                "dataSourceProperties.dataSource.url"       : "jdbc:oracle:thin:lc/password@localhost:1521:orcl",
                "dataSourceProperties.dataSource.user"      : "lc",
                "dataSourceProperties.dataSource.password"  : "password",
                "database.transactionIsolationLevel"        : "READ_COMMITTED",
                "jarDirs": ["/Users/you/<yourproject>/lib"]

        ]
```

Also add `compile 'com.oracle.ojdbc:ojdbc8:19.3.0.0'` in the dependencies section of *build.gradle*

Now try to deploy the node:
```
$ ./gradlew deployNode
```
