### ISSUE TITLE
Cordite app breaks Corda node

### ISSUE THREAD

**Issue by easeev** [corda/corda#5790]
Steps to reproduce:
1. Configure Corda 4.3 OS node
2. Save https://repo1.maven.org/maven2/io/cordite/cordite-cordapp/0.4.9/cordite-cordapp-0.4.9.jar to the cordapps directory
3. Start Corda node
4. The main thread crashes with the exception while the node process continues running

```
[WARN] 11:35:08+0000 [main] utilities.AppendOnlyPersistentMapBase.set - Double insert in net.corda.node.utilities.AppendOnlyPersistentMap for entity class class net.corda.node.internal.DBNetworkParametersStorage$PersistentNetworkParameters key 5D2671F9C96AD3DBFFDC3973FA62B5435E5D98BE21E7AE32446AE09FBB0D2A41, not inserting the second time
Exception in thread "main" java.lang.NoClassDefFoundError: io/cordite/commons/utils/jackson/CorditeJacksonInit
        at io.cordite.braid.BraidServerCordaService.<clinit>(BraidServerCordaService.kt:52)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at net.corda.node.internal.AbstractNode.installCordaService(AbstractNode.kt:662)
        at net.corda.node.internal.AbstractNode.installCordaServices(AbstractNode.kt:589)
        at net.corda.node.internal.AbstractNode.access$installCordaServices(AbstractNode.kt:120)
        at net.corda.node.internal.AbstractNode$start$8.invoke(AbstractNode.kt:382)
        at net.corda.node.internal.AbstractNode$start$8.invoke(AbstractNode.kt:120)
        at net.corda.nodeapi.internal.persistence.CordaPersistence.inTopLevelTransaction(CordaPersistence.kt:250)
        at net.corda.nodeapi.internal.persistence.CordaPersistence.transaction(CordaPersistence.kt:226)
        at net.corda.nodeapi.internal.persistence.CordaPersistence.transaction(CordaPersistence.kt:236)
        at net.corda.node.internal.AbstractNode.start(AbstractNode.kt:371)
        at net.corda.node.internal.Node.start(Node.kt:425)
        at net.corda.node.internal.NodeStartup.startNode(NodeStartup.kt:209)
        at net.corda.node.internal.NodeStartupCli$runProgram$2.run(NodeStartup.kt:130)
        at net.corda.node.internal.NodeStartup$initialiseAndRun$5.invoke(NodeStartup.kt:186)
        at net.corda.node.internal.NodeStartup$initialiseAndRun$5.invoke(NodeStartup.kt:137)
        at net.corda.node.internal.NodeStartupLogging$DefaultImpls.attempt(NodeStartup.kt:509)
        at net.corda.node.internal.NodeStartup.attempt(NodeStartup.kt:137)
        at net.corda.node.internal.NodeStartup.initialiseAndRun(NodeStartup.kt:185)
        at net.corda.node.internal.NodeStartupCli.runProgram(NodeStartup.kt:128)
        at net.corda.cliutils.CordaCliWrapper.call(CordaCliWrapper.kt:190)
        at net.corda.node.internal.NodeStartupCli.call(NodeStartup.kt:83)
        at net.corda.node.internal.NodeStartupCli.call(NodeStartup.kt:64)
        at picocli.CommandLine.execute(CommandLine.java:1056)
        at picocli.CommandLine.access$900(CommandLine.java:142)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1246)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1214)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1122)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:1405)
        at net.corda.cliutils.CordaCliWrapperKt.start(CordaCliWrapper.kt:73)
        at net.corda.node.Corda.main(Corda.kt:13)
Caused by: java.lang.ClassNotFoundException: io.cordite.commons.utils.jackson.CorditeJacksonInit
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 34 more
[ERROR] 11:35:08+0000 [main] internal.DbExceptionHandler.uncaughtException - Exception in thread "main" [errorCode=188a0l0, moreInformationAt=https://errors.corda.net/OS/4.1/188a0l0]
```

IMO Corda node software should be able to prevent an arbitrary CorDapp to crash the entire node.

**Comment by davidrapacchiale** [comment]
Thanks @easeev .
We intend on Corda being fully sandboxed in due course. In the meanwhile, we will raise this issue with the Cordite team.

**Comment by nimmaj** [comment]
Hi @easeev.  

Thanks for this.  We haven't quite got around to upgrading cordite to work with corda 4.3.  It currently runs against 4.1.  

We have this issue to track it: https://gitlab.com/cordite/cordite/issues/705 .  We'll get around to it sometime (time permitting) but if you fancy submitting a merge request that would be really awesome :-)
