### ISSUE TITLE
[Corda 4.3] IllegalArgumentException: Certificate path must at least include subject and issuing certificates

### ISSUE THREAD

**Issue by ghost** [corda/corda#5888]
I've migrated from Corda 4.2 to 4.3 version and started facing an exception bellow:

```
java.lang.IllegalArgumentException: Certificate path must at least include subject and issuing certificates
	at net.corda.core.identity.PartyAndCertificate.<init>(PartyAndCertificate.kt:25) ~[corda-core-4.3.jar:?]
	at net.corda.node.internal.AbstractNode.getPartyAndCertificatePlusAliasKeyPair(AbstractNode.kt:1153) ~[corda-node-4.3.jar:?]
	at net.corda.node.internal.AbstractNode.obtainIdentity(AbstractNode.kt:1106) ~[corda-node-4.3.jar:?]
	at net.corda.node.internal.AbstractNode.start(AbstractNode.kt:446) ~[corda-node-4.3.jar:?]
	at net.corda.node.internal.Node.start(Node.kt:552) ~[corda-node-4.3.jar:?]
	at net.corda.node.internal.EnterpriseNode.start(EnterpriseNode.kt:210) ~[corda-node-4.3.jar:?]
	at net.corda.node.internal.NodeStartup.startNode(NodeStartup.kt:211) ~[corda-node-4.3.jar:?]
	at net.corda.node.internal.NodeStartupCli$runProgram$2.run(NodeStartup.kt:132) ~[corda-node-4.3.jar:?]
	at net.corda.node.internal.NodeStartup$initialiseAndRun$5.invoke(NodeStartup.kt:188) ~[corda-node-4.3.jar:?]
	at net.corda.node.internal.NodeStartup$initialiseAndRun$5.invoke(NodeStartup.kt:139) ~[corda-node-4.3.jar:?]
	at net.corda.node.internal.NodeStartupLogging$DefaultImpls.attempt(NodeStartup.kt:538) ~[corda-node-4.3.jar:?]
	at net.corda.node.internal.NodeStartup.attempt(NodeStartup.kt:139) ~[corda-node-4.3.jar:?]
	at net.corda.node.internal.NodeStartup.initialiseAndRun(NodeStartup.kt:187) ~[corda-node-4.3.jar:?]
	at net.corda.node.internal.NodeStartupCli.runProgram(NodeStartup.kt:130) ~[corda-node-4.3.jar:?]
	at net.corda.cliutils.CordaCliWrapper.call(CordaCliWrapper.kt:190) ~[corda-tools-cliutils-4.3.jar:?]
	at net.corda.node.internal.NodeStartupCli.call(NodeStartup.kt:85) ~[corda-node-4.3.jar:?]
	at net.corda.node.internal.NodeStartupCli.call(NodeStartup.kt:66) ~[corda-node-4.3.jar:?]
	at picocli.CommandLine.execute(CommandLine.java:1173) ~[picocli-3.9.6.jar:3.9.6]
	at picocli.CommandLine.access$800(CommandLine.java:141) ~[picocli-3.9.6.jar:3.9.6]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1367) ~[picocli-3.9.6.jar:3.9.6]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1335) ~[picocli-3.9.6.jar:3.9.6]
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243) ~[picocli-3.9.6.jar:3.9.6]
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526) ~[picocli-3.9.6.jar:3.9.6]
	at net.corda.cliutils.CordaCliWrapperKt.start(CordaCliWrapper.kt:73) ~[corda-tools-cliutils-4.3.jar:?]
	at net.corda.node.Corda.main(Corda.kt:13) ~[corda-node-4.3.jar:?]
```
It's happening when we are starting the Corda env as a cold start without any older data.
The, previous version 4.2 doesn't have this exception.

Also, I faced this one message above of Corda log:

```
"logger":"net.corda.node.internal.Node","message":"identity-private-key not found in key store, generating fresh key!"
```

Node configuration of Corda `node.conf`:

```
p2pAddress: ${P2PADDRESS}
emailAddress: "support@domain.com"
myLegalName: "OU=service-name, O=DomainX, L=London, C=IE"
devMode: true
devModeOptions: {
  allowCompatibilityZone: true
}
rpcSettings: {
    address: "0.0.0.0:10003"
    adminAddress: "0.0.0.0:10004"
}
rpcUsers: [
    {
        user: ${CORDA_RPC_USERNAME}
        password: ${CORDA_RPC_PASSWORD}
        permissions: [
            ALL
        ]
    }
]
dataSourceProperties : {
  dataSourceClassName : org.postgresql.ds.PGSimpleDataSource
  dataSource.url : "jdbc:postgresql://"${PG_HOST}":"${PG_PORT}/${PG_DATABASE}
  dataSource.user : ${PG_USERNAME}
  dataSource.password : ${PG_PASSWORD}
}
database : {
  transactionIsolationLevel : READ_COMMITTED
  runMigration : true
  initialiseSchema : true
  initialiseAppSchema : UPDATE
}
sshd:  {
  port : 2222
}
detectPublicIp: false
networkServices: {
  doormanURL: "http://corditenms.nms.svc.cluster.local"
  networkMapURL: "http://corditenms.nms.svc.cluster.local"
}
```

For issuing certificates we are using NMS (https://gitlab.com/cordite/network-map-service).

And into release notes was something about that: https://docs.corda.net/release-notes.html
But without any instructions what should we do for supporting this changes on Corda 4.3.

May as a possible reason:

```
net.corda.nodeapi.internal.cryptoservice.TimedCryptoServiceException: Timed-out while waiting for 1000
```

So, the question what was changed in Corda 4.3 and what should I do for successfully migrating to this version 4.3?

**Comment by peterli-r3** [comment]
Hi 

With Corda 5 coming soon, we are closing up the issues prior to Corda v4.5. Thank you for your contribution to Corda!

Please feel free to contact devrel@r3.com if you need any further information
