### ISSUE TITLE
Corda Demobench not starting nodes

### ISSUE THREAD

**Issue by Ashishishere1** [corda/corda#5920]
I have installed Corda Demobench 4.1 exe and ran as admin
source: https://www.corda.net/demobench/
As per the videos, once i launch the application, it should start a node rightaway however the node in my case is not starting.
Following is the log of error i am getting.

_2020-02-02T13:27:27,539Z [INFO ] JVMConfig - Java executable: C:\Program Files\Corda DemoBench\runtime\bin\java
2020-02-02T13:27:27,741Z [INFO ] ExplorerController - Explorer JAR: C:\Program Files\Corda DemoBench\app\explorer\node-explorer.jar
2020-02-02T13:27:27,743Z [INFO ] WebServerController - Web Server JAR: C:\Program Files\Corda DemoBench\app\corda\corda-webserver.jar
2020-02-02T13:27:27,804Z [INFO ] NodeController - Base directory: C:\Users\Ideapad-Pc\demobench\20200202172726
2020-02-02T13:27:27,804Z [INFO ] NodeController - Corda JAR: C:\Program Files\Corda DemoBench\app\corda\corda.jar
2020-02-02T13:27:32,673Z [INFO ] NodeInfoFilesCopier - Now watching: C:\Users\Ideapad-Pc\demobench\20200202172726\notary
2020-02-02T13:27:33,027Z [INFO ] CordappController - Installed cordapp: C:\Program Files\Corda DemoBench\app\cordapps\corda-finance-contracts.jar
2020-02-02T13:27:33,030Z [INFO ] CordappController - Installed cordapp: C:\Program Files\Corda DemoBench\app\cordapps\corda-finance-workflows.jar
2020-02-02T13:27:34,599Z [ERROR] NodeController - Failed to launch Corda: Couldn't create PTY
java.io.IOException: Couldn't create PTY
	at com.pty4j.windows.WinPtyProcess.<init>(WinPtyProcess.java:42) ~[pty4j-0.7.2.jar:?]
	at com.pty4j.PtyProcess.exec(PtyProcess.java:81) ~[pty4j-0.7.2.jar:?]
	at com.pty4j.PtyProcess.exec(PtyProcess.java:51) ~[pty4j-0.7.2.jar:?]
	at net.corda.demobench.pty.R3Pty.createTtyConnector(R3Pty.kt:33) ~[demobench-4.1.jar:?]
	at net.corda.demobench.pty.R3Pty.run(R3Pty.kt:55) ~[demobench-4.1.jar:?]
	at net.corda.demobench.model.NodeController.runCorda(NodeController.kt:129) [demobench-4.1.jar:?]
	at net.corda.demobench.views.NodeTerminalView$open$2.run(NodeTerminalView.kt:93) [demobench-4.1.jar:?]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [?:1.8.0_181]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [?:1.8.0_181]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_181]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_181]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_181]
	at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_181]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) [?:1.8.0_181]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [?:1.8.0_181]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_181]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_181]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_181]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_181]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_181]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_181]
Caused by: com.pty4j.PtyException: Error running process: CreateProcess failed. Code 2
	at com.pty4j.windows.WinPty.<init>(WinPty.java:90) ~[pty4j-0.7.2.jar:?]
	at com.pty4j.windows.WinPtyProcess.<init>(WinPtyProcess.java:40) ~[pty4j-0.7.2.jar:?]
	... 20 more_

I guess it is related to the error of PTY not loading however I am not able to debug the same and I couldnt find help online. 

TIA for your suggestion.

**Comment by davidrapacchiale** [comment]
Hi @Ashishishere1 This is a know issue which we are tracking it as https://r3-cev.atlassian.net/browse/CORDA-3102
