### ISSUE TITLE
Unable to connect standalone shell over SSL

### ISSUE THREAD

**Issue by adelrustum** [corda/corda#5955]
Corda: 4.3 OpenSource
OS: Ubuntu
Standalone Shell: 4.3
Oracle JDK: 1.8.0_241

I enabled SSL for RPC inside my `node.conf`:
```
rpcSettings {
    useSsl=true
    ssl {
       keyStorePath=/opt/corda/certificates/rpcsslkeystore.jks
       keyStorePassword="XXX"
    }
    address = "0.0.0.0:10003"
    adminAddress = "0.0.0.0:10004"
}

```

I created a `config-file.conf` for my standalone shell:
```
node {
    addresses {
        rpc {
            host : "127.0.0.1"
            port : 10003
        }
    }
}
extensions {
    cordapps {
        path : /opt/corda/cordapps
    }
    sshd {
        enabled : "false"
        port : 2223
    }
}
ssl {
    truststore {
        path: "/opt/corda/certificates/export/rpcssltruststore.jks"
        type: "JKS"
        password: "XXX"
    }
}

```

Now when I try to connect:
```
ubuntu@xxx:/opt/corda/shell-cli$ sudo java -jar corda-tools-shell-cli-4.3-all.jar --config-file=config-file.conf 
// I get prompted for the below
User:
Password:
```

I receive this error:
```
[ERROR] 2020-02-12T21:03:32,130Z [Thread-4 (ActiveMQ-client-netty-threads)] core.client.initChannel - AMQ214021: Invalid cipher suite specified. Supported cipher suites are: TLS_RSA_WITH_AES_256_CBC_SHA256, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256, TLS_EMPTY_RENEGOTIATION_INFO_SCSV
[WARN ] 2020-02-12T21:03:32,139Z [Thread-4 (ActiveMQ-client-netty-threads)] channel.ChannelInitializer.warn - Failed to initialize a channel. Closing: [id: 0x8855a103] [errorCode=3do8bp, moreInformationAt=https://errors.corda.net/OS/4.3/3do8bp]
java.lang.IllegalArgumentException: Cannot support TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 with currently installed providers
	at sun.security.ssl.CipherSuiteList.<init>(CipherSuiteList.java:81) ~[?:1.8.0_241]
	at sun.security.ssl.SSLEngineImpl.setEnabledCipherSuites(SSLEngineImpl.java:2027) ~[?:1.8.0_241]
	at org.apache.activemq.artemis.core.remoting.impl.netty.NettyConnector$1.initChannel(NettyConnector.java:543) ~[corda-tools-shell-cli-4.3-all.jar:?]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113) [corda-tools-shell-cli-4.3-all.jar:?]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105) [corda-tools-shell-cli-4.3-all.jar:?]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:617) [corda-tools-shell-cli-4.3-all.jar:?]
	at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:46) [corda-tools-shell-cli-4.3-all.jar:?]
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1467) [corda-tools-shell-cli-4.3-all.jar:?]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1141) [corda-tools-shell-cli-4.3-all.jar:?]
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:666) [corda-tools-shell-cli-4.3-all.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:510) [corda-tools-shell-cli-4.3-all.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423) [corda-tools-shell-cli-4.3-all.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482) [corda-tools-shell-cli-4.3-all.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [corda-tools-shell-cli-4.3-all.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [corda-tools-shell-cli-4.3-all.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [corda-tools-shell-cli-4.3-all.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [corda-tools-shell-cli-4.3-all.jar:?]
	at org.apache.activemq.artemis.utils.ActiveMQThreadFactory$1.run(ActiveMQThreadFactory.java:118) [corda-tools-shell-cli-4.3-all.jar:?]
[ERROR] 2020-02-12T21:03:32,141Z [main] core.client.createConnection - AMQ214016: Failed to create netty connection [errorCode=rxgrdu, moreInformationAt=https://errors.corda.net/OS/4.3/rxgrdu]
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.ensureOpen(...)(Unknown Source) ~[corda-tools-shell-cli-4.3-all.jar:?]
[INFO ] 2020-02-12T21:03:32,156Z [main] internal.RPCClient.logElapsedTime - Failed Startup took 28 msec
[INFO ] 2020-02-12T21:03:33,392Z [main] internal.ReconnectingCordaRPCOps.establishConnectionWithRetry - Connecting to: 127.0.0.1:10003
[ERROR] 2020-02-12T21:03:33,396Z [Thread-6 (ActiveMQ-client-netty-threads)] core.client.initChannel - AMQ214021: Invalid cipher suite specified. Supported cipher suites are: TLS_RSA_WITH_AES_256_CBC_SHA256, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256, TLS_EMPTY_RENEGOTIATION_INFO_SCSV
[WARN ] 2020-02-12T21:03:33,405Z [Thread-6 (ActiveMQ-client-netty-threads)] channel.ChannelInitializer.warn - Failed to initialize a channel. Closing: [id: 0x15d9bc53] [errorCode=3do8bp, moreInformationAt=https://errors.corda.net/OS/4.3/3do8bp]
java.lang.IllegalArgumentException: Cannot support TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 with currently installed providers
	at sun.security.ssl.CipherSuiteList.<init>(CipherSuiteList.java:81) ~[?:1.8.0_241]
	at sun.security.ssl.SSLEngineImpl.setEnabledCipherSuites(SSLEngineImpl.java:2027) ~[?:1.8.0_241]
	at org.apache.activemq.artemis.core.remoting.impl.netty.NettyConnector$1.initChannel(NettyConnector.java:543) ~[corda-tools-shell-cli-4.3-all.jar:?]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113) [corda-tools-shell-cli-4.3-all.jar:?]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105) [corda-tools-shell-cli-4.3-all.jar:?]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:617) [corda-tools-shell-cli-4.3-all.jar:?]
	at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:46) [corda-tools-shell-cli-4.3-all.jar:?]
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1467) [corda-tools-shell-cli-4.3-all.jar:?]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1141) [corda-tools-shell-cli-4.3-all.jar:?]
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:666) [corda-tools-shell-cli-4.3-all.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:510) [corda-tools-shell-cli-4.3-all.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423) [corda-tools-shell-cli-4.3-all.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482) [corda-tools-shell-cli-4.3-all.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [corda-tools-shell-cli-4.3-all.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [corda-tools-shell-cli-4.3-all.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [corda-tools-shell-cli-4.3-all.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [corda-tools-shell-cli-4.3-all.jar:?]
	at org.apache.activemq.artemis.utils.ActiveMQThreadFactory$1.run(ActiveMQThreadFactory.java:118) [corda-tools-shell-cli-4.3-all.jar:?]
[ERROR] 2020-02-12T21:03:33,408Z [main] core.client.createConnection - AMQ214016: Failed to create netty connection [errorCode=rxgrdu, moreInformationAt=https://errors.corda.net/OS/4.3/rxgrdu]
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.ensureOpen(...)(Unknown Source) ~[corda-tools-shell-cli-4.3-all.jar:?]
[INFO ] 2020-02-12T21:03:33,412Z [main] internal.RPCClient.logElapsedTime - Failed Startup took 17 msec
```
I tried the steps mentioned here (i.e. adding JCE to /lib/security), but it didn't work:
https://support.datastax.com/hc/en-us/articles/204226129-Receiving-error-Caused-by-java-lang-IllegalArgumentException-Cannot-support-TLS-RSA-WITH-AES-256-CBC-SHA-with-currently-installed-providers-on-DSE-startup-after-setting-up-client-to-node-encryption
**Update:** Actually those files (from the above link) already exist inside `/usr/lib/jvm/jdk1.8.0_241/jre/lib/security/policy/limited`. 
I also have my `JAVA_HOME` and `JRE_HOME` setup inside `/etc/environment`.

On a side note, you have a couple of mistakes in the documentation of standalone shell: https://docs.corda.net/shell.html#starting-the-standalone-shell
If you look at the sample `config-file`:  
1. `ssl` section doesn't require a `keystore` section.  
2. `truststore` is misspelled, it's written `trustore`.

**Comment by peterli-r3** [comment]
Hi Adel

With Corda 5 coming soon, we are closing up the issues prior to Corda v4.5. Thank you for your contribution to Corda!

Please feel free to contact devrel@r3.com if you need any further information
