### ISSUE TITLE
Corda network boostrapper 4.3 api does not work from packaged spring boot app (jar)

### ISSUE THREAD

**Issue by karthik137** [corda/corda#5982]
I am using corda-network-bootstrapper 4.3 in my spring boot application. Here is the dependency:

```
		<dependency>
			<groupId>net.corda</groupId>
			<artifactId>corda-tools-network-bootstrapper</artifactId>
			<version>4.3</version>
		</dependency>
```

Here is my java code (spring boot)

```java
public class GenerateCordaNetwork {

    public static final Logger logger = LoggerFactory.getLogger(GenerateCordaNetwork.class);

    @Autowired
    private ResourceLoader resourceLoader;

    public void generateNetwork() throws IOException, URISyntaxException {
        NetworkBootstrapperRunner networkRunner = new NetworkBootstrapperRunner();

        //Working
        URI uri = new URI("file:///home/kirito/corda-composer/node/");
        Path path = Paths.get(uri);
        networkRunner.setDir(path);
        logger.info("Get directory : "+networkRunner.getDir().toString());
        networkRunner.runProgram();
    }
}

```
NOTE: /home/kirito/corda-composer/node/ directory has test_node.conf file. It has corda node configuration in json format.

The code works fine and generates node directory when launched from IntelliJ as a java application. 

Main method (spring boot)

```java
@SpringBootApplication
public class NetworkComposerApplication {

	public static void main(String[] args) {
		SpringApplication.run(NetworkComposerApplication.class, args);
	}

}

```

**The code throws following error when it is run as a jar file. Is there any solution for this?.**

**Need help !**

```
2020-02-18 15:07:35.690 ERROR 5237 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.nio.file.FileSystemNotFoundException] with root cause

java.nio.file.FileSystemNotFoundException: null
	at com.sun.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:171) ~[zipfs.jar:1.8.0_222]
	at com.sun.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:157) ~[zipfs.jar:1.8.0_222]
	at java.nio.file.Paths.get(Paths.java:143) ~[na:1.8.0_222]
	at net.corda.core.internal.InternalUtils.toPath(InternalUtils.kt:421) ~[corda-tools-network-bootstrapper-4.3.jar!/:na]
	at net.corda.core.internal.InternalUtils.toPath(InternalUtils.kt:423) ~[corda-tools-network-bootstrapper-4.3.jar!/:na]
	at net.corda.nodeapi.internal.network.NetworkBootstrapper.bootstrap(NetworkBootstrapper.kt:224) ~[corda-tools-network-bootstrapper-4.3.jar!/:na]
	at net.corda.bootstrapper.NetworkBootstrapperRunner.runProgram(Main.kt:92) ~[corda-tools-network-bootstrapper-4.3.jar!/:na]
```

**Comment by karthik137** [comment]
This is my spring boot version
```
 <parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.2.4.RELEASE</version>
</parent>
```

**Comment by peterli-r3** [comment]
Hi Karthik137

With Corda 5 coming soon, we are closing up the issues prior to Corda v4.5. Thank you for your contribution to Corda!

Please feel free to contact devrel@r3.com if you need any further information
