### ISSUE TITLE
A networked network-map cannot connect to itself as the node user to setup the webserver.

### ISSUE THREAD

**Issue by exFalso** [corda/corda#62]
```
Dec 14 14:01:47 cordaload-nameserver sh[60858]: Node listening on address               : cordaload-nameserver:31337
Dec 14 14:01:49 cordaload-nameserver sh[60858]: E 14:01:49 33 server.handleCreateSession - AMQ224018: Failed to create session
Dec 14 14:01:49 cordaload-nameserver sh[60858]:  org.apache.activemq.artemis.api.core.ActiveMQClusterSecurityException: AMQ119099: Unable to authenticate cluster user: ACTIVEMQ.CLUSTER.ADMIN.
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at org.apache.activemq.artemis.core.security.impl.SecurityStoreImpl.authenticate(SecurityStoreImpl.java:116) ~[artemis-server-1.4.0.jar
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl.createSession(ActiveMQServerImpl.java:1208) ~[artemis-server-1.4.0.j
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at org.apache.activemq.artemis.core.protocol.core.impl.ActiveMQPacketHandler.handleCreateSession(ActiveMQPacketHandler.java:154) [artem
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at org.apache.activemq.artemis.core.protocol.core.impl.ActiveMQPacketHandler.handlePacket(ActiveMQPacketHandler.java:80) [artemis-serve
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at org.apache.activemq.artemis.core.protocol.core.impl.ChannelImpl.handlePacket(ChannelImpl.java:633) [artemis-core-client-1.4.0.jar:1.
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at org.apache.activemq.artemis.core.protocol.core.impl.RemotingConnectionImpl.doBufferReceived(RemotingConnectionImpl.java:376) [artemi
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at org.apache.activemq.artemis.core.protocol.core.impl.RemotingConnectionImpl.bufferReceived(RemotingConnectionImpl.java:358) [artemis-
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at org.apache.activemq.artemis.core.remoting.server.impl.RemotingServiceImpl$DelegatingBufferHandler.bufferReceived(RemotingServiceImpl
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at org.apache.activemq.artemis.core.remoting.impl.netty.ActiveMQChannelHandler.channelRead(ActiveMQChannelHandler.java:68) [artemis-cor
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366) [netty-all-4.0.39.Final.jar
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352) [netty-all-4.0.39.Final.jar
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345) [netty-all-4.0.39.Final.jar:4
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [netty-all-4.0.39.Final.jar:4.0.39.Final]
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [netty-all-4.0.39.Final.jar:4.0.39.Final]
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366) [netty-all-4.0.39.Final.jar
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352) [netty-all-4.0.39.Final.jar
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345) [netty-all-4.0.39.Final.jar:4
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1066) [netty-all-4.0.39.Final.jar:4.0.39.Final]
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:900) [netty-all-4.0.39.Final.jar:4.0.39.Final]
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) [netty-all-4.0.39.Final.jar:4.0.39.Final]
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [netty-all-4.0.39.Final.jar:4.0.39.Final]
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366) [netty-all-4.0.39.Final.jar
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352) [netty-all-4.0.39.Final.jar
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345) [netty-all-4.0.39.Final.jar:4
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294) [netty-all-4.0.39.Final.jar:4.0.39
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366) [netty-all-4.0.39.Final.jar
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352) [netty-all-4.0.39.Final.jar
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911) [netty-all-4.0.39.Final.jar:4.0.39.Final]
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [netty-all-4.0.39.Final.jar:4.0.39.F
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:572) [netty-all-4.0.39.Final.jar:4.0.39.Final]
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:513) [netty-all-4.0.39.Final.jar:4.0.39.Final]
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:427) [netty-all-4.0.39.Final.jar:4.0.39.Final]
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:399) [netty-all-4.0.39.Final.jar:4.0.39.Final]
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140) [netty-all-4.0.39.Final.jar:4.0.39.Fina
Dec 14 14:01:49 cordaload-nameserver sh[60858]:         at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by mikehearn** [comment]
@shamsasari is changing things in this area. Re-assigning to him.

**Comment by shamsasari** [comment]
@exFalso with the web server split out, do you think this is still relevant? Can you remember the steps to reproduce this?

**Comment by exFalso** [comment]
@shamsasari IIRC it happened on plain node starts in a non-trivial non-local environment. I think we can optimistically close this for now, may have to reopen once we start loadtesting again
