### ISSUE TITLE
Starting flows via RPC is broken in the latest release

### ISSUE THREAD

**Issue by mikehearn** [corda/corda#650]
As part of the refactorings to split the code into internal and non-internal, we've broken the startFlow RPC! This isn't detected by our own tests or demos because the issue only shows up if you don't have node.jar on your classpath.

The issue is this:

```
com.esotericsoftware.kryo.KryoException: Unable to find class: net.corda.node.services.statemachine.FlowHandleImpl
Serialization trace:
value (net.corda.core.ErrorOr)
    at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:160)
    at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:133)
    at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:693)
    at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:118)
    at com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.read(CompatibleFieldSerializer.java:147)
    at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
    at net.corda.core.serialization.KryoKt$deserialize$1$1.execute(Kryo.kt:102)
    at com.esotericsoftware.kryo.pool.KryoPoolQueueImpl.run(KryoPoolQueueImpl.java:61)
    at net.corda.core.serialization.KryoKt.deserialize(Kryo.kt:102)
    at net.corda.core.serialization.KryoKt.deserialize(Kryo.kt:107)
    at net.corda.client.rpc.CordaRPCClientImpl.deserialize(CordaRPCClientImpl.kt:112)
```

`FlowHandleImpl` can't be deserialised because it's a private class inside `CordaRPCOpsImpl`, which makes sense: you can't send private classes across RPC. Both sides need to know about them.

`FlowHandleImpl` and `FlowProgressHandleImpl` need to be moved back into the core module, made non-private, and we need to craft an integration test that verifies all the important RPCs work when the node code is not on the classpath.

**Comment by shamsasari** [comment]
We'd no longer need `FlowHandle` and `FlowProgressHandle` as interfaces. They can be public data classes.
