### ISSUE TITLE
Serialisation failure if contract verification fails

### ISSUE THREAD

**Issue by shamsasari** [corda/corda#651]
If a flow does a contract verify and it fails, the session ends but things get stuck as the `TransactionVerificationException.ContractRejection` has reference to the `LedgerTransaction` which isn't (or rather shouldn't be) serialisable.

We get the following stack trace:
```
Tue May 09 15:13:38 CEST 2017>>> signature verified.
E 15:14:06 [Node thread] flow.[61ed2964-5554-4933-81a3-0d054ca19f1b].uncaughtException - Caught exception from flow
 com.esotericsoftware.kryo.KryoException: Class net.corda.node.services.persistence.NodeAttachmentService$AttachmentImpl is not annotated or on the whitelist, so cannot be used in serialization
Serialization trace:
attachments (net.corda.core.transactions.LedgerTransaction)
tx (net.corda.core.contracts.TransactionVerificationException$ContractRejection)
errorResponse (net.corda.node.services.statemachine.ErrorSessionEnd)
        at net.corda.core.serialization.CordaClassResolver.checkClass(CordaClassResolver.kt:60) ~[core-0.11.0.jar:?]
        at net.corda.core.serialization.CordaClassResolver.getRegistration(CordaClassResolver.kt:31) ~[core-0.11.0.jar:?]
        at com.esotericsoftware.kryo.Kryo.getRegistration(Kryo.java:488) ~[kryo-4.0.0.jar:?]
        at com.esotericsoftware.kryo.util.DefaultClassResolver.writeClass(DefaultClassResolver.java:97) ~[kryo-4.0.0.jar:?]
        at com.esotericsoftware.kryo.Kryo.writeClass(Kryo.java:540) ~[kryo-4.0.0.jar:?]
        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:645) ~[kryo-4.0.0.jar:?]
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:100) ~[kryo-4.0.0.jar:?]
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:40) ~[kryo-4.0.0.jar:?]
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575) ~[kryo-4.0.0.jar:?]
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80) ~[kryo-4.0.0.jar:?]
        at com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.write(CompatibleFieldSerializer.java:66) ~[kryo-4.0.0.jar:?]
        at com.esotericsoftware.kryo.Kryo.writeObjectOrNull(Kryo.java:629) ~[kryo-4.0.0.jar:?]
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:87) ~[kryo-4.0.0.jar:?]
        at com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.write(CompatibleFieldSerializer.java:66) ~[kryo-4.0.0.jar:?]
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575) ~[kryo-4.0.0.jar:?]
        at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80) ~[kryo-4.0.0.jar:?]
        at com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.write(CompatibleFieldSerializer.java:66) ~[kryo-4.0.0.jar:?]
        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:651) ~[kryo-4.0.0.jar:?]
        at net.corda.core.serialization.KryoKt.serialize(Kryo.kt:151) ~[core-0.11.0.jar:?]
        at net.corda.core.serialization.KryoKt$serialize$1.execute(Kryo.kt:144) ~[core-0.11.0.jar:?]
        at net.corda.core.serialization.KryoKt$serialize$1.execute(Kryo.kt) ~[core-0.11.0.jar:?]
        at com.esotericsoftware.kryo.pool.KryoPoolQueueImpl.run(KryoPoolQueueImpl.java:61) ~[kryo-4.0.0.jar:?]
        at net.corda.core.serialization.KryoKt.serialize(Kryo.kt:144) ~[core-0.11.0.jar:?]
        at net.corda.core.serialization.KryoKt.serialize$default(Kryo.kt:143) ~[core-0.11.0.jar:?]
        at net.corda.core.messaging.MessagingKt.send(Messaging.kt:152) ~[core-0.11.0.jar:?]
        at net.corda.core.messaging.MessagingKt.send$default(Messaging.kt:151) ~[core-0.11.0.jar:?]
        at net.corda.node.services.statemachine.StateMachineManager.sendSessionMessage(StateMachineManager.kt:559) ~[node-0.11.0.jar:?]
        at net.corda.node.services.statemachine.StateMachineManager.endSession(StateMachineManager.kt:465) ~[node-0.11.0.jar:?]
        at net.corda.node.services.statemachine.StateMachineManager.access$endSession(StateMachineManager.kt:70) ~[node-0.11.0.jar:?]
        at net.corda.node.services.statemachine.StateMachineManager$endAllFiberSessions$1.test(StateMachineManager.kt:443) ~[node-0.11.0.jar:?]
        at net.corda.node.services.statemachine.StateMachineManager$endAllFiberSessions$1.test(StateMachineManager.kt:70) ~[node-0.11.0.jar:?]
        at java.util.Collection.removeIf(Collection.java:414) ~[?:1.8.0_131]
        at net.corda.node.services.statemachine.StateMachineManager.endAllFiberSessions(StateMachineManager.kt:441) ~[node-0.11.0.jar:?]
        at net.corda.node.services.statemachine.StateMachineManager.access$endAllFiberSessions(StateMachineManager.kt:70) ~[node-0.11.0.jar:?]
        at net.corda.node.services.statemachine.StateMachineManager$initFiber$2.invoke(StateMachineManager.kt:425) ~[node-0.11.0.jar:?]
        at net.corda.node.services.statemachine.StateMachineManager$initFiber$2.invoke(StateMachineManager.kt:70) ~[node-0.11.0.jar:?]
        at net.corda.node.services.statemachine.FlowStateMachineImpl.processException(FlowStateMachineImpl.kt:161) ~[node-0.11.0.jar:?]
        at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:132) ~[node-0.11.0.jar:?]
        at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:41) ~[node-0.11.0.jar:?]
        at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1067) [quasar-core-0.7.6-jdk8.jar:0.7.6]
        at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:767) [quasar-core-0.7.6-jdk8.jar:0.7.6]
        at co.paralleluniverse.fibers.RunnableFiberTask.doExec(RunnableFiberTask.java:100) [quasar-core-0.7.6-jdk8.jar:0.7.6]
        at co.paralleluniverse.fibers.RunnableFiberTask.run(RunnableFiberTask.java:91) [quasar-core-0.7.6-jdk8.jar:0.7.6]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
```

Action points:
1) if we fail to serialise the exception in the session end message, just send a dummy/empty exception instead of propagating the problem, that way the underlying issue isn't hidden.
2) make LedgerTransaction not tagged as serialisable.
3) take the LedgerTransaction field out of TransactionVerificationException

**Comment by shamsasari** [comment]
Fix merged into master.
