### ISSUE TITLE
Hibernate sometimes attempts to clone objects via Java serialisation, which is prohibited

### ISSUE THREAD

**Issue by rick-r3** [corda/corda#702]
A user was experiencing this stack trace below.  It appears that during persistence, Hibernate makes a determination as to whether the object to be persisted is mutable and will attempt to clone it if so.  As part of that process, it can end up using Java serialisation in some circumstances to clone via serialisation and the deserialisation.  Since we have expressly forbid this in the node, we need to find a work around.

Ideally we do not want these objects to be cloned, since we know they are not going to get updated and it will slow performance to be cloning them.

```
rx.exceptions.OnErrorNotImplementedException: org.hibernate.type.SerializationException: could not deserialize
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:216) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.subjects.PublishSubject.onNext(PublishSubject.java:72) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.util.ObserverSubscriber.onNext(ObserverSubscriber.java:34) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.subjects.PublishSubject.onNext(PublishSubject.java:72) ~[rxjava-1.2.4.jar:1.2.4]
	at net.corda.node.services.vault.NodeVaultService.notifyAll(NodeVaultService.kt:234) ~[node-0.11.0.jar:?]
	at net.corda.node.services.api.ServiceHubInternal.recordTransactionsInternal$node_main(ServiceHubInternal.kt:65) ~[node-0.11.0.jar:?]
	at net.corda.node.internal.AbstractNode$services$1$recordTransactions$1.invoke(AbstractNode.kt:147) ~[node-0.11.0.jar:?]
	at net.corda.node.internal.AbstractNode$services$1$recordTransactions$1.invoke(AbstractNode.kt:114) ~[node-0.11.0.jar:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:54) ~[exposed-0.5.0.jar:?]
	at net.corda.node.utilities.DatabaseSupportKt.transaction(DatabaseSupport.kt:42) ~[node-0.11.0.jar:?]
	at net.corda.node.internal.AbstractNode$services$1.recordTransactions(AbstractNode.kt:146) ~[node-0.11.0.jar:?]
	at net.corda.core.node.ServiceHub$DefaultImpls.recordTransactions(ServiceHub.kt:67) ~[core-0.11.0.jar:?]
	at net.corda.core.node.PluginServiceHub$DefaultImpls.recordTransactions(PluginServiceHub.kt) ~[core-0.11.0.jar:?]
	at net.corda.node.services.api.ServiceHubInternal.recordTransactions(ServiceHubInternal.kt:41) ~[node-0.11.0.jar:?]
	at com.template.flow.InvoiceFlow$Initiator.call(InvoiceFlow.kt:45) ~[main/:?]
	at com.template.flow.InvoiceFlow$Initiator.call(InvoiceFlow.kt:21) ~[main/:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:127) [node-0.11.0.jar:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:41) [node-0.11.0.jar:?]
	at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1067) [quasar-core-0.7.6-jdk8.jar:0.7.6]
	at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:767) [quasar-core-0.7.6-jdk8.jar:0.7.6]
	at co.paralleluniverse.fibers.RunnableFiberTask.doExec(RunnableFiberTask.java:100) [quasar-core-0.7.6-jdk8.jar:0.7.6]
	at co.paralleluniverse.fibers.RunnableFiberTask.run(RunnableFiberTask.java:91) [quasar-core-0.7.6-jdk8.jar:0.7.6]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at net.corda.node.utilities.AffinityExecutor$ServiceAffinityExecutor$1$thread$1.run(AffinityExecutor.kt:69) [node-0.11.0.jar:?]
Caused by: javax.persistence.PersistenceException: org.hibernate.type.SerializationException: could not deserialize
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:147) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:155) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:162) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:780) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:758) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at net.corda.node.services.schema.HibernateObserver.persistStateWithSchema(HibernateObserver.kt:97) ~[node-0.11.0.jar:?]
	at net.corda.node.services.schema.HibernateObserver.persistState(HibernateObserver.kt:84) ~[node-0.11.0.jar:?]
	at net.corda.node.services.schema.HibernateObserver.persist(HibernateObserver.kt:77) ~[node-0.11.0.jar:?]
	at net.corda.node.services.schema.HibernateObserver.access$persist(HibernateObserver.kt:32) ~[node-0.11.0.jar:?]
	at net.corda.node.services.schema.HibernateObserver$3.call(HibernateObserver.kt:44) ~[node-0.11.0.jar:?]
	at net.corda.node.services.schema.HibernateObserver$3.call(HibernateObserver.kt:32) ~[node-0.11.0.jar:?]
	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134) ~[rxjava-1.2.4.jar:1.2.4]
	... 33 more
Caused by: org.hibernate.type.SerializationException: could not deserialize
	at org.hibernate.internal.util.SerializationHelper.doDeserialize(SerializationHelper.java:231) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.internal.util.SerializationHelper.deserialize(SerializationHelper.java:287) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.internal.util.SerializationHelper.clone(SerializationHelper.java:75) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.type.descriptor.java.SerializableTypeDescriptor$SerializableMutabilityPlan.deepCopyNotNull(SerializableTypeDescriptor.java:42) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.type.descriptor.java.SerializableTypeDescriptor$SerializableMutabilityPlan.deepCopyNotNull(SerializableTypeDescriptor.java:31) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.type.descriptor.java.MutableMutabilityPlan.deepCopy(MutableMutabilityPlan.java:35) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.type.AbstractStandardBasicType.deepCopy(AbstractStandardBasicType.java:306) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.type.AbstractStandardBasicType.deepCopy(AbstractStandardBasicType.java:302) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.type.TypeHelper.deepCopy(TypeHelper.java:53) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:267) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:182) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:125) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:189) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:132) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:58) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:773) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:758) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at net.corda.node.services.schema.HibernateObserver.persistStateWithSchema(HibernateObserver.kt:97) ~[node-0.11.0.jar:?]
	at net.corda.node.services.schema.HibernateObserver.persistState(HibernateObserver.kt:84) ~[node-0.11.0.jar:?]
	at net.corda.node.services.schema.HibernateObserver.persist(HibernateObserver.kt:77) ~[node-0.11.0.jar:?]
	at net.corda.node.services.schema.HibernateObserver.access$persist(HibernateObserver.kt:32) ~[node-0.11.0.jar:?]
	at net.corda.node.services.schema.HibernateObserver$3.call(HibernateObserver.kt:44) ~[node-0.11.0.jar:?]
	at net.corda.node.services.schema.HibernateObserver$3.call(HibernateObserver.kt:32) ~[node-0.11.0.jar:?]
	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134) ~[rxjava-1.2.4.jar:1.2.4]
	... 33 more
Caused by: java.io.InvalidClassException: filter status: REJECTED
	at java.io.ObjectInputStream.filterCheck(ObjectInputStream.java:1244) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1832) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1713) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1829) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1713) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1986) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422) ~[?:1.8.0_121]
	at org.hibernate.internal.util.SerializationHelper.doDeserialize(SerializationHelper.java:225) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.internal.util.SerializationHelper.deserialize(SerializationHelper.java:287) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.internal.util.SerializationHelper.clone(SerializationHelper.java:75) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.type.descriptor.java.SerializableTypeDescriptor$SerializableMutabilityPlan.deepCopyNotNull(SerializableTypeDescriptor.java:42) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.type.descriptor.java.SerializableTypeDescriptor$SerializableMutabilityPlan.deepCopyNotNull(SerializableTypeDescriptor.java:31) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.type.descriptor.java.MutableMutabilityPlan.deepCopy(MutableMutabilityPlan.java:35) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.type.AbstractStandardBasicType.deepCopy(AbstractStandardBasicType.java:306) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.type.AbstractStandardBasicType.deepCopy(AbstractStandardBasicType.java:302) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.type.TypeHelper.deepCopy(TypeHelper.java:53) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:267) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:182) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:125) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:189) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:132) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:58) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:773) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:758) ~[hibernate-core-5.2.6.Final.jar:5.2.6.Final]
	at net.corda.node.services.schema.HibernateObserver.persistStateWithSchema(HibernateObserver.kt:97) ~[node-0.11.0.jar:?]
	at net.corda.node.services.schema.HibernateObserver.persistState(HibernateObserver.kt:84) ~[node-0.11.0.jar:?]
	at net.corda.node.services.schema.HibernateObserver.persist(HibernateObserver.kt:77) ~[node-0.11.0.jar:?]
	at net.corda.node.services.schema.HibernateObserver.access$persist(HibernateObserver.kt:32) ~[node-0.11.0.jar:?]
	at net.corda.node.services.schema.HibernateObserver$3.call(HibernateObserver.kt:44) ~[node-0.11.0.jar:?]
	at net.corda.node.services.schema.HibernateObserver$3.call(HibernateObserver.kt:32) ~[node-0.11.0.jar:?]
	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134) ~[rxjava-1.2.4.jar:1.2.4]
	... 33 more
E 06:44:52 97 AbstractFuture.executeListener - RuntimeException while executing runnable net.corda.core.Utils$sam$Runnable$1a22f03a@6e664747 with executor MoreExecutors.directExecutor()
 rx.exceptions.OnErrorNotImplementedException: Failed to serialize what in net.corda.nodeapi.MarshalledObservation
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:216) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OperatorMaterialize$ParentSubscriber.drain(OperatorMaterialize.java:148) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.internal.operators.OperatorMaterialize$ParentSubscriber.onError(OperatorMaterialize.java:107) ~[rxjava-1.2.4.jar:1.2.4]
	at net.corda.core.Utils$toObservable$1$2.invoke(Utils.kt:126) ~[core-0.11.0.jar:?]
	at net.corda.core.Utils$toObservable$1$2.invoke(Utils.kt) ~[core-0.11.0.jar:?]
	at net.corda.core.Utils$failure$1.invoke(Utils.kt:100) ~[core-0.11.0.jar:?]
	at net.corda.core.Utils$failure$1.invoke(Utils.kt) ~[core-0.11.0.jar:?]
	at net.corda.core.Utils$sam$Runnable$1a22f03a.run(Utils.kt) ~[core-0.11.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[guava-21.0.jar:?]
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:902) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:813) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:677) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.SettableFuture.setException(SettableFuture.java:54) [guava-21.0.jar:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.processException(FlowStateMachineImpl.kt:162) [node-0.11.0.jar:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:138) [node-0.11.0.jar:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:41) [node-0.11.0.jar:?]
	at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1067) [quasar-core-0.7.6-jdk8.jar:0.7.6]
	at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:767) [quasar-core-0.7.6-jdk8.jar:0.7.6]
	at co.paralleluniverse.fibers.RunnableFiberTask.doExec(RunnableFiberTask.java:100) [quasar-core-0.7.6-jdk8.jar:0.7.6]
	at co.paralleluniverse.fibers.RunnableFiberTask.run(RunnableFiberTask.java:91) [quasar-core-0.7.6-jdk8.jar:0.7.6]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at net.corda.node.utilities.AffinityExecutor$ServiceAffinityExecutor$1$thread$1.run(AffinityExecutor.kt:69) [node-0.11.0.jar:?]
Caused by: java.lang.IllegalStateException: Failed to serialize what in net.corda.nodeapi.MarshalledObservation
	at net.corda.core.serialization.ImmutableClassSerializer.write(Kryo.kt:193) ~[core-0.11.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:651) ~[kryo-4.0.0.jar:?]
	at net.corda.core.serialization.KryoKt.serialize(Kryo.kt:151) ~[core-0.11.0.jar:?]
	at net.corda.core.serialization.KryoKt.serialize$default(Kryo.kt:147) ~[core-0.11.0.jar:?]
	at net.corda.node.services.messaging.RPCDispatcher$ObservableSerializer$write$subscription$1.call(RPCDispatcher.kt:74) ~[node-0.11.0.jar:?]
	at net.corda.node.services.messaging.RPCDispatcher$ObservableSerializer$write$subscription$1.call(RPCDispatcher.kt:55) ~[node-0.11.0.jar:?]
	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134) ~[rxjava-1.2.4.jar:1.2.4]
	
	... 26 more
	Caused by: com.esotericsoftware.kryo.KryoException: Class javax.persistence.PersistenceException is not annotated or on the whitelist, so cannot be used in serialization
Serialization trace:
cause (rx.exceptions.OnErrorNotImplementedException)
throwable (rx.Notification)
	at net.corda.core.serialization.CordaClassResolver.checkClass(CordaClassResolver.kt:60) ~[core-0.11.0.jar:?]
	at net.corda.core.serialization.CordaClassResolver.getRegistration(CordaClassResolver.kt:31) ~[core-0.11.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.getRegistration(Kryo.java:488) ~[kryo-4.0.0.jar:?]
	at net.corda.nodeapi.RPCKryo.getRegistration(RPCStructures.kt:139) ~[node-api-0.11.0.jar:?]
	at com.esotericsoftware.kryo.util.DefaultClassResolver.writeClass(DefaultClassResolver.java:97) ~[kryo-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeClass(Kryo.java:540) ~[kryo-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:76) ~[kryo-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.write(CompatibleFieldSerializer.java:66) ~[kryo-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575) ~[kryo-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80) ~[kryo-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.write(CompatibleFieldSerializer.java:66) ~[kryo-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:651) ~[kryo-4.0.0.jar:?]
	at net.corda.core.serialization.ImmutableClassSerializer.write(Kryo.kt:191) ~[core-0.11.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:651) ~[kryo-4.0.0.jar:?]
	at net.corda.core.serialization.KryoKt.serialize(Kryo.kt:151) ~[core-0.11.0.jar:?]
	at net.corda.core.serialization.KryoKt.serialize$default(Kryo.kt:147) ~[core-0.11.0.jar:?]
	at net.corda.node.services.messaging.RPCDispatcher$ObservableSerializer$write$subscription$1.call(RPCDispatcher.kt:74) ~[node-0.11.0.jar:?]
	at net.corda.node.services.messaging.RPCDispatcher$ObservableSerializer$write$subscription$1.call(RPCDispatcher.kt:55) ~[node-0.11.0.jar:?]
	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39) ~[rxjava-1.2.4.jar:1.2.4]
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134) ~[rxjava-1.2.4.jar:1.2.4]
	... 26 more
```

**Comment by rick-r3** [comment]
It looks as though there's perhaps some support for immutability in the form of `org.hibernate.annotations.Immutable` annotation on entities.

**Comment by joeldudleyr3** [comment]
See https://r3-cev.atlassian.net/browse/CORDA-1392.

**Comment by joeldudleyr3** [comment]
This is affecting users. See https://stackoverflow.com/questions/49605350/does-corda-persist-java-time-data-type.

**Comment by joeldudleyr3** [comment]
This is fixed.
