### ISSUE TITLE
Cash app needs updating to new notary selection API once designed and implemented

### ISSUE THREAD

**Issue by ediphy-cmurphy** [corda/corda#768]
Attempted to issue cash and got the following stacktrace after explorer window for that issuer was blown away (I suspect it is because I nominated multiple notaries):

java.lang.IllegalArgumentException: Collection contains more than one matching element.
	at net.corda.core.node.NodeInfo.getNotaryIdentity(NodeInfo.kt:37)
	at net.corda.explorer.views.cordapps.cash.NewTransaction$newTransactionDialog$$inlined$apply$lambda$1.call(NewTransaction.kt:148)
	at net.corda.explorer.views.cordapps.cash.NewTransaction$newTransactionDialog$$inlined$apply$lambda$1.call(NewTransaction.kt:44)
	at javafx.scene.control.Dialog.impl_setResultAndClose(Dialog.java:1026)
	at javafx.scene.control.DialogPane.lambda$createButton$599(DialogPane.java:777)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8413)
	at javafx.scene.control.Button.fire(Button.java:185)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.mac.MacApplication._enterNestedEventLoopImpl(Native Method)
	at com.sun.glass.ui.mac.MacApplication._enterNestedEventLoop(MacApplication.java:109)
	at com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:511)
	at com.sun.glass.ui.EventLoop.enter(EventLoop.java:107)
	at com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:590)
	at javafx.stage.Stage.showAndWait(Stage.java:474)
	at javafx.scene.control.HeavyweightDialog.showAndWait(HeavyweightDialog.java:162)
	at javafx.scene.control.Dialog.showAndWait(Dialog.java:341)
	at net.corda.explorer.views.cordapps.cash.NewTransaction.show(NewTransaction.kt:86)
	at net.corda.explorer.views.cordapps.cash.CashViewer$1$1$1.handle(CashViewer.kt:152)
	at net.corda.explorer.views.cordapps.cash.CashViewer$1$1$1.handle(CashViewer.kt:42)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)

**Comment by mikehearn** [comment]
Yep, that's right.

The current API has two ways to select a notary. Get all of them (and then the cash app assumes there's just one), or get any notary from the list. Neither really makes sense - most likely people will want to specifically control which notaries are used, either end users will want to control it, or it'll be managed by the network operator. But picking a random notary from the list or insisting there's only one is not correct.

We have a task on our plate that we were discussing at a planning meeting yesterday to pick, design and build a notary (and oracle) selection API for v1.0 - @adagys is working on it.

**Comment by ediphy-cmurphy** [comment]
After restarting and only appointing one notary I notice some further
unexpected behaviour. I have a setup with Notary, BoBT, BoBA and BoB in
your standard setup. I send money from BoBA to BoBT and I don't expect BoB
to have any knowledge of this transaction, yet the details of it appear in
the Transactions tab of the Bank of Baguettes GUI. Am I missing something
here?

**Comment by gendal** [comment]
Who was the issuer of the cash you paid from BoBA to BoBT?

**Comment by ediphy-cmurphy** [comment]
BoBT.

**Comment by gendal** [comment]
That's really weird.  I would expect the history of the asset to appear in the BoB transactions view if the cash was subsequently paid on to BoB (as BoB would need to validate the chain of custody).  But cash issued by BoBT to BoBA and then paid back (presumably? assuming I'm understanding your scenario correctly) to BoBT shouldn't go anywhere near BoB.  Let me try to reproduce...  you have me intrigued...

**Comment by gendal** [comment]
I've just done the following:

BoBT: Issue 1M GBP to BoBA
BoBA: Pay 1M GBP (issued by BoBT) to BoBT
BoB: look at Transactions list.  Nothing showing.

Was there anything else in your scenario that I missed?

**Comment by ediphy-cmurphy** [comment]
Let me look again at exactly what I did. It may be that I had BoB earlier
in in the chain. Will check and revert.

**Comment by ediphy-cmurphy** [comment]
So I looked at this again and I think I had made a few other steps besides
what you describe:

BoBT: Issue 1M GBP to BoBT

BoBT: Pay 200k GBP (issued by BoBT) to BoBA

BoBT: Pay 300k GBP (issued by BoBT) to BoB

BoB: look at Transactions list and see the 200k transaction which I didn't
expect as it was never party to any of the cash in that history.

**Comment by gendal** [comment]
Hi Chris,

Thanks.  This helps.

Yes - this seems plausible.  I'm afraid the underlying issue is an unavoidable consequence of the tradeoffs inherent in this space: if we're happy for the issuer to reissue (or countersign) every transaction that moves money they've issued then this problem goes away.  But if we want the ability for cash to move freely then the recipient needs to be able to examine a chain of evidence that leads from the payment to them all the way back to the original issuance of the cash by the issuer.  Otherwise, they have no way of being able to evidence that they do indeed have an enforceable claim against said issuer.

By default, for simplicity, in the explorer, an issuance (of any amount) is modelled as a single action: a single object is created representing the 1M GBP claim against BoBT.  

So, when you paid 200k of it to BoBA, we needed to account for the 800k that remained owned by BoBT, right?  You can think of the 800k as being the "change" from a 1M note.

So from that original 1M object, two new ones were created... one representing a 200k claim held by BoBA and a new 800k one representing the reduced amount now owned by BoBT.   This action is performed through a Corda transaction.

It was from that 800k that the payment to BoB was made.

So when BoB examined its history, it saw that the 800k came into existence as a result of the 1M being broken into 200k and 800k pieces.  And hence your observation.

There are a number of ways of fixing this in "real" scenarios.  In short, they include:  1) issuing cash in smaller "denominations", 2) having the issuer countersign/reissue to avoid the need to walk the chain back, 3) anonymising the parties so you learn the history but not who participated, 4) hardware techniques, and more.

We've already implemented some of these (although not yet visible in the explorer) and more are coming.

You will, I am sure, be wondering why we modelled it this way!  Couldn't we have just maintained a balance?  Like a big shared spreadsheet in the cloud that recorded how much had been issued by BoBT and how much was owned by each bank.... with the balances being updated with each transaction?

Yes... and Corda can support this.  But to do that would require that shared table to be visible to ALL participants.  Which would destroy privacy entirely.  The advantage of the (seemingly) unusual approach we use in Corda is that, when fully implemented, it provides a framework over which the other techniques I outlined above can be applied...  in a way that simply isn't possible with the "spreadsheet in the sky" model used by some other platforms.

Hope this helps... would love to whiteboard it with you in person some time.

**Comment by mikehearn** [comment]
Guys let's split this issue - irrelevant dependency transactions appearing in the Explorer is a separate bug we should fix. The underlying issue of seeing transactions that aren't do to with you are already being worked on with:

1. The confidential identities feature that's being merged now. This will strip such transactions of their identity data, like Bitcoin.
2. The project we discussed at the AWG call the other day and will soon be discussing publicly.

So we are well aware of the privacy issues blockchain systems have, the Explorer is merely showing them (it's acting a bit like a block explorer at the moment), and we have plans to address them fully and to the satisfaction of everyone. I'll open up a separate issue for the Explorer UI issue.

**Comment by mikehearn** [comment]
I filed https://github.com/corda/corda/issues/786 for the UI issue.

**Comment by ediphy-cmurphy** [comment]
Thanks both.

The bit I was missing was the atomicity of the issuance process - that each
block of issuance creates the link to all subsequent transactions no matter
which branch they are on. This is clearly problematic, but, as you both
explain, you are working on solutions to that.

I am starting to collate more questions as I delve deeper - would be good
to arrange a time to sit down in person over the next couple of weeks. I am
up in town most days and have an office just near you near the Guildhall so
let me know if you can spare an hour or so.

Cheers,

Chris.

**Comment by gendal** [comment]
Thanks Chris.  I'll follow up via email to arrange a meeting.
