### ISSUE TITLE
Paths.get("").normalize() throws ArrayIndexOutOfBoundsException when using Oracle JDK 8u20. 

### ISSUE THREAD

**Issue by roger3cev** [corda/corda#83]
Node fails to start when using Oracle JDK 8u20. 

`Paths.get("").normalize()` throws `ArrayIndexOutOfBoundsException`. This is a documented bug: 
http://bugs.java.com/view_bug.do?bug_id=8042751

Stack trace:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
  at sun.nio.fs.UnixPath.normalize(UnixPath.java:508)
  at net.corda.node.services.config.ConfigHelper.loadConfig(ConfigUtilities.kt:34)
  at net.corda.node.services.config.ConfigHelper.loadConfig$default(ConfigUtilities.kt:30)
  at net.corda.node.MainKt.main(Main.kt:74)
```

Solution is to upgrade JDK above version 1.8.0_20. Suggest we catch this exception and print the solution to screen -> `Upgrade JDK above version 1.8.0_20` or something.

**Comment by Clintonio** [comment]
Should we perhaps change the docs to require JDK 8u21? The docs already recommend the latest version possible.
