### ISSUE TITLE
Error starting DemoBench for Beta/M12

### ISSUE THREAD

**Issue by sjwwebster** [corda/corda#853]
a) Started Demobench and brought up Notary as first node

--- Corda Open Source 0.12.1 (4bae70a) -----------------------------------------------

New! Training now available worldwide, see https://corda.net/corda-training/

Logs can be found in                    : /Users/simon/demobench/20170615105918/notary/logs
Database connection url is              : jdbc:h2:tcp://localhost:10003/node
Listening on address                    : localhost:10000
RPC service listening on address        : localhost:10001
Providing network services              : corda.notary.simple, corda.notary.validating
Node for "Notary" started up and registered in 6.0 sec

Welcome to the Corda interactive shell.
Useful commands include 'help' to see what is available, and 'bye' to shut down the node.

b) Tried to start up the next node as follows but it never starts 

--- Corda Open Source 0.12.1 (4bae70a) -----------------------------------------------

New! Training now available worldwide, see https://corda.net/corda-training/

Logs can be found in                    : /Users/simon/demobench/20170615105918/bankofbreakfasttea/logs
Database connection url is              : jdbc:h2:tcp://localhost:10007/node
Listening on address                    : [0:0:0:0:0:0:0:1:61883]:10004
RPC service listening on address        : localhost:10005
Providing network services              : corda.issuer.GBP
Loaded plugins                          : net.corda.bank.plugin.BankOfCordaPlugin

c) Error appears in the notary screen

E 11:02:30 [Thread-9 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$3@482942d8-411425835)] core.client.createConnection - AMQ214016: Failed to create netty connection
 java.net.UnknownHostException: 0:0:0:0:0:0:0:1:61883: invalid IPv6 address
        at java.net.InetAddress.getAllByName(InetAddress.java:1169) ~[?:1.8.0_152-ea]
        at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[?:1.8.0_152-ea]
        at java.net.InetAddress.getByName(InetAddress.java:1076) ~[?:1.8.0_152-ea]
        at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:40) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:62) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:208) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:49) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:188) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:174) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:488) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:111) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:897) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:508) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:419) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:478) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152-ea]

**Comment by Clintonio** [comment]
Hi @sjwwebster 

It looks like you're having issues with an IPv6 address there. Is the issue still continuing for you?

Thanks,
Clint

**Comment by sjwwebster** [comment]
Hi Clinton  - yes still having this issue, tried downloading latest Demobench today, not change.

**Comment by joeldudleyr3** [comment]
Hi Simon. We weren't able to replicate this issue on Corda 3. I'm going to close it for now, but please re-open the issue if it occurs again on the latest version.
