### ISSUE TITLE
Node can fail to fully start when a port conflict occurs, without a useful error message

### ISSUE THREAD

**Issue by mikehearn** [corda/corda#86]
Example stack trace:

```
11:27:33.243 [QUIET] [system.out] E 11:27:33 1 Main.main - Exception during node startup
11:27:33.243 [QUIET] [system.out]  java.net.BindException: Address already in use
11:27:33.243 [QUIET] [system.out]   at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_92]
11:27:33.243 [QUIET] [system.out]   at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_92]
11:27:33.243 [QUIET] [system.out]   at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_92]
11:27:33.243 [QUIET] [system.out]   at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_92]
11:27:33.243 [QUIET] [system.out]   at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:1.8.0_92]
11:27:33.243 [QUIET] [system.out]   at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:125) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
11:27:33.243 [QUIET] [system.out]   at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:501) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
11:27:33.243 [QUIET] [system.out]   at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1218) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
11:27:33.243 [QUIET] [system.out]   at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:505) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
11:27:33.244 [QUIET] [system.out]   at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:490) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
11:27:33.244 [QUIET] [system.out]   at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:965) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
11:27:33.244 [QUIET] [system.out]   at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:210) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
11:27:33.244 [QUIET] [system.out]   at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:353) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
11:27:33.244 [QUIET] [system.out]   at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:408) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
11:27:33.244 [QUIET] [system.out]   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:402) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
11:27:33.244 [QUIET] [system.out]   at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
11:27:33.244 [QUIET] [system.out]   at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_92]
```

**Comment by thorstenhirsch** [comment]
I just stumbled upon this problem when building M12.1 ("Building 22% > ... > 137 tests completed"). The test is hanging in a loop. After not being able to initialise AMQP due to the port conflict, the receiving part of this test case throws an AMQP timeout error, but it does not exit the test case (which is another problem).

On my machine the port conflict was caused by Jetbrains RubyMine.

So if neither AMQP nor netty throw an error message with the conflicting port/application, maybe Corda can figure that out and throw a better error message. I propose to do that in a BindExceptionHandler, so that the additional work is only being done when this specific error has occurred.

**Comment by joeldudleyr3** [comment]
See https://r3-cev.atlassian.net/browse/CORDA-1394.
